### ISSUE TITLE
Implement message queue/broker for high volume requests

### ISSUE THREAD

**Issue by alokbabu** [IEEEKeralaSection/rescuekerala#101]
We need message queuing for high volume requests like "request for help".

**Comment by kuism** [comment]
Is anyone working on this?

**Comment by alokbabu** [comment]
I dont think so. Heard the scaling is under control at the moment. So might not be necessary at the moment. But can kept this open and watched.

**Comment by kuism** [comment]
Let me know if there are any high priority issues

**Comment by naveenpf** [comment]
Already implemented
