### ISSUE TITLE
HospitalView needs a search bar.

### ISSUE THREAD

**Issue by rejuls** [IEEEKeralaSection/rescuekerala#1014]
The Hospital page needs a search bar as there are 400 entries which are not sorted district wise.

**Comment by shamseena-dev** [comment]
In the hospital view, it would be better to sort out ,  if added one more column - "District" for the table.

Adding this comment here , since this issue seems to be similar.

**Comment by R-Aravind** [comment]
@shamseena-dev 	or it would be better to have dropdown of districts and on selecting the district, we can view the hospitals in that district. 
Similiar to the View registered voluteers page.

**Comment by jerinisready** [comment]
@biswaz  are you doing this or could I start this?

**Comment by biswaz** [comment]
doing
