### ISSUE TITLE
Could not resolve DNS to find Ushahidi volunteer portal

### ISSUE THREAD

**Issue by kaiiyer** [IEEEKeralaSection/rescuekerala#1016]
### Subject of the issue
DNS Error 1016 

Do not have a matching DNS record inside the Cloudflare DNS settings. So cannot resolve the address which should direct to Ushahidi volunteer portal.

https://volunteers.keralarescue.in/
### Your environment
* Firefox 65
* Linux

### Steps to reproduce
Visit https://volunteers.keralarescue.in/

**Comment by tomahawk-pilot** [comment]
that site is decommissioned.  and now redirected to https://help.keralarescue.in
