### ISSUE TITLE
Give More Exposure to Announcements

### ISSUE THREAD

**Issue by shamseena-dev** [IEEEKeralaSection/rescuekerala#1017]
### Subject of the issue
The "Announcement section" in the Home page  needs to be given more exposure. 
Rather than listing it among the other sections in the Home page, would be better if displayed on top of the page as a badge or using some highlighter.
And within the Announcement page , the each  announcement listing could be given a heading ,or use some hashtags on top (for eg: #Ernakulam #relief camps, etc) ,add  social media  share buttons for easy sharing of messages. The priority levels (coloring code) marked could also be improved , cant figure out it for a layman user. Right now, its hardly noticeable.

**Comment by Aswinpookkatt** [comment]
I will work on the issue.

**Comment by abhiramr** [comment]
@Aswinpookkatt  Do you need help with this?

**Comment by Aswinpookkatt** [comment]
@abhiramr sure any help is welcome.

**Comment by abhiramr** [comment]
@Aswinpookkatt  Can you ping me on the Slack group? - Abhiram Ramesh

**Comment by jerinisready** [comment]
am at slack now. do you want any help over that?

**Comment by subins2000** [comment]
@Aswinpookkatt I can add a noticeable header banner in the home page. Meanwhile you can work on the tags and stuff ?

**Comment by mankidavu** [comment]
Is this done or still waiting for more testing before merge?

**Comment by subins2000** [comment]
@mankidavu #1022 & #1023 fixes a part of the issue. More work needs to be done for fixing this.

**Comment by mankidavu** [comment]
As this is a top priority item, can we get few more volunteers with necessary skills to fix it quickly and merge?

**Comment by subins2000** [comment]
@mankidavu @abhiramr is working on it at the moment (the tags for each announcement)

**Comment by abhiramr** [comment]
@mankidavu Working on tags right now. Will ask asap if extra hands are needed. 
It will help if you can provide more info on what sort of announcements are required in addition to what the above two PRs have + description in this issue?

WRT 
>  lots of rumours floating around on my school and college groups. Like minor landslides with no causalities. People stuck ,but safe and waiting for water to recede etc.

Any thoughts on how this can be announced better?

**Comment by mankidavu** [comment]
<snip>...</snip>
> 
> WRT
> 
> > lots of rumours floating around on my school and college groups. Like minor landslides with no causalities. People stuck ,but safe and waiting for water to recede etc.
> 
> Any thoughts on how this can be announced better?

Earlier today I saw a gif file created by someone indicating the excess waterflow towards CIAL airport. It happened almost exactly as it is at a later stage. I'm sure we can create such 3D models over map data easily and make a simple gif file. That will make people understand it better, once shared through our announcement area. Let me dig that particular gif.

**Comment by vishnubvinod0602** [comment]
A dedicated team has to be assigned to contact the kseb officials inorder to confirm the opening of dams and they should be able to report us through a online tab there by it could be added to the announcement area inorder to reduce the fake news

**Comment by abhiramr** [comment]
The PR https://github.com/IEEEKeralaSection/rescuekerala/pull/1022/commits/4650f7dd0d5537428d7f8a314851e044e8267b9c

now has code for Hashtags as well.

Comments with GIFs here - https://github.com/IEEEKeralaSection/rescuekerala/pull/1022
