### ISSUE TITLE
Contact Info Page is empty

### ISSUE THREAD

**Issue by R-Aravind** [IEEEKeralaSection/rescuekerala#1019]
### Subject of the issue
Contact Info page is empty
![image](https://user-images.githubusercontent.com/44097855/62794658-442a8500-baf2-11e9-8813-3d7523c6674a.png)

### Your environment
* Chrome
* Ubuntu

### Steps to reproduce
	Contact info > Select District

### Expected behaviour
	Display Contact info of volunteers/NGOs in that district

### Actual behaviour
	The table is empty.

**Comment by tomahawk-pilot** [comment]
we are updating it
