### ISSUE TITLE
Mobile no is integer field make it regex field or simply character

### ISSUE THREAD

**Issue by prajinprakash4u** [IEEEKeralaSection/rescuekerala#102]
https://github.com/IEEEKeralaSection/rescuekerala/blob/app/restendpoint/models.py
mobile no is integer field.

> Ensure this value is less than or equal to 2147483647.

**Comment by bobinson** [comment]
While testing keep in mind that people will be panicking and entering wrong numbers. Validations should not prevent people from entering numbers.

**Comment by sreenadh** [comment]
@bobinson how about #84

**Comment by prajinprakash4u** [comment]
regex is best at all take a look at
https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-phone-number-in-django-models

**Comment by vvishakhp** [comment]
All browsers now support an input type 'tel' which is used to enter telephone numbers. 

<input type="tel" placeholder="9876543210" pattern="\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$" >

**Comment by vvishakhp** [comment]
`<input type="tel" placeholder="9876543210" pattern="\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})[-. )]*(\d{3})[-. ]*(\d{4})(?: *x(\d+))?\s*$" >`

You can use this. 

This validates all major phone number formats even if it includes 'spaces' or '-'

**Comment by naveenpf** [comment]
Duplicate #84
