### ISSUE TITLE
Removing unused Data placeholders in the Announcement Page

### ISSUE THREAD

**Issue by athul** [IEEEKeralaSection/rescuekerala#1021]
### Subject of the issue
Some Rows in the Announcements tab is empty 
-------------
This maybe due to some discrepancy in the data in the db and should be removed as more priority announcements will be added in the near future. 
![Screenshot_20190809_222642_com android chrome](https://user-images.githubusercontent.com/40897573/62795862-52c66b80-baf5-11e9-9bfb-b43a7d73ab15.jpg)
If these are still left out more the build times might increase

**Comment by subins2000** [comment]
This has been done.

**Comment by athul** [comment]
Cool.. Closing this
