### ISSUE TITLE
pagination and filter district wise

### ISSUE THREAD

**Issue by tomahawk-pilot** [IEEEKeralaSection/rescuekerala#1024]
please add a filter and pagination for hospital data

**Comment by subins2000** [comment]
I'll work on this

**Comment by rejuls** [comment]
The raw data did not have district info. The model needs to be changed and the location of 100+ hospitals need to be found.

**Comment by subins2000** [comment]
@rejuls yeah, need a new district field or perhaps filter by Name or email ?
