### ISSUE TITLE
[Feature Request] A page with status of bus and train routes

### ISSUE THREAD

**Issue by AnandBaburajan** [IEEEKeralaSection/rescuekerala#1028]
### Subject of the issue
It'd be helpful if there's a page with a tool to check whether bus/train routes are okay or not.
People with information can verify and update the status of the routes and add remarks too.

Something similar to:
[TO dropdown] - [FROM dropdown] - [Select BUS / TRAIN]
[CHECK STATUS button]
=>
[Status: OKAY / NOT OKAY] - [As of: TIME + DATE] - [REMARKS]
[UPDATE STATUS button]

**Comment by vigneshhari** [comment]
I believe it will be better to give the status of routes that are canceled in the announcements, we will soon have tag-based announcements and we can tag travel announcements, Adding all bus routes and train routes and managing them separately will be quite a task now.

**Comment by AnandBaburajan** [comment]
Perhaps this can help in some way: https://www.gizmolead.com/keralaroutes/
Code: https://github.com/AnandBaburajan/route-status-for-kerala-floods

It uses PHP with JSON files and is fully functional. It's currently hosted on a test site (my blog).
Would this be helpful if used as an iframe on a page at keralarescue.in?

Thanks.

**Comment by biswaz** [comment]
@AnandBaburajan Thank you for making this website. But it doesn't have enough data to be used by the public. It feels more like a beta website to me. You can try to onboard people  from our slack channels.
