### ISSUE TITLE
Server error (500) in private collection center section

### ISSUE THREAD

**Issue by fasalmbt** [IEEEKeralaSection/rescuekerala#1038]
The private collection and relief center section is experiencing a server error (500)

![Screenshot from 2019-08-10 16-18-41](https://user-images.githubusercontent.com/20360708/62821014-0299e880-bb8b-11e9-93ab-03327949abfb.png)

**Comment by jojurajan** [comment]
@tomahawk-pilot Could we get the logs for this crash?

**Comment by tomahawk-pilot** [comment]
link of this page

**Comment by tomahawk-pilot** [comment]
https://keralarescue.in/collection_centers/inside_kerala/

**Comment by fasalmbt** [comment]
In both sections (out side kerala too )  . This error is happening 

https://www.keralarescue.in/collection_centers/outside_kerala

**Comment by vigneshhari** [comment]
The error is solved, The solution isn't deployed yet
