### ISSUE TITLE
View Status By Taluk Server Error 500

### ISSUE THREAD

**Issue by rakeshkr22** [IEEEKeralaSection/rescuekerala#1041]
### View Status By Taluk Server Error 500
In view Status By Taluk Page, After selecting District dropdown getting Server Error 500.

### Your environment
* Chrome Browser
* Windows OX

### Screen Shots
![image](https://user-images.githubusercontent.com/10681753/62821359-23653c80-bb91-11e9-9313-c5c7d90b5638.png)

First page 

![image](https://user-images.githubusercontent.com/10681753/62821371-3ed04780-bb91-11e9-9fa2-19ea44139dc2.png)

**Comment by naveenpf** [comment]
it is fixed . Can you check and close ?
