### ISSUE TITLE
[Feature Request] Add back to 'home' button to go back to keralarescue.in home page from Individual links.

### ISSUE THREAD

**Issue by jojyva** [IEEEKeralaSection/rescuekerala#1046]
###  Add back to 'home' button to go back to keralarescue.in home page from Individual links
There is no home button for volunteers entering data in Individual links of Kerala Rescue home page. Its confusing for folks (like volunteers) who have to enter multiple requests. 
### Your environment
Prod - all Browsers.

**Comment by vigneshhari** [comment]
could you give me a link ? as in a url where you seem to have this issue

**Comment by R-Aravind** [comment]
the kerala rescue logo at the top serves as a home button

**Comment by jojyva** [comment]
1) Open the URL - https://keralarescue.in/
2) Click on "Request for Rescue" link which will take you to https://keralarescuemap.ushahidi.io/posts/create/17
3) Once you enter the data and click submit, or before submitting if you need to go back to the home page (https://keralarescue.in/) there is no 'Back to home" button

**Comment by tomahawk-pilot** [comment]
@jojyva we cant implement it as Ushahidi is a saas platform. and we don't have access to the code there.
