### ISSUE TITLE
WhatsApp integration for keralarescue.in

### ISSUE THREAD

**Issue by ladvine** [IEEEKeralaSection/rescuekerala#1047]
### Integrate whatsapp to keralarescue.in
Directly send rescue/resource requests as whatsapp message. It will be processed and submitted to keralarescue.in

### Expected behaviour
1. Register as volunteer in keralarescue.in
2. Create WhatsApp groups adding the keralarescue.in whatsapp contact.
3. All whatsapp message received in keralarescue.in whatsapp contact should be processed, checked for any redundancy and submitted as request in keralarescue.in

**Comment by tomahawk-pilot** [comment]
cannot be implemented due to privacy issues .
