### ISSUE TITLE
change slack joinig link

### ISSUE THREAD

**Issue by tomahawk-pilot** [IEEEKeralaSection/rescuekerala#1048]
update slack link in homepage to http://bit.ly/rescuechat

**Comment by jerinisready** [comment]
earlier link is still working no?

**Comment by tomahawk-pilot** [comment]
the link expired

**Comment by tomahawk-pilot** [comment]
this is the new one

**Comment by jerinisready** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/pull/1049
