### ISSUE TITLE
Wrong location co-ordinates

### ISSUE THREAD

**Issue by nithinjos** [IEEEKeralaSection/rescuekerala#106]
Guys, noticed that many of the request raised are by friends or family of the affected and not by themselves, and hence the co-ordinates might not help. If passing the coordinates to the rescue team, please verify the co-ordinates and mentioned location.

In this case, features like #96 could slow the rescue process down. Please double check.

**Comment by irshadshalu** [comment]
Add a dialog asking whether user is requesting for self or another person before loading GPS?

This can be done in JS, but a BooleanField will be more effective in this case.

**Comment by nithinjos** [comment]
That would be better. I'll open a child issue.

**Comment by irshadshalu** [comment]
Done in #122
