### ISSUE TITLE
announcement api broken

### ISSUE THREAD

**Issue by tomahawk-pilot** [IEEEKeralaSection/rescuekerala#1060]
announcement api is broken. 
https://keralarescue.in/announcements/api
please fix it or move it something generic . like .in/api/announcements

**Comment by neerajmohan96** [comment]
I believe the issue is with the url. It seems  /announcements/api is clashing  with /announcements/`<string:filter>` in mainapp/urls.py

**Comment by bobinson** [comment]
fixed via https://github.com/neerajmohan96/rescuekerala/pull/1

**Comment by bobinson** [comment]
closed by mistake.

**Comment by vigneshhari** [comment]
https://keralarescue.in/api/announcements/api  Its still there working without any issues
