### ISSUE TITLE
Dynamic Meta Description for Sub Pages 

### ISSUE THREAD

**Issue by jino-qb** [IEEEKeralaSection/rescuekerala#1061]
### Subject of the issue
Describe your issue here.

When we share pages online it might be better to have a matching description which fits that page. Like for this URL: https://keralarescue.in/announcements/

It should be something like the following:
"Important Announcements regarding Kerala Rescue Operations"

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

GO to this URL: https://keralarescue.in/announcements/

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

Will have the description as in the following image
![IMG_20190811_002101](https://user-images.githubusercontent.com/36069124/62825745-26325280-bbce-11e9-887d-f34bbd49bc05.jpg)

### Actual behaviour
Tell us what happens instead or what went wrong

We should have a proper description which fits that page.

**Comment by jino-qb** [comment]
Hi Team,
I have started on this and raised [PR#1062](https://github.com/IEEEKeralaSection/rescuekerala/pull/1062)

Please suggest the where all we need description changes

**Comment by rejuls** [comment]
#1062 is merged and hence this can be closed. @jino-qb @tomahawk-pilot @biswaz
