### ISSUE TITLE
[Feature Request] Check status of bus routes

### ISSUE THREAD

**Issue by AnandBaburajan** [IEEEKeralaSection/rescuekerala#1071]
### Subject of the issue
This addresses the feature request issue: https://github.com/IEEEKeralaSection/rescuekerala/issues/1028, for checking status of routes.

Perhaps this can help in some way: https://www.gizmolead.com/keralaroutes/
Code: https://github.com/AnandBaburajan/route-status-for-kerala-floods
The routes are updated by the people, for the people.

It uses PHP with JSON files and is fully functional. It's currently hosted on a test site (my blog) and can be hosted somewhere else if needed.

Would this be helpful if used as an iframe on a page at keralarescue.in?

**Comment by tomahawk-pilot** [comment]
the sites need more data. can you update the contents

**Comment by AnandBaburajan** [comment]
Yes, I'll add some more affected routes connecting prominent locations.

**Comment by AnandBaburajan** [comment]
I've updated around 15 affected routes and a few good routes.
The rest of the routes can be voluntarily updated by people with info.
Is this good to go?

**Comment by rejuls** [comment]
The idea is nice and if we could set this up for bus and train routes, get enough publicity, it can help a lot of people. Most routes are okay now. For the future.

**Comment by AnandBaburajan** [comment]
Can we at least try to get it up and running?

**Comment by biswaz** [comment]
@AnandBaburajan Thank you for making this website. But it doesn't have enough data to be used by the public. It feels more like a beta website to me. You can try to onboard people  from our slack channels.
