### ISSUE TITLE
Correct App link

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#1072]
Correct App link
https://cdn.keralarescue.in/app/keralarescuecamp.apk

![image](https://user-images.githubusercontent.com/12662835/62832578-7224dc00-bc4e-11e9-9d3b-bd19f87d8c3d.png)

**Comment by justinjohnymathew** [comment]
Is there any direct playstore link?

**Comment by naveenpf** [comment]
no

**Comment by justinjohnymathew** [comment]
shall I update the link ?

**Comment by naveenpf** [comment]
yes
