### ISSUE TITLE
Update django-redis version

### ISSUE THREAD

**Issue by farisshajahan** [IEEEKeralaSection/rescuekerala#1079]
The current version of django-redis in the requirements.txt leads to a Invalid type: CacheKey error during CI checks as well as in the dev environment because Django passes the CacheKey object to redis. This is fixed in the newer version.

### Environment
* python3
* Linux (Ubuntu 18.04)

**Comment by bobinson** [comment]
>Environment

>    python3
>    Linux

It will be a good idea to share exact versions, OS flavors like Ubuntu etc to give more context.

**Comment by farisshajahan** [comment]
@bobinson
Added. But it d doesn't matter for this scenario though.
