### ISSUE TITLE
remove irrelvant information from the top of the landing page

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#108]
![image](https://user-images.githubusercontent.com/18070249/44204302-af57aa80-a16f-11e8-8bbc-89b7609c9bcf.png)

**Issue Description:** The text content being loaded on the top of the page is irrelvant to any one trying to request rescue. Note that Even I don't have network coverage. Those unwanted text can be moved to a about link to not to hurt anyone feelings.

**Severity:** High

**Accepted behavior:** The home page should show only relevant information

**Testing :** Tested only with Safari on iOS on iPhone 7. Used a high speed internet. No mobile coverage.

**Comment by clasick** [comment]
Done with this issue. Just tidying up the code a bit and will initiate pull request.

**Comment by naveenpf** [comment]
Wont fix

**Comment by clasick** [comment]
@naveenpf Seems like a valid issue. Your reasons for "won't fix" labeling?
