### ISSUE TITLE
Bring back Classic Issue raise form

### ISSUE THREAD

**Issue by vmwsree** [IEEEKeralaSection/rescuekerala#1088]
### New Ushahidi Form is too complex for a simple user 
There is a significant difference in the volume of issues raised from the ground via website compared to last year. Yes the calamity is less but 120 is not a number we can trust. My assumption is either we are dropping users at the lead form, a user should be able to report the issue with very simple and fast process, which the older form was doing very well, We should route the issue submission via the older form. 

### This is just an assumption
* I could be wrong, but we should at least implement analytics, to see if traffic to lead ratio is okay, or how many clicks on Requests for Resource, and how many people complete the form.

**Comment by sreenadh** [comment]
Data from the form can be pushed to Ushahidi using their API.

**Comment by biswaz** [comment]
Ushahidi forms were used because our forms had UX problems that lead to wrong location information. But the learning from using ushahidi is that, it isn't perfect too..

**Comment by vmwsree** [comment]
@biswaz I am glad that other developers are also thinking same.Does this need a pr ? Please discuss this internally I believe that would make a significant change.If user has difficulty in a location we can ask for their pin code.

**Comment by rejuls** [comment]
Ushahidi has a lot of issues but serves the purpose for now. For the future, we should build something ourselves and use the google maps API (maybe?).

**Comment by biswaz** [comment]
@vmwsree Ushahidi's flaws and pros are being studied. We are not in a position to switch right now. More over, it aint that bad and it works better in some cases.
