### ISSUE TITLE
Making the app a PWA so that it can load much faster on devices

### ISSUE THREAD

**Issue by vvishakhp** [IEEEKeralaSection/rescuekerala#110]
Hello, I was thinking that we could add a service worker to cache all static assets and some dynamic pages so that everyone will be able to load the web page faster and the rescue operators can view the content even if they are offline.

**Comment by naveenpf** [comment]
Closing now. Not priority

**Comment by asimqt** [comment]
@naveenpf I think making the site PWA is a good idea. Since the network is not stable in the flooded area and most volunteers are registering for help. If we can make it a PWA, that'll help them. What do you think?
