### ISSUE TITLE
In district needs page have date and time of submission or edited

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#1104]
https://keralarescue.in/district_needs/

Each row needs date and time at which entry is made. 

Example 
updated on Aug 15, 2018 - 8.00 am

**Comment by biswaz** [comment]
Fixed in https://github.com/IEEEKeralaSection/rescuekerala/commit/d13e0ebbc68e8d857416c4b6cf99eb5f43729f16
