### ISSUE TITLE
Request for resources : Mandatory field

### ISSUE THREAD

**Issue by Dhanya-Abhirami** [IEEEKeralaSection/rescuekerala#111]
Make resource needed (water ,food, etc) a mandatory field.

**Comment by bobinson** [comment]
> Make resource needed (water ,food, etc) a mandatory field.

Please don't make this mandatory as people in emergency situation may not be able to understand what is going on and will prevent submitting quickly.

Only mobile number should be mandatory and all other details can be made optional. Location etc can be fetched using device capabilities if available.

**Comment by naveenpf** [comment]
Closing this
