### ISSUE TITLE
Need malayalam instructions on how to turn on "Allow location" access in browser.

### ISSUE THREAD

**Issue by alokbabu** [IEEEKeralaSection/rescuekerala#117]
GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ is one of the top priority features used at the moment. But many aren't using this as people ignores browser popups. Need instructions on how to allow "Location access"  in browsers in Malayalam.
 
Please refer a gif is recommended.
https://pasteboard.co/Hzqzsvs.png

**Comment by bobinson** [comment]
GPS നിർദ്ദേശാങ്കങ്ങൾ 

1.  ബ്രൗസറിൽ https://www.keralarescue.in/ തുറക്കുക 
2.  ബ്രൗസർ എന്ന ഒരു  സന്ദേശം  കാണിക്കും

**Comment by irshadshalu** [comment]
How are we planning to display this message?,
A simple modal dialog on clicking which GPS fetch starts?.

Is anyone working on it already or should I?

**Comment by bobinson** [comment]
> Is anyone working on it already or should I?
Go ahead and implement in anyway that you can. Its fine even if someone else is working. I don't have an Android so please feel free to make the translation better too.

**Comment by alokbabu** [comment]
This should be short and small as most of the people would be accessing the page on mobile phones. I would recommend something like a tooltip.

**Comment by irshadshalu** [comment]
As of now, the location will be requested as soon as the user opens keralarescue.in/request. 

Do we need to change it so that it only requests location after the user reads a modal/dialog with instructions?

**Comment by alokbabu** [comment]
Yes please. Which make more sense.

**Comment by aswinmohanme** [comment]
@irshadshalu I think asking on page load is better because the user would be overwhelmed by the forms at the end.

**Comment by alokbabu** [comment]
People woudn't notice that little pop up in panic. They will be probing to fill up the fields first.

**Comment by bobinson** [comment]
please fix #125 on highest priority if anyone can

**Comment by irshadshalu** [comment]
![screen shot 2018-08-16 at 5 46 29 pm](https://user-images.githubusercontent.com/8298478/44207894-62c69c00-a17c-11e8-9fc1-10b9b8d11dc5.png)


Here is the working screenshot. Should we load it as and when the user enters the page?

**Comment by naveenpf** [comment]
Should be handled in #125

**Comment by bobinson** [comment]
there is a second scenario : This is applicable only when the browser is asking for location.  If the browser is not asking for the location it will be confusing. So we must address the second scenario too. Also for #125 



GPS നിർദ്ദേശാങ്കങ്ങൾ



1. ബ്രൗസർ "www.keralaresue.in wants to know your location" എന്ന ഒരു സന്ദേശം കാണിക്കുകയാണെങ്കിൽ സന്ദേശത്തിൽ നിന്നും  Allow തിരഞ്ഞെടുക്കുക

2. ഇല്ലെങ്കിൽ, സഹായം ആവശ്യമുള്ള ലൊക്കേഷനോ , സ്ഥലത്തിന്റെ മേൽവിലാസമോ , തിരിച്ചിറിയാൻ സഹായിക്കുന്ന അടയാളങ്ങളോടെ രേഖപ്പെടുത്തുക 



Scenario3:

We also need instructions regarding how to give address details of others.

**Comment by irshadshalu** [comment]
We can check if the browser permission is already given or not and then decide whether to show the modal.
