### ISSUE TITLE
Text overlap on mobile in contact info/ registered requests page

### ISSUE THREAD

**Issue by gauthams09** [IEEEKeralaSection/rescuekerala#121]
Seeing issue on mobile page due to text going outside the columns on contact info/ registered requests page. Fix is to wrap them inside the column itself

**Comment by meain** [comment]
Duplicate of https://github.com/IEEEKeralaSection/rescuekerala/issues/42
Fixed with https://github.com/IEEEKeralaSection/rescuekerala/pull/93

**Comment by prajinprakash4u** [comment]
```
.table-responsive>.table>tbody>tr>td, .table-responsive>.table>tbody>tr>th, .table-responsive>.table>tfoot>tr>td, .table-responsive>.table>tfoot>tr>th, .table-responsive>.table>thead>tr>td, .table-responsive>.table>thead>tr>th {
    /* white-space: nowrap; */
}
```

this will solve overlap otherwise we need to set a width for the container

**Comment by bodhish** [comment]
Simple fix
In `@media screen and (max-width: 767px)`
use `white-space: normal` insted of `white-space: nowrap`

**Comment by biswaz** [comment]
I fixed this manually. Please check

**Comment by gauthams09** [comment]
Thanks biswas, pls close this

**Comment by naveenpf** [comment]
Fixed

**Comment by bobinson** [comment]
Please refer to some changes requested in #132
