### ISSUE TITLE
URGENT fix needed - unable edit location info

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#125]
**SEVERITY : HIGHEST SEVERITY AND PRIORITY**

**Issue:** Unable to manually edit the location information. I was trying to enter information of someone's parents and not able to edit.

Environment: Firefox on mac os  and Chrome : both tested on macos.

![image](https://user-images.githubusercontent.com/18070249/44206870-d49ce680-a178-11e8-99ee-7c7b0d7b2306.png)

![image](https://user-images.githubusercontent.com/18070249/44206892-e1b9d580-a178-11e8-9eae-6a83acc840ad.png)

Steps to reproduce:

**scenario 1:**

1. Allow browser to Access GPU location
2. The location details are auto filled

3. Unable to edit to the location

This is the case in Chrome and FF

**Scenario2:** 

1. Don't allow browser to access location
2. The location details are hidden

![image](https://user-images.githubusercontent.com/18070249/44207217-04002300-a17a-11e8-95d1-ed77762d3719.png)

PS: Power went out and I will not be to confirm.

**Comment by sidharthv96** [comment]
You can edit the Location in top. This is auto fetched GPS location.

**Comment by aswinmohanme** [comment]
Yeah, this is an a show stopper. On the map were getting other countries as the source. 

If the form is edited we need to calculate the gps location from the address

**Comment by sidharthv96** [comment]
Maybe we should hide the GPS location boxes as it might cause confusion.

**Comment by aswinmohanme** [comment]
Yeah that seems nice there is no need to display that.

**Comment by littlestar642** [comment]
@sidharthv96 Rather a better idea would be if we just remove the focus from the form field and add a disabled cursor over it. This way it will be seen to the user but at the same time do not give appearance to be editable.

**Comment by bobinson** [comment]
Steps to reproduce:


**scenario 1:**


1. Allow browser to Access GPU location
2. The location details are auto filled

3. Unable to edit to the location

This is the case in Chrome and FF


**Scenario2:** 

1. Don't allow browser to access location
2. The location details are hidden

![image](https://user-images.githubusercontent.com/18070249/44207217-04002300-a17a-11e8-95d1-ed77762d3719.png)

**Comment by alokbabu** [comment]
Please refer #127 as well.

**Comment by bobinson** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/18070249/44207763-ef248f00-a17b-11e8-94ad-06e02cb0156a.png">
People are using to report others, so please take care of this in priority. Thanks volunteers.

**Comment by irshadshalu** [comment]
#122 already hides the input field for Geo co-ordinates when user is requesting for others.

Should we add the ability to fill in location data manually?

**Comment by littlestar642** [comment]
I have solved the issue but facing problem creating the PR. Please someone help me with this  @bobinson

**Comment by kiranparakkalkalam** [comment]
@littlestar642: What's the issue you are facing?

**Comment by littlestar642** [comment]
Made a PR. Please review.

**Comment by vrthra** [comment]
@littlestar642 I have commented in your issue. For others, If you make it editable, please add the required location format for GPS in the label, and also validate it.

**Comment by mevinbabuc** [comment]
@naveenpf the popup map with draggable marker is a good for this as others usually use this..

**Comment by alokbabu** [comment]
@mevinbabuc How convenient is this for mobile phones users?

**Comment by bobinson** [comment]
First step for fix is to get a basic text area working with editable option. Other things like exact GPS co-ordinates is not something people in emergency can do.

**Comment by biswaz** [comment]
Please rebase everyone

**Comment by naveenpf** [comment]
Which pull request we should take ?

**Comment by bobinson** [comment]
@littlestar642 - please check this.

**Comment by irshadshalu** [comment]
Someone look into both #266 and #286. One of these should be selected based on usability and after testing and merged sooner.

**Comment by mevinbabuc** [comment]
@alokbabu works great on mobile!
