### ISSUE TITLE
Extract relevant information from Whatsapp messages etc

### ISSUE THREAD

**Issue by thezillion** [IEEEKeralaSection/rescuekerala#129]
People are sending help requests via WhatsApp to their friends etc. What if they could copy paste those messages, and we could extract details like location, things needed, contact details etc from these messages?

**Comment by bobinson** [comment]
Not easy unless exact geo-location is available - use of GSM and GPS is the best way.

**Comment by aswinmohanme** [comment]
Yeah, we can ask them to lodge a request via the request form

**Comment by naveenpf** [comment]
Closing this .. to complex. 
Volunteers should able to log issues.
