### ISSUE TITLE
Can we also fetch geo location of the volunteers?

### ISSUE THREAD

**Issue by jinut2** [IEEEKeralaSection/rescuekerala#133]
If we could have geo location of volunteers, we could geo-fence them and show their details to the people in need nearby when they put on a request.

**Comment by bobinson** [comment]
A simple page can do this - but at a later point as this  may be needed only later points.

**Comment by kracekumar** [comment]
Does adding geo-location information field in the page, https://keralarescue.in/volunteer/ work?

**Comment by jinut2** [comment]
I guess it would require a migration. Have to store the co-ordinates into the db.

**Comment by irshadshalu** [comment]
If anyone is working on it, refer #29 for easier integration.

**Comment by JintoAntony** [comment]
@jinut2 @irshadshalu Working on this one.

**Comment by naveenpf** [comment]
Please rebase

**Comment by JintoAntony** [comment]
@naveenpf https://github.com/IEEEKeralaSection/rescuekerala/pull/175.

**Comment by naveenpf** [comment]
@biswaz please merge

**Comment by JintoAntony** [comment]
@biswaz Updated.

**Comment by pranavashok** [comment]
This issue is still reproducible.
