### ISSUE TITLE
Translation : Malayalm of Districts (enhancement)

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#134]
![image](https://user-images.githubusercontent.com/18070249/44208737-e4b7c480-a17e-11e8-9ace-ad2b11a8bb74.png)

**Issue Description:**  Malayalam translation for the district names will be helpful.

Severity: Normal

Accepted behavior:  Show district names in Malayalam in bracket along with English names

Optional : Sorting based on the locations with highest issues could be helpful. Say Ekm, Wayand etc at the top.

**Comment by bodhish** [comment]
Fixed in `https://github.com/IEEEKeralaSection/rescuekerala/pull/136`
