### ISSUE TITLE
https://www.keralarescue.in/requests/?district=ekm

### ISSUE THREAD

**Issue by panickervinod** [IEEEKeralaSection/rescuekerala#139]
Returns Server 500. 

Can this be redirected to a  google sheet.  

https://docs.google.com/spreadsheets/d/1gRu1p7RpJ3qFr4gQpS3oSafBDvMxeR4umQaVgDSgZbc/edit?usp=sharing

**Comment by naveenpf** [comment]
Dev is on it

**Comment by littlestar642** [comment]
Why is it needed to redirect the page to a google sheet, when there is already a table that shows the requests? @panickervinod

**Comment by venupai** [comment]
Site is down again. If this is due to deployment suggestion tk use a symlink based system to reduce downtime.

**Comment by agzuniverse** [comment]
Server is back up, this is not a problem as of now.

**Comment by venupai** [comment]
Verified. Server is back up. Thanks

**Comment by naveenpf** [comment]
fixed
