### ISSUE TITLE
tables are messed up on mobile and desktop

### ISSUE THREAD

**Issue by clasick** [IEEEKeralaSection/rescuekerala#147]
The date column on Desktop is barely readable.

![Desktop](https://screenshotscdn.firefoxusercontent.com/images/9480e38a-3d8b-478b-a079-09a71a31734f.png)

On mobile, all the useful information other than the location is hidden.

![Mobile](https://screenshotscdn.firefoxusercontent.com/images/32eb75db-1157-40c5-b4b7-4c231bd42d79.png)

**Comment by amalshehu** [comment]
Anyone started working on this issue ?

**Comment by abhaga** [comment]
A quick fix is to set `overflow-x: visible` on the top `div.table-responsive`. Here: https://github.com/IEEEKeralaSection/rescuekerala/blob/master/mainapp/templates/mainapp/request_list.html#L10

**Comment by ABHISHEKVALSAN** [comment]
when people add extremely long strings without spaces (eg. URL), then  word wrap fails.
The instance below is the reason for the problem

"""
Phone not reachable <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3925.4205920297554!2d76.33523201434568!3d10.308185492640298!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b08026b9eb3dd15%3A0xf8972735ad5efcf9!2sHotel+Sidha
"""
admin can manually edit the entry for time being. 
PS: entry is made under thrissur district.

**Comment by namboodiri** [comment]
I've made the container margin to 0 and width 100%, So that no space is wasted there.
I've made a PR. #153

**Comment by bobinson** [comment]
additional info : view in iOS Safari (iPhone7)

<img width="375" alt="image" src="https://user-images.githubusercontent.com/18070249/44215041-28b2c580-a18f-11e8-8c86-674d58f5e4ac.png">

**Comment by abhaga** [comment]
Fixing it in the frontend will only help so much. I propose that we convert long links to linked text thus solving the primary issue. So a very long link like `https://google.com/map/asdsdasdsdasd....` will be rendered as `<a href="https://google.com/map/....">Link to https://google.com/map</a>` with the visible text only showing the domain. If this sounds ok, I can work on this.

**Comment by alokbabu** [comment]
District shouldn't be shown in the table when it is already filtered by District. Timestamps can be moved under Requestee as Requested by "John Doe" on "Aug 16 hh:mm:ss". A seperate table for each case is also requested which shows location details. Can autogen case numbers for each requests and when clicking on case number a more detailed view for each case. Also display Status of each case.

**Comment by asimqt** [comment]
Can we show different format in mobile instead of the table? Like a list like:
```
District: Kollam,
Location: Kodiyattukara,
GPS: N/A,
Requestee: 
Contact number: 
```

**Comment by bobinson** [comment]
```
District: Kollam,
Location: Kodiyattukara,
GPS: N/A,
Requestee: 
Contact number: 

```
This will increase the space required on the page where the listing is shown and perhaps can be done in the detail page -- if at all such a thing is implemented.

**Comment by abhaga** [comment]
We can clean up the `Other Needs` input to strip out html links and URLs if there is no use case for those.

**Comment by ragsagar** [comment]
So who is working on this? We might need this quickly. Requests page is not very useful now.

**Comment by vinoth44** [comment]
We can fix the maximum width of the column to 200px and user word-break: break-all for now. 

May I can help for mobile responsive. Like the below image: 
https://res.cloudinary.com/css-tricks/image/upload/c_scale,w_1000,f_auto,q_auto/v1528559934/responsive-table-on-iphone-1_ftg6oh.png

**Comment by ajish99** [comment]
Use word break and set table td to nowrap=nowrap

**Comment by clasick** [comment]
@vinoth44 @ajish99 this used to be there but it was taken out in this commit 87bdccb

**Comment by asimqt** [comment]
If we have a detail page, show only Name, Location - Dist Shortcode, and mobile on this table. And clicking on cell should goto detail page. Because the vertical scrollbar is not visible in mobile and some desktop browsers.

**Comment by alokbabu** [comment]
@asimqt But there is not CaseID for "requested helps yet" someone who has access to db shall add a new case_id column and add autogenerated caseids.

**Comment by justinsyatnam** [comment]
@asimqt Please check the last comments in https://github.com/IEEEKeralaSection/rescuekerala/issues/132. Looks like a possible duplicate
