### ISSUE TITLE
Request to add few Additional Fields while listing requests status.

### ISSUE THREAD

**Issue by panickervinod** [IEEEKeralaSection/rescuekerala#157]
Please do consider adding few additional fields to the request status.  Some of them could be also part of the summary 

| Request Id 
| Reference ID ( to sync up with any system updating the  Recent status details or tracked elsewhere.)
| Timestamp 
| Name 
| Phone Number 
| # Of People Stuck 
| Any Kids/Elderly/Pregnant 
| Drinking Water/Food Available 
| District 
| Locality    
| Email Address 
| Any Other Contacts/Comments 
| Recent Status (Safe) (Admin)

**Comment by naveenpf** [comment]
Similar to #20
