### ISSUE TITLE
Database of people at relief camps

### ISSUE THREAD

**Issue by xaneem** [IEEEKeralaSection/rescuekerala#161]
A lot of people have been moved to relief camps. Currently, registrations are taken mostly in paper and it's becoming difficult to search the list to locate someone.

We're trying to build this. Will post updates here. Suggestions / help appreciated.
(via Abdullah)

**Comment by viggi-v** [comment]
It involves writing a whole new part of the application including new routes and templates, right?

**Comment by bobinson** [comment]
same as #81 @120

**Comment by ahumblenerd** [comment]
@xaneem are you working on this ?

**Comment by binu456m** [comment]
Will take care of creating the forms. Have done earlier, so can share the code

**Comment by bobinson** [comment]
@binu456m - share whatever you can via github. You can just create a repo and share the details here.

**Comment by xaneem** [comment]
@viggi-v Yes, it's a new part of the app.

First, I'm preparing a list of minimum features for this to be useful. Will post it here.

@ahumblenerd Working on this. Might be stuck if I lose internet access.

**Comment by binu456m** [comment]
Any help needed for coding? Or forms?

**Comment by naveenpf** [comment]
I have marked working on it. Please ping once done.

**Comment by naveenpf** [comment]
Please see this #120

**Comment by xaneem** [comment]
Relief Camps
    - Name of place
    - Location
    - District
    - Capacity

People
    - Name
    - Age
    - Gender
    - Location
    - Phone Number (not public)

Workflow:
- Admin/Coordinator can create relief camp
- Relief camp coordinators / volunteers can enter information of people.
- Public can search for people with name / phone number / location / age / relief camp name.

**Comment by viggi-v** [comment]
Any possibility of linking each entry to the already existing data about requests? that way once a person marks himself as safe and staying in a camp, his data can be removed from the requests list?
(just suggesting a feature)

**Comment by ahumblenerd** [comment]
Keep pushing. If you loose internet i shall take over. [ If i dont also loose power ].

**Comment by viggi-v** [comment]
@xaneem  do you have a fork on which you are adding new features? which repo should be watched?

**Comment by naharp** [comment]
The registry must be seachable with Mobile number or name. Mobile number need not be displayed but just searchable considering privacy of people. 
Maybe show phone numbers as 98xxxx4321

**Comment by xaneem** [comment]
@viggi-v Haven't pushed. Will post here in a while. Working with @ajnas and @jaseemkm
@naharp Yes, doing it that way.

**Comment by naharp** [comment]
I have power back, any link to your fork will be appreciated, I have some code done on camps and rescued.

**Comment by xaneem** [comment]
@naharp Working with @ajnas on the initial structure. Once it's ready, will post here.

**Comment by answerquest** [comment]
1. How about using a field to hold ANY unique identifier? (email id, mobile, landline, aadhar, pan..)
2. Photo to identify person? (in case of unaccompanied minor or mentally disabled this might be the only thing that can help)

If there's trouble like no network in information collection at relief camps then I'll suggest ODK Collect hooked to google drive. It can store photos too, and data collection on mobile can be done while offline. Links: [ODK Collect](https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=en_US) | [Documentation](https://docs.opendatakit.org/collect-connect-google/) | [A guide](https://www.google.com/earth/outreach/learn/odk-collect-and-google-drive-integration-to-store-and-manage-your-data/) | [a video](https://www.youtube.com/watch?v=GnXwGmhaI9U)

**Comment by xaneem** [comment]
Please refer #262. It has to be thoroughly tested and reviewed.

**Comment by xaneem** [comment]
Would love some feedback.

Home
<img width="1012" alt="screen shot 2018-08-17 at 05 25 25" src="https://user-images.githubusercontent.com/4448331/44240971-a05c1100-a1de-11e8-9d49-1c67bfa7f170.png">

List of Relief Camps
<img width="1181" alt="screen shot 2018-08-17 at 05 28 42" src="https://user-images.githubusercontent.com/4448331/44240977-a6ea8880-a1de-11e8-8b74-f5fcc28a4234.png">

Person Registration (by camp coordinator who's assigned a login)
<img width="426" alt="screen shot 2018-08-17 at 05 28 57" src="https://user-images.githubusercontent.com/4448331/44240980-abaf3c80-a1de-11e8-802f-b2919cf1af69.png">

Person Search (public)
<img width="1173" alt="screen shot 2018-08-17 at 05 28 22" src="https://user-images.githubusercontent.com/4448331/44240992-bb2e8580-a1de-11e8-9926-c356c27fcdea.png">

Refer PR #262. Improvements are welcome.

**Comment by naveenpf** [comment]
Change Relief Camps to Camp Name
