### ISSUE TITLE
Duplicate requests

### ISSUE THREAD

**Issue by biswaz** [IEEEKeralaSection/rescuekerala#173]
TODO: Remove duplicate requests
Use unique together in model field
Take db backup before fixing
Ensure regular backups via aws

**Comment by bobinson** [comment]
> Take db backup before fixing

Fixing what ?

**Comment by jishnunand** [comment]
@biswaz Can you give us more detail over here?

**Comment by abdullatheef** [comment]
Do we need db unique constraint for this? Or just blocking in ui is fine, right ?

**Comment by bobinson** [comment]
>Do we need db unique constraint for this? Or just blocking in ui is fine, right ?

Best practice is to have constraints and thus validations at every level - ie frontend , back-end logic as well as db.

**Comment by JikaMarley** [comment]
It would be great if a duplicate request is identified and the already saved details load up, so if a user can add more info and update the request
