### ISSUE TITLE
[Enhancement] No link to mapview of rescue needed people from main page

### ISSUE THREAD

**Issue by ananthuma** [IEEEKeralaSection/rescuekerala#174]
No link to the mapview https://keralarescue.in/map/  from main page.Its very easy to find rescue needed people from mapview rather than scrolling the entire list.

**Comment by vigneshhari** [comment]
We were using Gmaps API till now and it had a request limit, that's why we didn't make it public, now we have switched to free alternatives and will make it public after a short test

**Comment by vigneshhari** [comment]
@ananthuma will fix that
@bobinson Thanks but we'll stay with the current Map since it actually performs better.

**Comment by nishadhka** [comment]
This is an instance of [Ushahidi](https://www.ushahidi.com/) for flood mapping http://35.200.234.24/posts/create/2, it has csv import facility, if there is an data dump of the website, it is easy to import into it provided having geocoding API conversion on the non lat long entries. It is better to use tested and field deployed app than a custom developed one at present. 
![data entry page](https://user-images.githubusercontent.com/3928997/44222204-6fa9b680-a1a1-11e8-864a-fb40caa10c3e.png), [visualization](https://user-images.githubusercontent.com/3928997/44222251-8f40df00-a1a1-11e8-9ae2-f42f84ba8c34.png)

**Comment by sidhu18** [comment]
Also add available or nearby camps in map view.

**Comment by vigneshhari** [comment]
We can have existing data present in Ushahidi but updating it in real time would be hard, however, we can use this for mapping camps, supply posts and such.

**Comment by nishadhka** [comment]
Is there any dump of existing data, will work on geo referencing it

**Comment by vigneshhari** [comment]
You can get the live map data from keralarescue.in/data as JSON

**Comment by answerquest** [comment]
Hi, thanks for moving to leaflet/OSM!  
There's clearly mis-located markers in the data. But people have typed in their locations.   

Suggestions:  
1. Add a "corrected_latlng" field to schema. Keep blank, have a trusted team fill that. On the map, use that field for location if not blank, and, put a different marker on it.
2. Add satellite imagery layer. (is there a latest-tiles-source for the Kerala region? Sat companies have released such imagery for other disasters)
3. Another field in schema, 1/0 flag for accurate/inaccurate and mark that too.

I can help code for all these if it's going to be on leaflet.

**Comment by vigneshhari** [comment]
We have updated the map with some features now, we are looking into misentered data, we have added an option for users to enter lat and long by their own now.
I'll look into getting the satellite image data

**Comment by nishadhka** [comment]
@vigneshhari the points outside state boundary needs attention for correcting it, can be filtered by geometry intersect, is this data different from keralarescue.in/data, looking for the categories of points such as [Red: Needs Rescue,Green: Request Made For Other,Blue: Generic Request]

**Comment by vigneshhari** [comment]
I'll ask the team to give a different color for pins outside the boundary.

**Comment by answerquest** [comment]
Suggesting using Leaflet's L.divIcon. Reduces performance issues, enables much higher number of points on map (several thousands or more). Can assign it classes based on metadata and use CSS to give it any shape/color. Sharing a snippet. (If I can know where's the code that generates the markers, I can create a PR)

```
var stopmarker = L.marker([lat,lon], { 
	icon: L.divIcon({
		className: `stop-divicon`,
		iconSize: [17, 17],
		html: labelShort
	}) 
});
stopmarker.addTo(stopsLayer);
```

**Comment by aswinmohanme** [comment]
@answerquest we use react-leaflet for adding those markers. You can find the code at https://github.com/aswinmohanme/kerala-flood-map

**Comment by answerquest** [comment]
@aswinmohanme thanks, looking it up.  
@nishadhka @vigneshhari the JSON data converts very easily into CSV here: https://konklone.io/json/ . One could also make a script to update latest id's at a place. Zapier is a possible tool for that. Suggesting: put on shared spreadsheet for location correction, or put into a CRM so each request can be tracked, etc. I'm focussing on map right now so just putting these ideas out there. Apologies, this digresses from this issue's subject.

**Comment by nishadhka** [comment]
Got 1391 rows of data from json file, after making a Kerala state boundary geomerty intersection, 783 rows stayed, imported into Ushahidi, the visualisation is as follows, all the points are not imported, it has issue in bulk import, have to do batch wise batch 
![screenshot_2018-08-17_00-35-37](https://user-images.githubusercontent.com/3928997/44229475-cfaa5800-a1b5-11e8-8f6a-003aef1d526c.png), the Ushahidi has cool features of flagging the report as different levels of approval even as a csv column 
![screenshot_2018-08-17_00-31-14](https://user-images.githubusercontent.com/3928997/44229680-60813380-a1b6-11e8-92a0-a5fdee9bf338.png), wishes people consider this option of Ushahidi that will be better for protecting the privacy, PS **no one makes new pens while in examination hall**
