### ISSUE TITLE
map shows incorrect location information

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#177]
URL: https://keralarescue.in/map/

![image](https://user-images.githubusercontent.com/18070249/44221133-2310ac00-a19e-11e8-929a-cd276c0bc5c8.png)

**Issue:**

Since we are taking the current GPS location of the one who is requesting information, the map is showing wrong locations.

This can be avoided by making the following check box more promiment and moving it closer to the Requestee check box. I
*Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു *

**Severity:** High

Since this is causing incorrect data being captured. Correct data can help easy tabulation in future.

**Comment by adamshamsudeen** [comment]
Chalakudy and Aluva seems to be affected more and hence needed more priority said the minister.

**Comment by naveenpf** [comment]
Issue with #125
