### ISSUE TITLE
Slack is down. Do we have a better way to communicate?

### ISSUE THREAD

**Issue by vrthra** [IEEEKeralaSection/rescuekerala#179]
keralarescue.slack.com is no longer accessible, and the slack [status](https://status.slack.com/) page says they are having problems. If there is a different way to communicate, please list on this issue.

**Comment by ragsagar** [comment]
Yeah, slack failed at most required time. Let use IRC

**Comment by bodhish** [comment]
Flock is an alternative for slack
'https://flock.com'

**Comment by naveenpf** [comment]
irc will be fine

**Comment by vrthra** [comment]
+1 for IRC #keralarescue?

**Comment by vigneshhari** [comment]
Telegram would be fine right ?

**Comment by biswaz** [comment]
Telegram ?

**Comment by biswaz** [comment]
Will suit our purpose. Lets hope slack will be online soon

**Comment by jishnunand** [comment]
@biswaz can you tell me wts the issue with slack I can help you with that.

**Comment by biswaz** [comment]
It's their server issue

**Comment by ragsagar** [comment]
https://webchat.freenode.net/?url=irc://irc.freenode.net/keralarescue

**Comment by jishnunand** [comment]
There is no issue with their server. Because I am using slack now too.

**Comment by ragsagar** [comment]
I registered a channel `#keralarescue` in freenode. Let's use that for till slack comes back.

**Comment by vigneshhari** [comment]
slack is back up

**Comment by biswaz** [comment]
@jishnunand your location?

**Comment by vigneshhari** [comment]
Slack is Active now. I'm closing this Issue

**Comment by ragsagar** [comment]
Great, Slack is back 👍

**Comment by jishnunand** [comment]
Bangalore

**Comment by bodhish** [comment]
Check this 'https://status.slack.com' @jishnunand

**Comment by jishnunand** [comment]
@biswaz can you invite me to keralarescue.slack.com channel?
jishnunand@gmail.com

**Comment by irshadshalu** [comment]
I can't create an account on slack. Any help is appreciated.
