### ISSUE TITLE
Button to add new request on request success page

### ISSUE THREAD

**Issue by littlestar642** [IEEEKeralaSection/rescuekerala#180]
Observed Behaviour:-

Presently, there is no button on the request success page that may take a user back to generate a new request.

Expected Behaviour:-

A button below the "successfully registered" message that may be used to submit a new request.

**Comment by JintoAntony** [comment]
@littlestar642 Working on it.

**Comment by naveenpf** [comment]
Are you working on this ?

**Comment by JintoAntony** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/pull/175 Updated.
