### ISSUE TITLE
Update Rescue Status with otp

### ISSUE THREAD

**Issue by vmwsree** [IEEEKeralaSection/rescuekerala#183]
Using the phone field in the request the owner of the request should be able to update his situation,If he is rescued or not.

**Comment by jishnunand** [comment]
@vmwsree is it required with otp? why can't we use some popup box for updating the status?

**Comment by kannankumar** [comment]
@jishnunand Without OTP, anyone can update status(accidentally/otherwise) of any other request. Do we want that?
As a start we can have a basic popup with status options and add in OTP when that is ready.

**Comment by venupai** [comment]
OTP is not much reliable during these circumstances. It might be delivered really late.

**Comment by JithinPavithran** [comment]
@kannankumar 
I think we shouldn't add the overhead of OTP at this emergency situation.

**Comment by jishnunand** [comment]
@venupai correct +1. For now we can keep a popup box for updating their status

**Comment by jishnunand** [comment]
@biswaz can we bring this up?

**Comment by kannankumar** [comment]
Alright I agree with you. OTP might be unreliable now.
We can go with the alternative option suggested by @jishnunand.

**Comment by naveenpf** [comment]
Wait for #20

**Comment by vmwsree** [comment]
OTP will be reliable since it also shows that the person has reached a safe location, But Giving a pop means anyone can mess up our data. you can ask the user if the otp is not available then give a one line feedback on his situation+ recaptcha. or once the status is updated we can send the person your status is updated if its wrong that person can re-raise the issue.
