### ISSUE TITLE
Phone number validation is still broken

### ISSUE THREAD

**Issue by Neonkraft** [IEEEKeralaSection/rescuekerala#191]
Phone numbers of length less than 10 is being accepted.

The front end validation ensures that the text box accepts only digits 0-9 (as well as + - and . )
The phone field in the models have max_length = 10, so it addresses the concern of the upper limit.

The problem can be fixed by adding a RegexValidator on the phone.CharField. The regex can be ^[0-9]{10}$

I've tried this and it works. However, in the case of the request page, when regex validation fails on the backend, the "Allow Location - നിങ്ങളുടെ സ്ഥലം കൊടുക്കുക" help modal pops up again (because the user is redirected back to the request page itself). It can be extremely confusing to the user. 

Thoughts, anyone?

**Comment by salmanulfarzy** [comment]
Working on it with Django Validators.

**Comment by biswaz** [comment]
@clasick Like?
