### ISSUE TITLE
API Configuration expecting

### ISSUE THREAD

**Issue by asjadnabeel** [IEEEKeralaSection/rescuekerala#193]
We are currently working on a app.
If somebody can configure API (RestAPI ) especially for the "help request " model un the server... then the app also can reach the people over smartphone .

**Comment by jishnunand** [comment]
@asjadnabeel if required we can enable API's for existing apps.

**Comment by bobinson** [comment]
@asjadnabeel - why don't just use the browser as its available in every phone ? Would humbly request to test what we have make it better.

**Comment by asjadnabeel** [comment]
@bobinson : No problem, it is working so well in browser. Suggested a different method wherein i can give some help also people(both affected and volunteers) will have easy access to website also. We can provide some features like, auto location detection,  update about requests,  ..etc ...

**Comment by naveenpf** [comment]
Same as #22

**Comment by asjadnabeel** [comment]
@jishnuanand: i am happy to work if API is enabled, but don't want to conflict intrest of people who are contributing on this project.
