### ISSUE TITLE
Don't try validation attempts on live site!

### ISSUE THREAD

**Issue by clasick** [IEEEKeralaSection/rescuekerala#195]
Many GitHub users are trying out validation attempts on the deployed site! Try out on your local site if you want to check something...

![](https://screenshotscdn.firefoxusercontent.com/images/cebdd21f-0c1b-464e-a356-dd83bc43e1aa.png)

I've seen tens of examples like this so far today.

This will need to be stopped and fixed from the backend. :anger:

**Comment by jishnunand** [comment]
@clasick is there any test server available?

**Comment by salmanulfarzy** [comment]
Not yet, For now we coudld rely on local server for development to prevent polluting production data.

**Comment by naveenpf** [comment]
No fix planned now.
