### ISSUE TITLE
Adding Open Graph tags (Makes social media sharing easier)

### ISSUE THREAD

**Issue by lunaroyster** [IEEEKeralaSection/rescuekerala#198]
When you enter a URL on Social Media, and WhatsApp, OG tags are used to display a picture and description. 

PR: https://github.com/IEEEKeralaSection/rescuekerala/pull/184

**Comment by scanalkara** [comment]
https://github.com/fcurella/django-social-share
https://github.com/lettertwo/django-socialsharing
This links might help

**Comment by bobinson** [comment]
@lunaroyster - this is good. Please followup and ensure the merge!

@biswaz @naveenpf : Please merge this PR as many people from US etc are waiting to help.

**Comment by lunaroyster** [comment]
@bobinson Awesome. 

#184 looks good to me in code. 

If someone could test it by pasting the dev URL into WhatsApp or Twitter, we could see how it looks.

**Comment by lunaroyster** [comment]
![image](https://user-images.githubusercontent.com/6189367/44228753-aab4e580-a1b3-11e8-9be7-53a239cf47e4.png)
