### ISSUE TITLE
Implement a ticketing system. 

### ISSUE THREAD

**Issue by naveenfrancis** [IEEEKeralaSection/rescuekerala#20]
- [ ] Have id for each case.

- [ ] Able close each case id.

- [ ]

**Comment by kira0204** [comment]
Hi @naveenfrancis, apologies, I couldn't understand what you meant here.

Github already has a ticketing system implemented as `Issues` and gives a unique ID to them as well.

**Comment by naveenfrancis** [comment]
Each request should have a ticket id like PTM0001. We need able to call the requestor and close the case. 
Request are piling up. Now it looks like 5500 requests. Many are calling the same requestor called bt volunteers again and again. 
Not ticketing for github. 

Sample ticket PTM0001, TCR0020

**Comment by dnivra** [comment]
Hijacking/piggybacking this discussion. Can we move to an already well developed system specifically for this purpose? I think it might be best to use [Eden from the Sahana Foundation projects](https://sahanafoundation.org/eden/) because [it is well tested in disaster scenarios](https://sahanafoundation.org/eden/deployments/) and [provides lots of features](https://sahanafoundation.org/eden/features/). Additionally, they do provide hosted Eden instances too so we can simply contact them and get it done.

Most features we think of will be already implemented there. We can customize and self-host Eden instance if required than relying on a hosting provided by them.

**Comment by naveenfrancis** [comment]
Any ticketing mechanism would fine now. If it is tested well good. Let's use that.

**Comment by rahulkrishnanfs** [comment]
@dnivra @naveenfrancis if  it is good then we can test and move  to it

**Comment by dnivra** [comment]
I have not used Eden and from a brief glance, it seems to have good features. We might have to investigate what features it offers and then perhaps implement additional features we need. Sahana Foundation might also offer some volunteers for this purpose: experienced developers who could help.

**Comment by dnivra** [comment]
Demo site if anyone wants to check it out: demo.sahanafoundation.org

**Comment by rahulkrishnanfs** [comment]
@dnivra  it looks goods, Location tracking is also available

**Comment by JESWINKNINAN** [comment]
Please let me know if anyone need help from DevOps kind of activities: ping me here jeswinjkn@gmail.com

**Comment by rakesh-gopal** [comment]
Can you assign this to me?
I'm planning to implement something like this:
![image](https://user-images.githubusercontent.com/1679290/44204021-add9b280-a16e-11e8-9ec4-8455969b1ae3.png)

**Comment by biswaz** [comment]
If you're aim for something like:
Volunteer calls existing requests, confirms request is fullfilled, marks as fullfilled
Then we already have it, it is only given to District Project Managers  of KSITMand Volunteer POCs

We shall seek how to optimize the work flow.

**Comment by ashikmuhammedpa** [comment]
@biswaz @naveenpf  Can we get access to the volunteers list on the field asap ? that will help us to route the request manually for the time being. please share your whatsapp number.

**Comment by bobinson** [comment]
better to just use a paginated listing and assigning to volunteer leaders based on location can help.

**Comment by ashikmuhammedpa** [comment]
right @bobinson , i am trying it with a cloud based app. if it works we can integrate that with this website.

**Comment by ashikmuhammedpa** [comment]
@naveenpf 

userid: naveenpf 
pwd:12345

https://dev58610.service-now.com/login.do

Try this 

also availble as mobile application.so easy for eveyone. we can ask international volunteers to input the whatsapp or facebook help msg here

@bobinson @biswaz

**Comment by bobinson** [comment]
1. Created a Telegram group here : https://t.me/RescueKerala

@biswaz - please join and will give the admin access.

**Comment by naveenpf** [comment]
Already District officials are taking the requests and updating. 
If the status update is given public, officials are worried about wrong updates. 
Still discussions are going. 
Please wait for update

**Comment by bobinson** [comment]
agree.

And also if there is someway for the authorities to prioritize areas that will be good I believe. The context is some one stuck in area is asked to wait for 1.5 hours as the rescue is happening in an emergency basis. Which means prioritization of locations can be helpful for authorities. (wishlist)

**Comment by alokbabu** [comment]
Is there an admin interface for Changing status for each case ("help requests")?

**Comment by alokbabu** [comment]
Is anyone working on this?

**Comment by vjMagar** [comment]
Hi please assign this to me. Will be working on it

**Comment by alokbabu** [comment]
@naveen could we get some insight on this issue please.

**Comment by vjMagar** [comment]
@alokbabu I have just started looking at this and yes will be working on this. Shall upload the pr asap.

**Comment by panickervinod** [comment]
@naveenpf @vjMagar @alokbabu There should be an admin view to update status as well as sync up reference from any other tracking sheet. #157

**Comment by naveenpf** [comment]
We are planning to implement. 

-Each rescuecase once logged, has to create a ticket. (external app)
-Volunteers can only update tickets. 
-Only Districts officials will close the ticket. 

Currently District officials handling the requests.

**Comment by vjMagar** [comment]
So here is the base idea.

We create new app, naming it ticket management.

Model shall have FK to request

**Comment by panickervinod** [comment]
Sound good

**Comment by vjMagar** [comment]
We make new app naming it ticket management 

It's shall have one model, 

Ticket -> FK to request model.

Assuming that only district office have access they are the admin stuff, using this logic to restrict the status option on can see and update.

Now on views we shall have different two panel one showing details of tickets, and then second panel to update the status and all.

And display on second panel shall be based on the access user have. Eg volunteer can update ticket, and so.

We shall have another view for district officers for quick response. This shall show the status of all requests with district wise filters and all. (Similar to admin dashboard)

**Comment by jishnunand** [comment]
@naveenpf which external system you are going to use over here?

**Comment by ashikmuhammedpa** [comment]
@naveenpf  Is there any way we can get the volunteer list ? so that we can manually assist the request for the time being ?

**Comment by ashikmuhammedpa** [comment]
@naveenpf  can you pls ping me in whatsapp ? I m on +919745653615.  or pls share yours I shall reach out to you

**Comment by jishnunand** [comment]
what's the status of this?

**Comment by vjMagar** [comment]
hi i have just reached home and have started with it. @jishnunand would you like to join in so that we can complete this faster?

**Comment by ashikmuhammedpa** [comment]
Guys, Please look at this

dev58610

userid: test_user

password:12345


also , mobile application available

Playstore -> ServiceNow (Download the application) and use the same credentials .


Its quite easier and already available in app. Volunteers and other people who is abroad also can work as it is on cloud. Request you all to try and deploy it faster rather than coding it from scratch

**Comment by naveenpf** [comment]
GOK officials internal requirements on this. It will be developed by internal team. 
If help is needed I will update.

**Comment by pranavashok** [comment]
It might make sense to integrate #246 in this system.

**Comment by bobinson** [comment]
## Ticketing System - Usecases

1. UA1: How to prioritise requets ?
2. UB1: How to get geo-location?
3. UB3: How to track a request is handled ?
4. UA2: We need to avoid duplicate requests -- this is an important issue as people requesting help are requesting help via multiple methods using social media, whatsapp etc as well via TV/Radio channels etc. This creates dupicate requests. 
5. UA3: Scheduling - the requests are handled on a priority basis. ie if some location is under threat, that request is first taken care by the volunteers. This means, the post-poned requests will get missed out. We need a mechanism to schedule.
6. UA4: Verify resucue - We need to update the status of rescue and close duplicates.
7. UA5: Location Priority : locations undere water should be prioritized. This should be ideally done with the feedback from the volunteers on field.
8. UJ1: SMS / USSD linking for OTPs and send confirmations etc. (low priority)
9. UT1: **Last Known Location from GSM towers** (in many cases the last known location from the Telecom HLR can help to traingulate  a person with upto 4 meters of accuracy. Will need help from Telcos. )

**Comment by shajith** [comment]
Talked this through with @naveenfrancis in slack, this is the current requirements/plan:

Requirements: volunteers need to be able to update the status of a request, to indicate if it's being handled or already handled.

Plan:

1. Add a descriptive request ID to the request (Eg: EKM1234)
2. Add a page that accepts a request ID and allows looking up and updating the status of that request. Collect a name, phone number, and comments/actions taken when updating.

There might be more things we want here, but this seems to be the immediate priority. Jump in #ticketingsystem in slack if you want to help!

**Comment by AparnaJW** [comment]
Can requestee phone number be the basis of closing /updating a case?

**Comment by giju** [comment]
Guys , What is the status of this one . If this feature is not implemeted , you can use this .

https://keralafights.com/manage/ 


We have pulled the data from keralarescue.in and created a ticketing system here. 
As of now we have 30K tickets there .  Right now , we can make use of community to do a dedupe check , call and confirmation and corresponding status updates and resolved , the Govt officials can later verify the closure. 

We have more than 12000 requests coming in as duplicates. The work flow what we implemented is what was mentioned on the SOS pages.

Along with every status update , we keep track of a work log as well. 
All of the data is exposed as API's and we are keeping a remote_id to refer the ids of the tickets on keralarescue.in as well.  So any time you can sync the data back to the rescue kerala.

**Comment by nikhildev4nk** [comment]
@giju  Great Work bro...

One suggestion. Can you make an open portal(page) where somebody can just come in and put their mobile number and mark safe. No need to display the request or anything. Just capture mobile number and allow them to mark safe. This we can share to relief centers(+) and ask them to update. 

And then we can use these mobile numbers to put a separate status for the related request.  

(And another note: In dashboard, selecting external and clicking next button on the bottom keeps loading..)

**Comment by giju** [comment]
Thanks @nikhildev4nk - Will do and update everyone.

**Comment by a-thomas-ny** [comment]
I have opened this https://github.com/IEEEKeralaSection/rescuekerala/issues/449 and got linked to this...
https://keralafights.com/manage/ - This looks great.
Option to filter the records with location is important. 
My parents were rescued from Chengannur 2 days ago after 2 days in water... No Electricity, Network Coverage in any of these critical areas.. Can there be a status like "UNKOWN" or something?

'Status' is required field and none of those are applicable in a critical situation.

Also, very critical to provide the option to enter google map link. In my opinion, there is no other trusted sources to provide the coordinates to helicopter rescue. I have requested this issue also earlier - related to this. https://github.com/IEEEKeralaSection/rescuekerala/issues/252

**Comment by a-thomas-ny** [comment]
please consider the criticality, There is already questions from national/international media to Major Kishore how the location is passed to them. soon things will come back to this request and in my openion, this should be rolled to production immediately so that relatives can start mark/change the status and pin the locations of their lowed ones

**Comment by lalkrishna** [comment]
If the status can change only by authorities, we may didn't get correct status. Let relatives or friends can update status, and only authorised person can verify that post. 

In person i have requested for my friend who's in aarattupuzha, and now he's safe. But the request still there.

**Comment by weather81** [comment]
clearly of the topic here but can you also include an option or as a seperate thread to add cleaning materials to a specified list of panchayats where the flood has receeded but left a great aftermath.i think it would be good for cleaning up and stuff
