### ISSUE TITLE
pip3 install -r requirements.txt will fail if you don't have required libraries 

### ISSUE THREAD

**Issue by syamsmudavandoor** [IEEEKeralaSection/rescuekerala#204]
To install dependancies , README specifies as pip3 install -r requirements.txt . If the system doesn't have proper libraries the above command will fail. To fix that update README of  Install dependancies part like below

sudo -H pip3 install -r requirements.txt

**Comment by salmanulfarzy** [comment]
Don't use `pip` with `sudo`. There are multiple blocked PRs to update the documentation with different dependency management solutions. Please wait for any of them to be merged or follow the open PRs.

**Comment by naveenpf** [comment]
documentation
