### ISSUE TITLE
Interactive voice response to call requestee mobile number

### ISSUE THREAD

**Issue by linson007** [IEEEKeralaSection/rescuekerala#209]
Hi,

Can anyone /company can send a IVR call to all the request mobile number to check whether they are rescued or not .?

**Comment by naveenpf** [comment]
not planned

**Comment by linson007** [comment]
Ok.
 
At least send a message to all numbers periodically (which are not  marked as rescued)  and ask them to call to a toll free number with IVR capability to handle whether they are still in trouble or not .  This may reduce number of request .

I dont this this is too tedious since a lot of company are providing  bulk SMS and IVR functionality . 
Hope some company will come forward .
