### ISSUE TITLE
Load balancing and other aspects with website

### ISSUE THREAD

**Issue by dnivra** [IEEEKeralaSection/rescuekerala#21]
I'm here from social media posts such as [this](https://old.reddit.com/r/india/comments/97p5qn).

What is current situation like? I see cloudflare being used. What's the current plan? Where are things being hosted in backend and what database is being used?

Also, what is feature wise status of the website? Is there much more to be done? I think it might be best to [use Eden from the Sahana Foundation projects](https://sahanafoundation.org/eden/) because it is [well tested in disaster scenarios and provides lots of features](https://sahanafoundation.org/eden/features/). Additionally, they do provide hosted Eden instances too so we can simply contact them and get it done.

**Comment by kira0204** [comment]
This looks amazing @dnivra . I would wait for the maintainer of this repo to reply, I just had a cursory read and it would be great if you could list any cons(if there are)

**Comment by joicemjoseph** [comment]
@smc is ready to help with scaling and load balancing.

**Comment by shahidhk** [comment]
It will be difficult at this point to implement another system. Let us focus on scaling the current setup.

If the maintainers could point out issues with the current deployment setup, we can work on fixing them.

**Comment by dnivra** [comment]
@shahidhk I would say depends. If we have too many features to implement, then not spending time on it might be wise. If there aren't many, then no need to move. Otherwise, it might be better to move?

But yes, it would be good to know what is current deployment setup and requirements so a better decision can be made.

**Comment by rahulkrishnanfs** [comment]
@shahidhk I too be in the same page, we can work on the scaling part  but as now there is no ticketing system to track. Another issue opened for that. If we can implement the location tracking system then it would be better

**Comment by vinu** [comment]
any idea on the current deployment strategy? using heroku ?

**Comment by JESWINKNINAN** [comment]
Please let me know if anyone need help from DevOps kind of activities: ping me here jeswinjkn@gmail.com

**Comment by JESWINKNINAN** [comment]
Is this completed?

**Comment by akhulbe** [comment]
Agree that scaling up the current deployment would most likely be faster than moving to a different platform. I have experience with scaling up and performance tuning. I need access to traffic and performance metrics.

Is anyone working on this? I have a few suggestions that I've added on issue #69

**Comment by 141984** [comment]
If you guys need help moving to AWS, I can help

**Comment by akhulbe** [comment]
@141984 last I heard, the plan is to migrate it to state data center (based on the comment by vigneshhari  on issue #69). I think scaling up the current stack on Heroku would be faster. I don't know why it's being migrated. I don't have enough visibility into those reasons.

**Comment by alokbabu** [comment]
Deploy this to Azure Webapp which is scalable rather than spending time on load balancing it to multiple VMs. Or if the chocking point is database someone add message brokering for requests like RabbitMQ or AzureBus.

**Comment by old-M0nk** [comment]
The state data center would mean that we would have to set up our own load balancer. 
I have experience using ElasticBeanstalk on AWS. Deploying a Django App there shouldn't take much time.

Also, where do we get visibility on server load?

**Comment by JESWINKNINAN** [comment]
@akhulbe I have experienced in running high scalable apps, Beanstalk is a nice option for fast launch. @old-M0nk server load can be identified by getting into the instance which launched by the Beanstalk.
and using cloudwatch

**Comment by naveenpf** [comment]
Closing this .
