### ISSUE TITLE
Re-order districts based on geography

### ISSUE THREAD

**Issue by namboodiri** [IEEEKeralaSection/rescuekerala#213]
Might be a small change, but it can help people locate the option faster when filling out the form.

**Comment by namboodiri** [comment]
Am working on it

**Comment by irshadshalu** [comment]
Lexicographical ordering makes more sense. This has already been discussed before.

**Comment by naveenpf** [comment]
Discussed before

**Comment by namboodiri** [comment]
Ok cool..
