### ISSUE TITLE
Extract bootstrap styles used to different file and use vanilla JS.

### ISSUE THREAD

**Issue by asimqt** [IEEEKeralaSection/rescuekerala#216]
We're loading the whole Bootstrap and jQuery. We could extract these styles to a different file as we don't need every style coming with BS. Similarly we could use jqLite or vanilla JS instead of whole jQuery.

**Comment by naveenpf** [comment]
Are you planning to work on this ?

**Comment by irshadshalu** [comment]
Bootstrap will already be cached on most browsers. Extracting styles from it is a hectic task compared to the small decrease in load size. 

We need to build stuff faster and jQuery helps the cause. jqLite is considerable, but is it worth the effort is to be analysed.

**Comment by zahlekhan** [comment]
https://getbootstrap.com/docs/3.3/customize/
This allows you to remove certain components from BS. Downside is we need to host it.

**Comment by asimqt** [comment]
@irshadshalu Since this is a small site, rewriting CSS is not a very big task, I think. I'll try to work on it. Caching will only help repetitive visitors, not new visitors. (The small increase in total weight of the site affects the UX marginally since most of them will use 3G/4G in Kerala with a mobile phone.)
If someone has time, working on this will have its own advantage. I looked at the code, and the amount of JS tasks we're using is very less also. Thoughts?

**Comment by amits97** [comment]
Taking a look at this

**Comment by amits97** [comment]
- I combined the GOK, IEEE and IT mission images into a sprite for now: so that only one image would be needed to load. Saving us to use just one network call of `~11KB` instead of 3 network calls adding up to `14KB`.
- Moved JQuery and Bootstrap CDN urls to `cdnjs.com`
- DNS prefetch `cdnjs.cloudflare.com`
- Added tag to prerender `/request`
