### ISSUE TITLE
Add Google Maps for better location picker. 

### ISSUE THREAD

**Issue by ajitsen** [IEEEKeralaSection/rescuekerala#219]
Use Googles map-based location picker

**Comment by naveenpf** [comment]
Cost issues.

**Comment by ajitsen** [comment]
Issue: 
1. Reverse lookup of lat, lon to address not very close to what we can get in Google.  
2. A visual google map can be used to pinpoint the location on the map easily.

**Comment by ajitsen** [comment]
Let me figure out a feasible solution. one thing I see is https://support.google.com/crisismaps/?hl=en  

As per the policy, they do allow.
