### ISSUE TITLE
Need an API end point

### ISSUE THREAD

**Issue by shaheenkdr** [IEEEKeralaSection/rescuekerala#22]
We are working on an app to fetch all the data of people who need help with click of a single button, thinking of merging with the rescue kerala website, Can we get an API end point for the same , in case if we are pushing details to this server from the mobile app ?

**Comment by shahidhk** [comment]
https://www.django-rest-framework.org/ Can be used to create API

**Comment by ahumblenerd** [comment]
@jerinpetergeorge how much have you progressed ?

**Comment by hemanth7787** [comment]
I am also started working on it.    Hope we need authentication for the same.   Any suggestion into which auth type we should use ?  
http://www.django-rest-framework.org/api-guide/authentication/

**Comment by ahumblenerd** [comment]
@hemanth7787 Please go with token based auth.

**Comment by jerinpetergeorge** [comment]
I made an PR #73 . Suggestions pls

**Comment by hemanth7787** [comment]
@jerinpetergeorge  Good, are you working on auth as well ?

**Comment by jerinpetergeorge** [comment]
yeah

**Comment by PSNAppz** [comment]
Please do provide a page for API Documentation.

**Comment by jerinpetergeorge** [comment]
@hemanth7787 
I think you could add pagination and filtering

**Comment by jerinpetergeorge** [comment]
@hemanth7787 anyway i made a [PR](https://github.com/hemanth7787/rescuekerala/pull/1) to your repo

**Comment by hemanth7787** [comment]
@jerinpetergeorge Thanks,  I have merged and created PR #94

**Comment by kurianbenoy** [comment]
I had earlier worked on this issue and is now merged on branch app. 
check my PR on #65

**Comment by kurianbenoy** [comment]
@naveenpf @jerinpetergeorge @hemanth7787 
We need to add authentication as well as CORS and csrf excemption

**Comment by jerinpetergeorge** [comment]
@kurianbenoy  is [this DB configs](https://github.com/IEEEKeralaSection/rescuekerala/pull/65/files#diff-83251527a15f0d908d24fb8adb8fac90R109) are required ?? Seems like local DB settings

**Comment by kurianbenoy** [comment]
@jerinpetergeorge its  not required @biswaz rectified it in the subsequent commits.
@jerinpetergeorge  are you currently working on this issue?

**Comment by naveenpf** [comment]
Closing it

**Comment by jerinpetergeorge** [comment]
@kurianbenoy not yet started. I have some power supply issues here :(

**Comment by naveenpf** [comment]
Working on it

**Comment by vmwsree** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/pull/149 this is graphql auto documtation included
