### ISSUE TITLE
Stock Details that we collect from different camps

### ISSUE THREAD

**Issue by crsharat** [IEEEKeralaSection/rescuekerala#221]
A section provide detail information about the items that we collect from different camps
Like how many items are available and what more items are needed in the camps.
In this way we can control the stock items that people are providing to flood affected regions.

The volunteers in the camps update the stock details on the site and we can share this info with other camps and in other districts. 

When an particular items are transferred or received to the destination place we can update the same on the site.

Status will be like
eg: Need 1000 sanitary pads at XXX village.
4000 sanitary pads are available at YYYY camp
1000 sanitary pads is transferred via Volunteer Head to the XXX village 
1000  sanitary pads delivered at XXX village

And we can inform people that we need X numbers of particular items.

Please let me know if this issue is reasonable and we can start working on that ASAP.

Also currently AnboduKochi volunteers are collecting and providing relief items from various location in Ernakulam. We can take help from them about the stock details.

Thanks

**Comment by naveenpf** [comment]
In production now
