### ISSUE TITLE
[Needs Input] Add Malayalam string for Request Maps

### ISSUE THREAD

**Issue by Neonkraft** [IEEEKeralaSection/rescuekerala#223]
### Subject of the issue
The home page has no Malayalam description for Request Maps

**Comment by vigneshhari** [comment]
Please provide the correct translation and i'll update it

**Comment by ananthuma** [comment]
maybe സഹായം ലഭിക്കേണ്ട സ്ഥലങ്ങൾ

**Comment by vigneshhari** [comment]
Will Update ASAP

**Comment by sajeeshor** [comment]
"സഹായം ലഭിക്കേണ്ട സ്ഥലo " will be  more precise.

**Comment by Neonkraft** [comment]
I'll get this done

**Comment by biswaz** [comment]
avashymaya is better than labikenda right?

**Comment by Neonkraft** [comment]
Ok, let's decide on the string first.

**Comment by abhaikollara** [comment]
സഹായം ആവശ്യമായ സ്ഥലങ്ങൾ ?

**Comment by Neonkraft** [comment]
I second സഹായം ആവശ്യമായ സ്ഥലങ്ങൾ

**Comment by abhaikollara** [comment]
Push it, we can always change it later 🤷‍♂️

**Comment by Neonkraft** [comment]
Have updated to സഹായം ആവശ്യമായ സ്ഥലങ്ങൾ

**Comment by imismailpe** [comment]
സഹായം ആവശ്യപെട്ടവരുടെ സ്ഥലങ്ങൾ
സഹായം ആവശ്യപെട്ടവർ
സഹായം വേണ്ട സ്ഥലങ്ങൾ

**Comment by alokbabu** [comment]
സഹായം വേണ്ട സ്ഥലങ്ങൾ please

**Comment by alokbabu** [comment]
സഹായം ആവശ്യമായ സ്ഥലങ്ങൾ. Is anyone on it?

**Comment by biswaz** [comment]
#217 will merge now
