### ISSUE TITLE
Integrating Flood Map

### ISSUE THREAD

**Issue by kishorv06** [IEEEKeralaSection/rescuekerala#243]
Can we integrate flood map from https://www.microid.in/keralaflood/ ?

**Comment by R3x** [comment]
This should help us in having Real-time updates on routes for faster and better evacuation process. Also possibly for better transportation inside the state.

**Comment by vibhoothiiaanand** [comment]
Also, the google maps also have "Kerala Flood" in areas where it's affected 
So if we make that also link in this it will be beneficial for all people in more dynamic way i feel.

**Comment by aswinmohanme** [comment]
I think we should add it to the header of the existing map ? so users can navigate from there

**Comment by naveenpf** [comment]
Is there any pull request for this now ?

**Comment by gladiatorvarg** [comment]
I am working on this. Ping me if someone else is doing it.

**Comment by Rohanr007** [comment]
Highly unlikley results! 
NOGO PULL
