### ISSUE TITLE
Requests page - Location field is looking for an  exact match of the location value during search

### ISSUE THREAD

**Issue by sajeeshor** [IEEEKeralaSection/rescuekerala#244]
### Subject of the issue
Location field will return the result only if  it find an exact match in location field. And performing a case sensitive search, this will be difficult unless the person searching knows the exact string entered in the location field. Will be more useful if this can be extended to enable case insensitive like search, this may create some slowness but will be very useful. 

### Your environment
* 3.5
* firefox-61
* Ubuntu

### Steps to reproduce
Open request Requests page
Filter is based district (eg; wayanad)
Enter location (Eg:- Mananthavady) - no results displyed
Enter location as MANANTHAVADY - return 1 record.
Filter again using  district
Enter a partial string in location (Eg: Malagara  in 'Malagara chakkida padiyil')- No records returns

### Expected behaviour
It should ideally perform a case insensitive like search to get full use of this functionality.

**Comment by irshadshalu** [comment]
I think #227 solves this.
