### ISSUE TITLE
GPS coordinates when request made by third party

### ISSUE THREAD

**Issue by camaheshv** [IEEEKeralaSection/rescuekerala#249]
### GPS coordinates option to be enabled when the request is raised by relatives/friends. Latitude,longitude format to be given with validation. (Not directly picking from phone)
This will help to have better mapping of people who got trapped. 

As I see, requests are also largely made by relatives from outside Kerala.  They will be able to find coordinates and paste here correctly

**Comment by irshadshalu** [comment]
#235 addresses the same issue with proposed solution as a placepicker.

**Comment by naveenpf** [comment]
Same as #248
