### ISSUE TITLE
Include UPI option in contribute page

### ISSUE THREAD

**Issue by akhilerm** [IEEEKeralaSection/rescuekerala#25]
If possible include UPI codes in the page [To Contribute](https://www.keralarescue.in/reg_contrib/)

- cmdrf@fbl

- keralacmdrf@sib

- keralacmdrf@sbi

**Comment by ajmaln** [comment]
On it

**Comment by ahumblenerd** [comment]
Is this issue closed ?

**Comment by sprajosh** [comment]
PR submitted

**Comment by sprajosh** [comment]
couldn't find cmdrf@fbl .. so didn't add that

**Comment by naveenpf** [comment]
Fixed
