### ISSUE TITLE
Location Issue

### ISSUE THREAD

**Issue by aniledappal** [IEEEKeralaSection/rescuekerala#252]
### Subject of the issue
Capturing wrong location due to auto detection of location settings.
May be the people who needs help they don't have internet access , so others are requesting help for the victims and it is capturing the GPS location of the requestor .

### Expected behaviour
Enable manual and auto deduction of GPS location. 

### Actual behaviour
As of now automatically deducting the location details of the requester .

**Comment by emamdev** [comment]
I think, this is a major issue. People in different countries are trying to enter the information for their family members it is all over the map..
![image](https://user-images.githubusercontent.com/7717754/44235920-45440300-a179-11e8-991f-5781f17bdda9.png)

**Comment by emamdev** [comment]
Instead of location, including Address, City (District is already a drop down) can help some extend to map the area without the coordinates. Also, a landmark field can help the rescue process.

**Comment by gvmani** [comment]
Looks like related to #248

**Comment by naveenpf** [comment]
Same as #248

**Comment by a-thomas-ny** [comment]
This issue still exists in the new system.
![image](https://user-images.githubusercontent.com/7717754/44320648-527b1f00-a411-11e8-9724-e19f4795e137.png)
