### ISSUE TITLE
Crowdsourcing urgency for requests.

### ISSUE THREAD

**Issue by lunaroyster** [IEEEKeralaSection/rescuekerala#256]
There are 2781 (and counting) requests at https://keralarescue.in/data/

Reading through these, it's obvious that some are very urgent. They involve pregnant women, infants, old and ill people.

We need a way to determine the urgency of these requests.

1. We could try looking for keywords like 'Urgent', 'Pregnant', 'Trapped', 'Infant' et cetera, and use those to determine urgency.
2. Another idea is to crowdsource urgency. Let's have people vote on the apparent urgency of requests.

This way, we could help rescuers find the people with urgent needs first.

# Crowdsourcing

Let's display requests to users, and ask them to vote on their urgency. We can use this data to figure out which requests are the most pressing, and pass it on to rescuers and volunteers

The data needed for this is available right here: https://keralarescue.in/data/

We can have people located anywhere read the requests, and rate them on the basis of urgency.

**Comment by lunaroyster** [comment]
This is perhaps a distraction to have on the same platform. It might make sense to have a separate service to crowdsource urgency, and return the urgency values to rescuekerela.in

I'd love to try building out the urgency system, if it makes sense. Thoughts?

**Comment by gokulan97** [comment]
I'm no NLP expert, but think there should be APIs to detect urgencies and can we categorize it accordingly?

**Comment by SaifurRahmanMohsin** [comment]
Yep. Dumping the data in a single end point isn't the best practice. As more data enters this will take a hit on the app.

**Comment by lunaroyster** [comment]
I feel the data is somewhat chaotic: 
![image](https://user-images.githubusercontent.com/6189367/44236843-09865900-a1cc-11e8-80a0-e22a2b4d22e6.png)

Some of it is in Malayalam, and I'm not sure how useful NLP APIs are for regional languages.

I think it'd make sense for humans to do it.

**Comment by hari03** [comment]
If NLP approach is taken, then malayalam should be translated to english using Google Translate APIs before it can be processed to identify keywords.

**Comment by gokulan97** [comment]
One min, using sentiment analysis, as for what I've tried, everything is categorized as negative. Not sure if we;ll be able to filter out urgent ones.

**Comment by itssujeeth** [comment]
+1 for people based solution; as matured application of translation and nlp based classification can take time.

**Comment by camaheshv** [comment]
Rescue requests to have first priority, over other requirements, especially in night times... Crowdsourcing appears to be a good idea to rank based on prority.

**Comment by lunaroyster** [comment]
@gokulan97 Yeah, I feared the same. NLP solutions will take a while.

So I've started working on a site for crowdsourcing urgency. It'll use data from keralarescue.in/data, but I'll make sure to use a cache so I don't burden the site receiving heavy traffic.

**Comment by adamshamsudeen** [comment]
Can I get more keywords like this 'Urgent', 'Pregnant', 'Trapped', 'Infant' ? I'm working on something

**Comment by bodhish** [comment]
Add a new flag `Extremely Urgent` 
Give the description as `Only for sick and ..., ... , ...`

**Comment by lunaroyster** [comment]
Alright. Some details:

I'm using firebase's firestore to quickly get this up. My data looks like this:

requests/[request id*]/{reports:[]}

* (same as the id from data)

A report can be a value from 0 to 3, and -1, where 0 is not urgent, and 3 is very urgent. -1 is for spam. I'm saving firestore data by being super brief.

I expect to get several reports per request (Perhaps bias towards new requests?) if this takes off. That should be enough to figure out urgency.

**Comment by atmb4u** [comment]
Guys - Quick update here on the ```geolocation deduplication```
**NB: Please use the below logic to implement deduplication of requests based on location**

```scala
// data from https://keralarescue.in/data/
val data = spark.read.json("/Users/atm/lab/rescuekerala/rescue_data.json")
data
  .select('latlng)
// latitude-logntude matching
  .filter(_(0).toString.matches("[0-9]+.[0-9]+,[0-9]+.[0-9]+")) 
// Convert string lat log to double
  .map(x => x.toSeq(0).toString.split(",").map(x => x.toString.toDouble))
// 4 decimal point is enough to precisely identify land parcels - https://en.wikipedia.org/wiki/Decimal_degrees
  .map(x => ("%.4f".format(x.toSeq(0)), "%.4f".format(x.toSeq(1)))) 
  .distinct()
  .count()
```

Its implemented in scala Spark.

This is how it would look in a python context (not as efficient as the above one, but works for 1-to-1 cases

```python
def dedupe_location(location1, location2):
    try:
        return (round(float(location1.split(",")[0]), 4) == round(float(location2.split(",")[0]), 4) and 
                round(float(location1.split(",")[1]), 4) == round(float(location2.split(",")[1]), 4))
    except:
        return False
```

**Results**

On the sample set given 
Total request count - `2842`
Matched to a formatted GPS location (Lat Long) - `2161`
Deduplicated GPS locations for requests - `1628` (25% less)

**Comment by anandkp92** [comment]
I have a basic script that separates requests based on the following strings
"Urgent", "Pregnant", "Baby","Elderly","medic".

Attaching the code and the csv files for the same.

[separated-based-on-urgent-pregnant-etc.zip](https://github.com/IEEEKeralaSection/rescuekerala/files/2295630/separated-based-on-urgent-pregnant-etc.zip)

Let me know if you need me to modify the code or add it else where.

**Comment by lunaroyster** [comment]
Should newer requests be prioritized over older ones?

**Comment by SaifurRahmanMohsin** [comment]
@lunaroyster The earlier ones would be in more trouble since they are stuck in their situation for a longer time without it being resolved, which reduces their chance percentage should they be in severe trouble. When this is all over, we'll get together and watch I, Robot and I'll show you the "Save the girl" scene to explain what I mean.

**Comment by adamshamsudeen** [comment]
I have written a script to fetch and prioritize things:
 https://github.com/adamshamsudeen/Kerala-flood-priority
Priority cases after running on /data https://docs.google.com/spreadsheets/d/1QF1H5g7kXiZSGzal9zNYdreY_kqEuOBakkqlBmWJ_hs/edit?usp=sharing

**Comment by josecherian** [comment]
@adamshamsudeen , I think paralysed, paralyzed   should be  in urgency vocabulary as well. Saw many requests mentioning this.

**Comment by lunaroyster** [comment]
Site's live. GUI work needs to be done, but it works. People can start rating requests based on urgency. I'm now working on the endpoint that displays data. At some point, it'd make sense for rescuekerala.in to download the results and show crowdsourced urgency, if it works out.

**Comment by adamshamsudeen** [comment]
Please check #346
