### ISSUE TITLE
Users who are requesting on behalf of others should be able to pick the location on the map

### ISSUE THREAD

**Issue by Neonkraft** [IEEEKeralaSection/rescuekerala#261]
As of now, users who request on behalf of others have no way of picking the location. Considering that there is shortage of electricity everywhere now, it makes sense to give this feature to allow non-resident keralites the ability to mark their family/friends who are in need of help.

**Comment by aniledappal** [comment]
Looks like related to #248

**Comment by naveenpf** [comment]
already discussed.
