### ISSUE TITLE
Cannot include GPS coordinates

### ISSUE THREAD

**Issue by anandkp92** [IEEEKeralaSection/rescuekerala#264]
### Subject of the issue
Cannnot include GPS Coordinates and GPS accuracy

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

MAC OS/Firefox 

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

Go the the website https://keralarescue.in/request/ and try to add GPS coordinates, it isn't allowing me. 

![screen shot 2018-08-16 at 3 55 47 pm](https://user-images.githubusercontent.com/10254895/44239209-19bb1b80-a16d-11e8-89e6-e8f8d64de840.png)

**Comment by aniledappal** [comment]
Looks like related to #248

**Comment by anandkp92** [comment]
Ok. closing this issue then
