### ISSUE TITLE
Performance Optimization for Django App

### ISSUE THREAD

**Issue by nazeeronline** [IEEEKeralaSection/rescuekerala#269]
### Subject of the issue
Performance Optimization and Caching

For your project please implement HAProxy(Load Balancer) + Varnish (caching) so that the load is balanced and the application never caches as the major access pages of content will be served from the Varnish cache.

Ref : https://blog.disqus.com/scaling-django-to-8-billion-page-views

**Comment by naveenpf** [comment]
Closing this now. Now under control
