### ISSUE TITLE
The income help requests can have location (google maps).

### ISSUE THREAD

**Issue by jinut2** [IEEEKeralaSection/rescuekerala#27]
This could help the volunteers to pinpoint the area requesting help and make the process faster.

**Comment by ginigangadharan** [comment]
that's valid point. 
Location data is critical for any help.
Ask to include coordinates or a direct option to choose it on page

**Comment by vigneshhari** [comment]
We already have a team working for the same.

**Comment by naveenfrancis** [comment]
Same as #31. Can we close this ? And have one request open
