### ISSUE TITLE
Add Mahe as a district

### ISSUE THREAD

**Issue by sanpra1989** [IEEEKeralaSection/rescuekerala#270]
### Subject of the issue
I am guessing Mahe is also affected.

**Comment by naveenpf** [comment]
Are you planning work on this ?

**Comment by sanpra1989** [comment]
I am unfamiliar with Django unfortunately, I think I'll be of better help testing.

**Comment by Kavit900** [comment]
I think, it's something we need to add in the database right ?

**Comment by bodhish** [comment]
Done, Opening a PR

**Comment by jishnunand** [comment]
@naveenpf seems PR open for this. Need any help other this?
