### ISSUE TITLE
Search should be robust to handle different spellings of malayalam words

### ISSUE THREAD

**Issue by sanpra1989** [IEEEKeralaSection/rescuekerala#272]
### Subject of the issue
Malayalam words may often be spelled in different ways, meenakshi/minakshi, Aaluva/aluva, etc.

A quick hacky solution is to define some simple variants that cover common alternative spellings.

**Comment by naveenpf** [comment]
help required

**Comment by ajitsen** [comment]
I can take this up,  how is this implemented now, I was planning to setup a Solr instance on AWS.

**Comment by arjun23496** [comment]
If it is still not fixed, I can take this up. We can use a simple "levenstein distance" to find similar names. [https://en.wikipedia.org/wiki/Levenshtein_distance](https://en.wikipedia.org/wiki/Levenshtein_distance)
