### ISSUE TITLE
Need csv for urgent issues in dmodashboad

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#275]
### Subject of the issue
Need csv for urgent issues in dmodashboad

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by rjdp** [comment]
where is the specification of this issue/task ?
