### ISSUE TITLE
[Intertnal]Need a page for announcement from homepage 

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#279]
### Subject of the issue
Need a page for announcement from homepage 

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by theryecatcher** [comment]
Could you verify if this is what's required.

Main Page

![image](https://user-images.githubusercontent.com/16442416/44246645-38410700-a1ad-11e8-8d8f-4ce9e460dbca.png)

Announcements are maintained in the database so that they can be updated in the backend.
The announcements page

![image](https://user-images.githubusercontent.com/16442416/44246681-6de5f000-a1ad-11e8-8dbc-0a0ff5ddf766.png)

**Comment by PSNAppz** [comment]
@theryecatcher The main page looks good. No need to put announcements inside a table. You can put the heading as the link and when we click on it, the announcement expands to show the rest of the content.

**Comment by itssujeeth** [comment]
Announcements can be shown similar to blog-summaries

**Comment by theryecatcher** [comment]
@PSNAppz Thanks will look into the collapsible part. The idea of a table was to avoid editing the page for each new entry of and when they are to be added.

**Comment by namboodiri** [comment]
I think @PSNAppz was talking about the front-end table.
The backend table should stay.

**Comment by mojogeorge** [comment]
Yes, I believe.

**Comment by binu456m** [comment]
Annoucements can show as Headlines in the top of the Page. we can show as moving one (sliders) - from Left to right

**Comment by PSNAppz** [comment]
@namboodiri Yes, I was talking about the front-end only.

**Comment by jishnunand** [comment]
can't implement this as CMS??? data in the front-end keeps moving as a slider?

**Comment by theryecatcher** [comment]
Yes a ticker seems to be a better option connected with the backend table. Am trying to implement that right now let me know if anyone else wants to take it up if they can do it faster.

**Comment by gauthams09** [comment]
May I know who all are working on this currently? Is there any PR currently raised? This would be a really good feature addition. Also, test it on mobile also guys, you can use chrome dev tools for this

**Comment by theryecatcher** [comment]
I am trying to implement a ticker feed to the homepage.

**Comment by bobinson** [comment]
> I am trying to implement a ticker feed to the homepage.

We need the home page to load really fast - so no JS etc please.

**Comment by theryecatcher** [comment]
I have submitted a PR [#296](https://github.com/IEEEKeralaSection/rescuekerala/pull/296) with the basic infra. Would need to populate the DB though with the links.

**Comment by bobinson** [comment]
Anurag [11:41 AM]
Working on it.

**Comment by anuragashok000** [comment]
@cyberjithu working on this now.

**Comment by biswaz** [comment]
Need internal review @naveenpf

**Comment by bobinson** [comment]
@biswaz also from @vigneshhari 

I am skeptical about the db change involved. Please make sure that  the changes are not major.

Also the PR is under testing

**Comment by riginoommen** [comment]
Please see websockets also while on this issue  - https://www.fullstackpython.com/websockets.html

**Comment by theryecatcher** [comment]
There is a PR #296 under testing. Please work on websockets if it won't put extra load on the server. Priority would be to serve the pages as soon as possible seieng low connection speeds.
