### ISSUE TITLE
Are we in need of the district column in the lists page?

### ISSUE THREAD

**Issue by theryecatcher** [IEEEKeralaSection/rescuekerala#28]
Anyways the user selects their districts in the dropdown. It can save some data loads.

**Comment by eldhoabe** [comment]
The request are already by districts

![image](https://user-images.githubusercontent.com/4771705/44193151-fb402a80-a142-11e8-9cf9-a7fe972a9ddf.png)

**Comment by sanjuwdr** [comment]
I agree.

**Comment by theryecatcher** [comment]
My point was to avoid loading of the districts column in the page.

**Comment by eldhoabe** [comment]
yes, that a point.
Which would save more space to load the view

**Comment by vigneshhari** [comment]
You can just hit view requests without selecting any districts, which is why we have a districts column

**Comment by theryecatcher** [comment]
Ok makes sense, Thanks!
