### ISSUE TITLE
Use a simple webpage to get location at high accuracy from mobile device

### ISSUE THREAD

**Issue by imatefx** [IEEEKeralaSection/rescuekerala#280]
### Subject of the issue
User has to just open the link and their location will be reterived at high accuracy , they can select some options, 
select box with range for number of people with them
check box for 
1. Pregnant People
2. Children below 5
etc..

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
addressed in  Please take a look at the PR #266 

if possible please test the PR

**Comment by imatefx** [comment]
ok closing as it is a duplicate
