### ISSUE TITLE
Error trace shown on homepage

### ISSUE THREAD

**Issue by actuallyKasi** [IEEEKeralaSection/rescuekerala#281]
### Subject of the issue
Error trace shown on homepage

### Your environment
* Chrome
* Mac OS
### Steps to reproduce
Can't reproduce 

### Actual behaviour
PFA
<img width="1661" alt="screen shot 2018-08-17 at 11 24 23 am" src="https://user-images.githubusercontent.com/5820155/44246361-70c5fc80-a210-11e8-8c6f-53f0f9ba78a8.png">

**Comment by tachyons** [comment]
Wait, a PHP app mapped to this domain ?

**Comment by PSNAppz** [comment]
@actuallyKasi This is not the actual domain of this app. 

https://www.keralarescue.in is the right domain.

**Comment by rparjun** [comment]
@actuallyKasi  Please close this PR.
