### ISSUE TITLE
Database performance tuning

### ISSUE THREAD

**Issue by cibingeorge** [IEEEKeralaSection/rescuekerala#284]
### Subject of the issue
Database queries are not optimized.

- There are a lot of queries which are jst select * on table.. they need some sort of server side pagenation
- some of them do ORDER BY dateadded DESC.. i cldnt see indexes on the dateadded.. so we cld change them to do order by id desc
or create index on dateadded desc
- https://keralarescue.in/contactus/?district=<district> for eg is mostly static. Introduce a redis/in memory cache and cache the result of the query for lets say 5 mins (edited)
potentially cache generated content/query result on most of these pages which are almost static
- `explain analyze` any complicated queries which exist, and build custom indexes to handle them

**Comment by bobinson** [comment]
#165 - adding for reference.

**Comment by rjdp** [comment]
Have you guys tried Varnish? I can help. https://buggydebugger.com/2017/03/05/configuring-varnish-django-nginx/

**Comment by rjdp** [comment]
currently using Heroku for hosting right ? I dont think heroku has it.

**Comment by rjdp** [comment]
https://devcenter.heroku.com/articles/django-memcache , thoughts ?

**Comment by rjdp** [comment]
https://devcenter.heroku.com/articles/django-memcache , Thoughts?

**Comment by yeaske** [comment]
Since the target data is relatively smaller, the easier option is to set up a local memory cache backend rather than a memcached backend. Or at least until someone can set up a memcached one, this will provide comparatively efficient caching for static content. Thougths?

**Comment by rjdp** [comment]
@yeaske local memory us fine I think, but needs to be profiled that its fills the performance issue else use memcached

**Comment by bobinson** [comment]
db is on AWS. I believe @biswaz and @cibingeorge  are taking care of it. 

Lets keep this thread clean as this is taken care of.

**Comment by rajeeshr-punathil** [comment]
A quick PR with a couple of changes to improve some of the DB queries: https://github.com/IEEEKeralaSection/rescuekerala/pull/356
