### ISSUE TITLE
`/contactus/`info column phone number overlaps email

### ISSUE THREAD

**Issue by labtocat** [IEEEKeralaSection/rescuekerala#286]
### Steps to reproduce
`https://keralarescue.in/contactus/?district=ekm`
![screen shot 2018-08-17 at 9 30 49 am](https://user-images.githubusercontent.com/2720972/44247280-dca06900-a200-11e8-8156-5c1658f9f935.png)

**Comment by labtocat** [comment]
Please provide a db dump.

**Comment by vabhijith02** [comment]
Is DB dump available ?

**Comment by ashwinkjoseph** [comment]
@jishnunand while what you mentioned is true, I think that the author of this issue meant was talking about the two columns overlapping on mobile

**Comment by remedcu** [comment]
I just wrote a simple solution for the problem by changing the "Email" label to "Other Contacts" as well as adding malayalam translation for the same.

**Comment by iamakidilam** [comment]
@ashwinkjoseph The columns aren't overlapping on mobile as far as I've tested.
![keralarescue in_contactus__district ekm iphone 5_se](https://user-images.githubusercontent.com/17932700/44253856-91954e80-a21e-11e8-9fb6-6938031613a1.png)

Issue is with the DB I think.
