### ISSUE TITLE
IMP: Tweak CF CDN and fix redirects for speed

### ISSUE THREAD

**Issue by actuallyKasi** [IEEEKeralaSection/rescuekerala#287]
**Issue 1: HTML is not cached**
fetching HTML doc alone take ~1s (location SG) and it is because CF cache by default contents with extensions like .html.

<img width="775" alt="screen shot 2018-08-17 at 11 54 08 am" src="https://user-images.githubusercontent.com/5820155/44247181-1d09e200-a215-11e8-9f9b-9e6d508ce4ee.png">

**FIx: Create page rule to cache everything**
Follow this guide >> https://support.cloudflare.com/hc/en-us/articles/236166048. Post doing this you can verify fix by inspecting http header _cf-cache-status: HIT_

**Issue 2: Redirects causing to fetch from origin 2 times and doubles latency**
For example /request is redirecting (301) to origin /requests/ and it is easy to fix. 

<img width="773" alt="screen shot 2018-08-17 at 11 52 37 am" src="https://user-images.githubusercontent.com/5820155/44247226-69552200-a215-11e8-810d-00a5d0e5e55d.png">

**Comment by bobinson** [comment]
@actuallyKasi - please submit a PR ( https://help.github.com/articles/about-pull-requests/)

**Comment by actuallyKasi** [comment]
Also note that issue 1 can be fixed by someone with Cloudflare control panel access.

**Comment by vaishnavsm** [comment]
PR for (2) made at pull #294

Admins, please fix (1)

**Comment by bobinson** [comment]
@naveenpf   - #294  can be merged.

**Comment by MansoorMajeed** [comment]
@biswaz Can you ask someone with Cloudflare access to setup html caching? That can save a lot in terms of latency
