### ISSUE TITLE
NGO LIst , supplies  received , supply distribution pattern (  district wise ) , relief camp wise requirements

### ISSUE THREAD

**Issue by msrajesh** [IEEEKeralaSection/rescuekerala#288]
### Subject of the issue
List  of the NGOs ,   
inventory   received item wise by NGOs
districts  at  which  they (NGOs) distribute .

Requirement   of supplies  in each district ( rough  #  of camps ,  #  persons )

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
can be considered as part of #20
