### ISSUE TITLE
Request List : Columns needs to be wrapped

### ISSUE THREAD

**Issue by gvmani** [IEEEKeralaSection/rescuekerala#297]
### Subject of the issue
Columns is not getting wrapped, not fitting in one view

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.
![image](https://user-images.githubusercontent.com/920089/44249876-8d156980-a20f-11e8-8f5f-74782b34e1b9.png)

### Expected behaviour
Should be able to view without scrolling horizontally.

### Actual behaviour
Need to scroll to view important  details

**Comment by remedcu** [comment]
This issue can be closed I believe.
