### ISSUE TITLE
a database for relief camp location is required for volunteer mobilisation 

### ISSUE THREAD

**Issue by camaheshv** [IEEEKeralaSection/rescuekerala#300]
Unable to locate any database across internet where we can find details of relief camps opened.  can we have a database for that ?

A bare minimum requirement is address of the Camp and estimated number of people sheltered there..

**Comment by camaheshv** [comment]
@alexmathew sorry for delay in reply. Yes it's required and guess you've added it. I'll check and reply. 

Once water is getting under control next important thing is to give support to camps

**Comment by AlexMathew** [comment]
No, I actually haven't added anything about it. Wanted to know what exactly the requirement is.

**Comment by camaheshv** [comment]
Thanks for the new link. Who has authority to add details of camp ?

**Comment by AlexMathew** [comment]
I am not sure about this. 

Could you please explain why specifically you require this information? It'll help figure out who is responsible for it.

**Comment by camaheshv** [comment]
I'll update very soon . Meanwhile https://m.facebook.com/story.php?story_fbid=10156613281332640&id=690677639

**Comment by camaheshv** [comment]
Name of Camp, Location coordinates, Number of People, Co ordinator name and contact info (could be ward member or so)

**Comment by AlexMathew** [comment]
I'll find out about this and let you know.

**Comment by camaheshv** [comment]
I've list of places in and around Kochi and Thrippunithura in an image. Planning to convert it to a database with gps cordinates.

**Comment by camaheshv** [comment]
@AlexMathew  naveen got a seperate thread.. can i close this and join there ?

**Comment by AlexMathew** [comment]
Yes, absolutely!

**Comment by camaheshv** [comment]
please proceed and join us on #325  thanks a lot
