### ISSUE TITLE
Manually adding gps cordinates not working

### ISSUE THREAD

**Issue by iamsreeju** [IEEEKeralaSection/rescuekerala#304]
### Subject of the issue
Describe your issue here.
I tried the portal to register for rescuing my parents and relatives stuck in first floor. They don't have network, only incoming works. Portal supposed to allow adding their coordinates instead of mine. It tries to read mine and set it into readonly field. Then I had to open same in desktop and add cordinates by removing readonly attribute by using inspect.

If selecting "for others" option, no gps field at all, thats a critical field. Whats wrong with taking location coordinates or url if registering for others.

Anyway no respose received at all to the requests raised. Still not received any help and trying to reach rescue team.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by irshadshalu** [comment]
Same as #225 . Solved in #289 . Will be merged soon after testing!

**Comment by ashwinrajeev** [comment]
manually added location is getting saved in `needothers` field

`<input type="text" name="needothers" maxlength="500" class="form-control" placeholder="Enter location manually" title="" id="pac-input">`

**Comment by lijoantony** [comment]
Working on it

**Comment by ashwinrajeev** [comment]
this issue is fixed
