### ISSUE TITLE
[New] GPS Location picking 

### ISSUE THREAD

**Issue by irshadshalu** [IEEEKeralaSection/rescuekerala#31]
Add ability to automatically detect user's location when a request is being made.

**Comment by biswaz** [comment]
Workin on an app

**Comment by irshadshalu** [comment]
Great!!

I have added this for web in #29 , do merge it and mark this as closed :)

**Comment by naveenfrancis** [comment]
People may not be installing an app now. Webform also needs rough geolocation.
