### ISSUE TITLE
 mechanism to sort the requests by rescuerequests, foodrequests, medicalrequests etc

### ISSUE THREAD

**Issue by galahad** [IEEEKeralaSection/rescuekerala#311]
mechanism to sort the requests by rescuerequests, foodrequests, medicalrequests etc

### Expected behaviour
Rescue requests could be tagged with tags to indicate what type of requests we are looking for. Are you looking to be rescued 2. Are you looking for food 3. Are you looking for supplies. etc. This way 
Rescue operators could prepare themselves when reaching out.

**Comment by remedcu** [comment]
I believe that is being done in #305
