### ISSUE TITLE
Mobile app for people to be rescued

### ISSUE THREAD

**Issue by galahad** [IEEEKeralaSection/rescuekerala#313]
Mobile application for people to be rescued

## Expected behaviour
1. Quickly post rescue request
2. Post what supplies are needed
3. Find out the status of rescue - how far, how much time
4. Find out if there are any new warnings - more water coming etc.

**Comment by sanjuwdr** [comment]
We can work on that. The website should provide APIs.

**Comment by bobinson** [comment]
We need to a wait bit as db needs to be tuned. Refer #309

**Comment by godwinjoseph-wisilica** [comment]
Mention me, if starting any mobile aplication?

**Comment by galahad** [comment]
https://play.google.com/store/apps/details?id=in.keralarescue.keralarescue is another app

**Comment by galahad** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/issues/312 is the app for rescuers

**Comment by galahad** [comment]
https://github.com/vmwsree/keralarescueapp source code from Vivek

**Comment by Sheikh-Aman** [comment]
Unfortunately, I don't know anything in Fluttr, but only native Android SDK.
If there's a place I can help with my Android SDK programming knowledge, I'd jump in.
I am watching this thread.

**Comment by galahad** [comment]
#mobile-app is the slack channel for this

**Comment by Sheikh-Aman** [comment]
The address of the Slack team to join, please?
I am from Bangalore and represent a big Android developer community, I can spread the message there

**Comment by godwinjoseph-wisilica** [comment]
Can you provide skype/slack or any other channel or group to interact?
