### ISSUE TITLE
Most of the latest requests had no summary.

### ISSUE THREAD

**Issue by sanjuwdr** [IEEEKeralaSection/rescuekerala#314]
### Subject of the issue
Describe your issue here.
Most of the latest requests I checked was blank. We should do something to verify the details and to validate the data entered. 

@biswaz @naveenpf 

check these requests
https://keralarescue.in/request_details/20097/
https://keralarescue.in/request_details/19552/
https://keralarescue.in/request_details/18967/
https://keralarescue.in/request_details/18802/

**Comment by sanjuwdr** [comment]
Need to take care of these too
We should validate it with regex. 

https://keralarescue.in/request_details/20390/
https://keralarescue.in/request_details/20387/

![image](https://user-images.githubusercontent.com/36788451/44256630-5cd9c500-a227-11e8-8174-1c897962bf99.png)

**Comment by sanjuwdr** [comment]
We can use this regex.
@vigneshhari Can we add this?

**Comment by vigneshhari** [comment]
The Request was made with no other input by the user hence there is no summary

**Comment by vigneshhari** [comment]
@sanjuwdr i believe there is a PR for this

**Comment by bhavin192** [comment]
@vigneshhari you are right, here is it, just mentioning it for reference #196
