### ISSUE TITLE
Need an option to delete/report spam 

### ISSUE THREAD

**Issue by faisalnksaif** [IEEEKeralaSection/rescuekerala#318]
### Subject of the issue
When I went through the requests, I faced that there are lot of spam requests

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by gvmani** [comment]
There should be a voting/flagging mechanism to address this. Otherwise arbitrarily closing/flagging issues will cause trouble.

**Comment by faisalnksaif** [comment]
Yes, we can set a flag, if many people hit it as spam, atleast admin can hide them from the view

**Comment by bobinson** [comment]
#20
