### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by kira0204** [IEEEKeralaSection/rescuekerala#32]
Hi guys,

It's great that we all are coming together to help this website, every helping hand is required and appreciated, but before you make any contribution, below are some points that you should keep in mind.

* Select an issue that you want to work upon and comment on the same so that no other person takes up the same issue
* If the issue your PR is solving is not mentioned in the `issues` tab, first open the issue and then solve it so that other people know what you are working upon and hence we reduce the number of duplicates.

PS: Will incorporate this in Readme, afk for now

**Comment by sreecodeslayer** [comment]
As a follow up to this, would be helpful for devs to help on issues, if you guys can label them.

Currently most of the issues include feature requests, so marking them with help wanted labels and status labels of the issues.

**Comment by naveenpf** [comment]
Closing now.
