### ISSUE TITLE
The requests list table fields is not completely visible.

### ISSUE THREAD

**Issue by nabilnalakath** [IEEEKeralaSection/rescuekerala#320]
### Subject of the issue
The horizontal scrolling bar at the bottom is not immediately visible. 

### Your environment
*Chrome
* Windows

### Steps to reproduce
Go to this link- 
https://keralarescue.in/requests/?district=ekm&requestee__icontains=&requestee_phone=&location__icontains=

### Expected behavior
The table should be responsive and all fields should be properly shown.  Adjusting Date column width would also be helpful.

### Actual behaviour
Some fields in the table are not completely visible.

**Comment by justusrk** [comment]
A quick fix would be to set a max-width. But wouldnt be a good fix.

**Comment by athultuttu** [comment]
I would suggest to hide the actual google maps link. The link is a string w/o spaces and this is causing increased width in column. Hide link text and make it an actual hyperlink.

**Comment by sanjuwdr** [comment]
#324 can solve this.

**Comment by salmanulfarzy** [comment]
Screenshot of mentioned issue, Tables with large number of rows are really difficult to navigate. 

![image](https://user-images.githubusercontent.com/10276208/44256704-95799e80-a227-11e8-9768-3f162d4975c1.png)

**Comment by gvmani** [comment]
Same as #297 & #226

**Comment by storiesbyjerry** [comment]
```
`<form>
  
  <div class="form-group">
    <label for="exampleFormControlSelect1">Districts - ജില്ല:</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>State 1</option>
      <option>State 2</option>
      <option>State 3</option>
      <option>State 4</option>
      <option>State 5</option>
    </select>
  </div>
<div class="form-group">
    <label for="exampleFormControlInput1">Requestee - അപേക്ഷകന്‍റെ പേര് contains:</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="">
  </div>

<div class="form-group">
    <label for="exampleFormControlInput1">Requestee Phone - അപേക്ഷകന്‍റെ ഫോണ്‍ നമ്പര്‍:</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="">
  </div>

<div class="form-group">
    <label for="exampleFormControlInput1">Location - സ്ഥലം contains:</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="">
  </div>
  
</form>`
```

**Comment by abhilal007** [comment]
the issue seems to be a duplicate wrt #324 requesting to close this

**Comment by yaseralivp** [comment]
![img1](https://user-images.githubusercontent.com/16204646/44264401-180e5800-a240-11e8-8c44-5cc25c1ddb31.png)

I think this will give a better view, 
Provide a max-height to the div `<div id="requests-table" class="table-responsive">` and place the div `<div class="pagination">` as a sibling of `<div id="requests-table" class="table-responsive">`

**Comment by jilvin** [comment]
@biswaz @vigneshhari
