### ISSUE TITLE
To see the Status of issued requests

### ISSUE THREAD

**Issue by bohemianjock** [IEEEKeralaSection/rescuekerala#321]
### Subject of the issue
The people who have issued a request are not able to see the status of the issue. 

### Your environment
*  Python3
* Chrome 68
* Linux

### Steps to reproduce
A message showing the updated information about the actions taken to the raised issue and also provide a message if the raised issue is closed successfully.

### Expected behaviour
NO such functionality seems available.

### Actual behaviour
Adding the functionality

**Comment by pranavashok** [comment]
Issue #20 will take care of this.

**Comment by bohemianjock** [comment]
OK. Cool

**Comment by pranavashok** [comment]
Could you please close this issue @bohemianjock ?
