### ISSUE TITLE
CAMP requirements

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#325]
We need to add another page where we can view information about a camp.

- Need taluk and village options in camp registering. 
- Click on a camp name to view additional details
- Text field for "Requirements in Camp"
- Number of people for each gender

Edit: Taluk and village was added

**Comment by nithinjos** [comment]
Anyone working on it?

**Comment by naveenpf** [comment]
join slack for this

**Comment by biswaz** [comment]
Taluk and village added by me earlier

**Comment by jinojossy93** [comment]
Hi @nithinjos , @biswaz ,

I have started on this.

If anyone started on this other than me. Please DM at slack *_jinojossy93_*

**Comment by naveenpf** [comment]
can you check slack before doing

**Comment by kurianbenoy** [comment]
Duplicate of #300

**Comment by kurianbenoy** [comment]
I am starting work on this issue

**Comment by camaheshv** [comment]
Do you know where we get the name of camps ? I have names of 42 camps in Kakkanad and Trippunuthura. Working on it to get more details about it

**Comment by camaheshv** [comment]
https://drive.google.com/file/d/0B87GnrHsMIX0OXZEZVp0SkVBV3ROOXNNdkw1UW5tb3VuV1Y4/view?usp=drivesdk

**Comment by xaneem** [comment]
![requirements](https://user-images.githubusercontent.com/4448331/44277953-093c9b00-a26a-11e8-9891-55efa3d0234e.png)

<img width="1217" alt="coordinator" src="https://user-images.githubusercontent.com/4448331/44277954-0b065e80-a26a-11e8-8827-d3630ec984d7.png">

Done in PR #406
