### ISSUE TITLE
Enable JWT authorization on /data/ API Endpoint.

### ISSUE THREAD

**Issue by alokbabu** [IEEEKeralaSection/rescuekerala#326]
Could we please authorize /data API endpoint please. This is gonna be hammered when everyone starts using this endpoint to create their own version of map and all other stuff.

**Comment by gvmani** [comment]
Are you proposing this for throttling the api usage ? Otherwise on what basis will we authorize/deny access to data.

**Comment by alokbabu** [comment]
/data endpoint is public now. So literally anyone who has internet access can access this. Since it is pulling all the data at the same time it is gonna eat our dataserver. I am proposing this should be authorized by putting a bearer token on the header to accesss the api. Only flood map and other official sites should use it. This shouldn't be public. And this is vulnerable to DDos attacks as well.

**Comment by gvmani** [comment]
@alokbabu, then it should be allowed only to be used by a few apps. Giving out keys to few individuals will cause more issues.  We will need a moderators to decide on permitting access.
