### ISSUE TITLE
URGENT: Search by location does not retain keyword value for paginated pages.

### ISSUE THREAD

**Issue by alokbabu** [IEEEKeralaSection/rescuekerala#331]
Steps to reproduce:

Search by Location: Chengannur

Click on page 2 (It shows 2 page of all results not chengannur related.)

Steps to take
Add ?district=&requestee__icontains=&requestee_phone=&location__icontains=
parameters on paginated pages.

**Comment by namboodiri** [comment]
I can work on that.

**Comment by alokbabu** [comment]
Thanks @namboodiri

**Comment by namboodiri** [comment]
I've fixed the issue and made a PR. Please check #334
