### ISSUE TITLE
Migration error in latest master

### ISSUE THREAD

**Issue by rabeesh** [IEEEKeralaSection/rescuekerala#336]
Running error on local setup, in Mac (Operating system) 

### Steps to reproduce
$ python3 manage.py migrate

```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0034_auto_20180817_1337, 0034_auto_20180817_1206 in mainapp).
To fix them run 'python manage.py makemigrations --merge'
```

### Expected behaviour
Should run migration on local setup

**Comment by biswaz** [comment]
Rebase

**Comment by biswaz** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/commit/c2b099ef5b0ad21d83637238c205ea4755a56a4a fixed

**Comment by rabeesh** [comment]
@biswaz can I retry now ?
