### ISSUE TITLE
Is the data on Kerala Rescue updated?

### ISSUE THREAD

**Issue by vinodxyz** [IEEEKeralaSection/rescuekerala#339]
Guys,

Trying to work with the data from kerala rescue.
Have an urgent question.

I've been checking the data at 
https://keralarescue.in/data/

At the time I'm posting this, the latest record is of: 9:53 am IST

But, as I keep refreshing the page, the data gets updated. Is this data getting synchronized?
Would it take time to sync to latest data?

Need urgent advise. 
Thanks!

**Comment by ragsagar** [comment]
Feel free to ask around and make a PR with these details.

**Comment by ragsagar** [comment]
Afaik @biswaz and @vigneshhari can merge and deploy. Can you guys confirm?

**Comment by vinodxyz** [comment]
We're trying to visualize the areas around kerala where the requests are coming from. 
Latest data would be of a lot of help!
Thanks a lot!

**Comment by vigneshhari** [comment]
The Data is updated and The JSON contains all the requests

**Comment by vigneshhari** [comment]
The Load on our Servers are Extremely High so please limit the use of our API endpoints
