### ISSUE TITLE
Relief Camps list does not seem to work

### ISSUE THREAD

**Issue by devvb** [IEEEKeralaSection/rescuekerala#348]
### Subject of the issue
https://keralarescue.in/relief_camps does not return any results.

### Your environment
Environment independent issue.

### Steps to reproduce
Just go to https://keralarescue.in/relief_camps and select any district.

### Expected behaviour
The up-to-date list of relief camps in each district should be shown.

### Actual behaviour
Nothing is displayed.

**Comment by gvmani** [comment]
Tried relief camps and person search, not returning results. Not sure if there is data added.

**Comment by xaneem** [comment]
Data is not added. Please be patient.

**Comment by devvb** [comment]
Any chance data can be pumped in? I am sure there are sources... the site is meant to be the mouth piece of the Kerala Gov, so would really help.

**Comment by kurianbenoy** [comment]
I had tested by adding relief camps in my local server and it works perfectly fine @bobinson

**Comment by kurianbenoy** [comment]
You can close this issue

**Comment by johnsamuelwrites** [comment]
The list is still empty: https://keralarescue.in/relief_camps/?district=

**Comment by devvb** [comment]
Sure, there may not be a bug. However, there is no information on who is administering the site. If you do, can you chase them to have the data populated. This is about making the most of the tool. Right now, there is nowhere (as far as I know) where relief camps are being listed and its surely impeding work on the ground!

**Comment by SajinSabu** [comment]
Data's are added and link is working now.

**Comment by SajinSabu** [comment]
It is under testing.

**Comment by thelostone-mc** [comment]
Looks like this has been resolved ! Can we close this out ?
