### ISSUE TITLE
donation options - Request for a change.

### ISSUE THREAD

**Issue by saifali40** [IEEEKeralaSection/rescuekerala#350]
### Subject of the issue
Please add the CM relief fund options if possible, will be helpful if you add the tezID

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by realslimshanky** [comment]
I'm working on this issue.

**Comment by salmanulfarzy** [comment]
Multiple PRs exist to add UPI into contributing pages.

**Comment by gauravsaini** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/issues/402#issuecomment-413922583

**Comment by nithin19888** [comment]
+1

**Comment by benjoseph** [comment]
If information is available for how to make international donations, please add that too.

**Comment by remedcu** [comment]
Related PR's & Issues : #36 #52 #90 #141 #350 #402 #468 #510 #614 

Quoting @biswaz 

"Officials want just a link to the official portal. Sorry KSITM requirements are our first priority. I know exactly what it feels like be on the contributor side. Been there, done that."

So, I believe this can be closed.

@syam3526 @vigneshhari @vrthra @bobinson
