### ISSUE TITLE
inconsistent latlong format in /data

### ISSUE THREAD

**Issue by Vijayabhaskar96** [IEEEKeralaSection/rescuekerala#351]
### Subject of the issue
The latlong data in https://keralarescue.in/data/ has an inconsistent format

Some look like this: Neeleeswaram temple
(This isn't even helpful) 
Some look like this: 9°20'39.0" N 76°36'04.8"E
Others look like this: 8.5605784,76.8813206
(I think this is how every record should be)

**Comment by bobinson** [comment]
data cleansing effort is on. Closing.
