### ISSUE TITLE
Name field on Contact Us Page on rescuekerala should be in malayalam and english

### ISSUE THREAD

**Issue by tusharpl** [IEEEKeralaSection/rescuekerala#352]
### Subject of the issue
Most of the Name field in "Contact Us" page on keralarescue.in are in english. The ones for malappuram and thrissur have most of the names in malayalam. To make it easy, all of them should be malayalam and english.

### Your environment
* Python 3
* Chrome v66
* Llnux - Fedora

### Steps to reproduce
Click on Contact Us image on main page of keralarescue.in and select any district dropdown as malappuram or thrissur

### Expected behaviour
Names should be both in malayalam and english. It is an easy fix.

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by remedcu** [comment]
Can you please list the links so that someone can work on that ASAP.

**Comment by pranavashok** [comment]
https://keralarescue.in/contactus/?district=

**Comment by remedcu** [comment]
That needs database access to edit the names.

**Comment by pranavashok** [comment]
If someone can transliterate it, then we can ask those who have database access to update it.

**Comment by swetakum** [comment]
What's the status on this? I can pick this up , if not already picked up.

**Comment by salmanulfarzy** [comment]
I will try to translate as much as possible, How do you want the data ?

**Comment by vigneshhari** [comment]
You can use google translate plugin to translate all the text to Malayalam, Hence closing this issue
