### ISSUE TITLE
District needs and collection points not updated

### ISSUE THREAD

**Issue by bohemianjock** [IEEEKeralaSection/rescuekerala#357]
### Subject of the issue
The link for district needs and collection points returns an empty table.

### Your environment
* Python 3
* Chrome 68
* Linux Mint

### Steps to reproduce
Gather data and display it

### Expected behaviour
Table showing the district,items requires and collection point
### Actual behaviour
Blank table

**Comment by zahlekhan** [comment]
![screenshot 18](https://user-images.githubusercontent.com/27266434/44265439-23638280-a244-11e8-807d-537e07b6c042.png)
Seems to be working on my side.

**Comment by bohemianjock** [comment]
![needs](https://user-images.githubusercontent.com/26796930/44265585-d59b4a00-a244-11e8-9922-4ca07e31297d.png)






For me It's not.@zahlekhan

**Comment by bohemianjock** [comment]
Seems to be a problem with my server
