### ISSUE TITLE
Page title need to be displayed. 

### ISSUE THREAD

**Issue by DivyaRaviDivya** [IEEEKeralaSection/rescuekerala#358]
### Subject of the issue
Page Title is not available for pages like "Registered request","Request for help" etc

### Your environment
* version of your python : NA
* which browser and its version : Chrome
* OS Type (iOS/Android/Linux/Windows) : Android

### Steps to reproduce

1.Go to https://keralarescue.in
2. Click on menu options available in the page.(eg: request for help )
3.Navigate to pages( like request for help,registered requested) and observe the page title.

### Expected behaviour
For each page,page title need to be displayed

### Actual behaviour
Page titles are missing

**Comment by subins2000** [comment]
I'll work on this

**Comment by realslimshanky** [comment]
I'm working on resolving this issue.

**Comment by remedcu** [comment]
#373 has already solved this. Please merge that commit.
