### ISSUE TITLE
enable caching for /data

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#361]
### Subject of the issue
auto generate  keralaresruce.in/data

**Comment by batpad** [comment]
Just to try and throw colour on exactly what (I think) is needed here:

Every 1 minute or so, we need to query the database, and output the JSON that should be available at `/data` to a static file. Then, `/data` can always be served as a static file, so will not hit the database for every request, etc.

So, however we do this - every 1 minute (or so), we want something to trigger a python function that will read the db, and dump a static JSON file, that can then be served at `/data`.

**Comment by subins2000** [comment]
Why not have a CRON job to remake the /data every minute or so ?

**Comment by MansoorMajeed** [comment]
On a different note, we don't really have to do that. We can cache the `/data` end point for a few seconds using Nginx or varnish. That way, each request won't hit the DB and instead will be served from the cache

**Comment by cibingeorge** [comment]
Do this really need to be exposed? Can we pagenate this?

**Comment by subins2000** [comment]
Enabling caching for /data specifically in CloudFlare will help too

**Comment by batpad** [comment]
> We can cache the /data end point for a few seconds using Nginx or varnish. 

I think this would be the ideal solution. However, right now, the app is running with `gunicorn` with Heroku (which I think has some sort of load balancer in front) - hence setting this up may require deeper infrastructural changes.

> Why not have a CRON job to remake the /data static file every minute or so ?

I think that's exactly the current plan.

> Do this really need to be exposed? Can we pagenate this?

It is currently being used by the map page. I would agree though, paginating it and having the map page fetch separate pages might be best. However one caches, as this data grows, it's going to be a lot of data down the wire for a single request.

> Enabling caching for /data specifically in CloudFlare will help too

This seems reasonable if easy? cc @vigneshhari - has this been considered? We really should implement something to cache the `/data` end-point soon as the hit on the db there is pretty hard.

**Comment by MansoorMajeed** [comment]
@subins2000 Yes, that should work too
@cibingeorge I'm with you. This is a single json with the phone numbers and addresses of a lot of people. Any malicious party will be able to simply download it and use it for whatever they need.
We should not be exposing this.

As a hack, we can host it on a different port and allow only the mapping app to connect to it through firewall

**Comment by batpad** [comment]
> As a hack, we can host it on a different port and allow only the mapping app to connect to it through firewall

The mapping app is just another URL that will need to fetch this URL anyway and anyone with malicious intent would be able to call the URL directly, whether on a port or not.

If there is a concern about sensitive data being exposed via the API, this is being exposes in more places than just the `/data` end-point. I think it is a valid issue, but I think we should make a separate issue for this and not mix it with this issue, which is about caching.

**Comment by MansoorMajeed** [comment]
@batpad Fair enough. There is an issue already here https://github.com/IEEEKeralaSection/rescuekerala/issues/308

**Comment by midhunkrishna** [comment]
If this is running on heroku, then we have used https://devcenter.heroku.com/articles/scheduler with high reliability in the past. @batpad

**Comment by MansoorMajeed** [comment]
An update on cloudflare caching: Cloudflare's minimum cache expiry for free account is 2 hours. To get 1 minute expiry, we will need the business account. This is not feasible.
