### ISSUE TITLE
Application gets hang when switch between options - show rescue needed,request made for other,show all request.

### ISSUE THREAD

**Issue by DivyaRaviDivya** [IEEEKeralaSection/rescuekerala#364]
### Subject of the issue

Application gets hang when switch between options - show rescue needed,request made for other,show all request.

### Your environment
* version of your python : NA
* which browser and its version : chrome
* OS Type (iOS/Android/Linux/Windows) : Android

### Steps to reproduce
1. Go to Request Map page
2.Switch b/w options show rescue needed,request made for other,show all request

### Expected behaviour
1. App should need to work smoothly while switch b/w menus such as - show rescue needed,request made for other,show all request
2. Map should to be loaded easily
3. Map scrolling area should to be limited.

### Actual behaviour
1. Application got hang while switch b/w show rescue needed,request made for other,show all request.
2. Delay is there to load map.
3. Map gets scroll to invisible area when try to move map by touch.

**Comment by cijo7** [comment]
This is because a lot of data need to be downloaded and processed. Data fetch takes about 1 sec and then it must be processed. Mobile devices will hang. There must be more efficient end points to fetch near by data only.

**Comment by bobinson** [comment]
closing as this may be a sporadic issue.
