### ISSUE TITLE
Can a facilty to add the GPS coordinates manually be added?

### ISSUE THREAD

**Issue by saraann** [IEEEKeralaSection/rescuekerala#367]
It can help people who post request on behalf of others to add their gps coordinates manually.

**Comment by johnsamuelwrites** [comment]
It's already there. Please check the screenshot below: https://keralarescue.in/request/. Are you talking about this?
![screenshot_2018-08-17 kerala rescue](https://user-images.githubusercontent.com/8275121/44267918-48e69100-a230-11e8-87c4-5060cc417f97.png)

However, there is an issue https://github.com/IEEEKeralaSection/rescuekerala/issues/225

**Comment by saraann** [comment]
That is not working. When I click requesting for others, the text boxes goes off and if I dont tick the requesting for others, the gps coordinates text boxes are greyed off and disabled. It cannot be added manually. That is the problem

**Comment by johnsamuelwrites** [comment]
You can mark this as a duplicate of https://github.com/IEEEKeralaSection/rescuekerala/issues/304. It seems to be handled in https://github.com/IEEEKeralaSection/rescuekerala/pull/289. However, the merge is causing issues.

**Comment by saraann** [comment]
Ok, thank you.

**Comment by saraann** [comment]
Thank you. Duplicate of #304
