### ISSUE TITLE
Unable to run migration

### ISSUE THREAD

**Issue by cyriac** [IEEEKeralaSection/rescuekerala#380]
### Subject of the issue
Unable to run migrations

### Your environment
* python 3.6
* Chrome (not applicable to the issue)
* Mac OS

### Steps to reproduce
Clone the repo and run `./manage.py migrate`

### Expected behaviour
Migration runs

### Actual behaviour
Fails with following error.
```
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0035_merge_20180817_1449, 0036_auto_20180817_1500 in mainapp).
To fix them run 'python manage.py makemigrations --merge'
```

**Comment by biswaz** [comment]
Fixed in https://github.com/IEEEKeralaSection/rescuekerala/commit/139f704bd669a6393762862baab1919246fe3f2f
