### ISSUE TITLE
Hyperlinking contact numbers in view requests page

### ISSUE THREAD

**Issue by nithin-vijayan** [IEEEKeralaSection/rescuekerala#39]
Since people might access the site from mobile devices mostly, how about making the phone number a hyperlink which opens the dialer on clicking ?

**Comment by nithin-vijayan** [comment]
Raised pull request for the same.

**Comment by prathyvsh** [comment]
Added a .json file of helpline numbers here: https://github.com/studiobofa/kf2018/blob/master/helplines.json

**Comment by naveenpf** [comment]
already implemented

**Comment by nithin-vijayan** [comment]
i see this was not merged
