### ISSUE TITLE
enter location manually data goes on field " others needs"

### ISSUE THREAD

**Issue by bismillakhans** [IEEEKeralaSection/rescuekerala#391]
![screenshot from 2018-08-17 20-10-47](https://user-images.githubusercontent.com/28209728/44272368-3da85b00-a25a-11e8-89e6-9ab315fccbb0.png)
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
issue not clear.
