### ISSUE TITLE
Relief Camp details are not available

### ISSUE THREAD

**Issue by KuttanMalayali** [IEEEKeralaSection/rescuekerala#393]
### Subject of the issue
The list of Relief camps are not available on search, this should be taken care as to identify the nearest safe place.

**Comment by johnsamuelwrites** [comment]
Check https://github.com/IEEEKeralaSection/rescuekerala/issues/325. This is currently in progress.

**Comment by johnsamuelwrites** [comment]
Currently, there are results for Thrissur: https://keralarescue.in/relief_camps/?district=tcr

**Comment by sajithmohan** [comment]
currently results are coming, but there is no rescue camps added for most of the districts in system.database entry should be short code for state field (eg: ekm for Ernakulam).
is there any backend page for adding Relif Camps?

**Comment by arjunkomath** [comment]
Results are still missing for the following districts:
- Alappuzha https://keralarescue.in/relief_camps/?district=alp
- Idukki https://keralarescue.in/relief_camps/?district=idk
- Kasargod https://keralarescue.in/relief_camps/?district=ksr
- Kottayam https://keralarescue.in/relief_camps/?district=ktm
- Palakkad https://keralarescue.in/relief_camps/?district=pkd
- Trivandrum https://keralarescue.in/relief_camps/?district=tvm

**Comment by riginoommen** [comment]
Related to #423, #348, #325

**Comment by vigneshhari** [comment]
The relief camps are listed properly now hence closing this issue
