### ISSUE TITLE
Find people feature not giving any result

### ISSUE THREAD

**Issue by var23rav** [IEEEKeralaSection/rescuekerala#395]
### Subject of the issue
Find people feature not giving any result
https://keralarescue.in/find_people/?name__icontains=&phone__icontains=&address__icontains=kollam&district=&notes__icontains=&gender=0&camped_at=

### Steps to reproduce
Search people by adding any value to find people form

### Expected behaviour
Putting any value to any of the text field, wont give any result.
eg: Address: Kollam

### Actual behaviour
Expected some result, for a district

![capture](https://user-images.githubusercontent.com/7958115/44272710-32a1fa80-a25b-11e8-8b8a-d34bf24af53b.JPG)

**Comment by dipukp** [comment]
I think it is because the data has not been entered yet. Please test later and check if there is really an issue.

**Comment by voidspacexyz** [comment]
I am not sure if production has the latest code. I have tested with the most common names and I didnt get any at all

Possible issues : 
1. Not updated code
2. Migrations ?

**Comment by vigneshhari** [comment]
The data is now inserted as batches , the issue is resolved
