### ISSUE TITLE
Suggestion : To reduce Icon & English font size and Malayalam little bigger.Other state people residing in Kerala

### ISSUE THREAD

**Issue by shan-vm** [IEEEKeralaSection/rescuekerala#405]
Suggestion : 
1. To reduce Icon & English font size and Malayalam little bigger.
2. How to address other state people residing in Kerala(Can we user google builtin translator or something like that)

![screen shot 2018-08-17 at 7 28 08 pm](https://user-images.githubusercontent.com/6676205/44277534-b5bf5280-a253-11e8-9b37-e8d6d2fa6d37.png)

**Comment by remedcu** [comment]
Resource: https://translate.google.com/manager/website/

**Comment by shan-vm** [comment]
@remedcu I did your suggestion

**Comment by bobinson** [comment]
@shan-vm  - please get it tested

**Comment by shan-vm** [comment]
@bobinson 
I did test on my side with other web pages.
I am not familiar with Django/Python

**Comment by shan-vm** [comment]
@vrthra Can you help
