### ISSUE TITLE
Collecting group photos from rescue shelters and publishing

### ISSUE THREAD

**Issue by tittuvarghese** [IEEEKeralaSection/rescuekerala#409]
### Identifying people after the rescue is hard.
Rather than collecting names why can't we take group photos and publish the same in the website with shelter location and contact? So that their relatives and friends can easily track down.

**Comment by namboodiri** [comment]
That sounds a lot more easy and effective. +1

**Comment by sachushaji** [comment]
Its a nice idea +1

**Comment by bobinson** [comment]
#20 can handle this.
