### ISSUE TITLE
Create Telegram channel instead of Slack

### ISSUE THREAD

**Issue by gauravsaini** [IEEEKeralaSection/rescuekerala#413]
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by syam3526** [comment]
we already have 900+ people in slack so another movement is not possible.

**Comment by syam3526** [comment]
closing this issue as its a wont fix
