### ISSUE TITLE
Add Fixtures for initial data

### ISSUE THREAD

**Issue by xssChauhan** [IEEEKeralaSection/rescuekerala#416]
### Add fixtures
Add fixtures to provide initial data to the models.
This is necessary for testing. More importantly, it is handy for testing the search functionality and other core features.

**Comment by bobinson** [comment]
need more info

**Comment by batpad** [comment]
Similar to #481 #469

**Comment by var23rav** [comment]
@xssChauhan  @bobinson  @batpad what the plan to close the duplicated issue..
Seems like the issue counts keep increasing.. 
Authors Pls go forward and close it when you find its duplicated

**Comment by var23rav** [comment]
@xssChauhan  @bobinson  @batpad what the plan to close the duplicated issue..
Seems like the issue counts keep increasing.. 
Authors Pls go forward and close it when you find its duplicated

**Comment by vigneshhari** [comment]
There is a wiki on generating the dummy data
