### ISSUE TITLE
Tables are not showing properly in mobile

### ISSUE THREAD

**Issue by ajaykanayil** [IEEEKeralaSection/rescuekerala#42]
Guys, tables not showing properly in mobile - check these pages...

https://keralarescue.in/district_needs/
https://keralarescue.in/requests/

![img_9676](https://user-images.githubusercontent.com/7960725/44194291-2d598880-a153-11e8-8481-2a88b5ba813a.PNG)

**Comment by JijinJayakumar** [comment]
Fixed, #55 and #59 PR

**Comment by visakhsuku** [comment]
is this issue still there?

**Comment by go2hyder** [comment]
![capture](https://user-images.githubusercontent.com/10498709/44199455-406d5800-a155-11e8-8d0c-7b9e2900f4d7.PNG)

change white-space to normal

`@media screen and (max-width: 767px)
.table-responsive>.table>tbody>tr>td, .table-responsive>.table>tbody>tr>th, .table-responsive>.table>tfoot>tr>td, .table-responsive>.table>tfoot>tr>th, .table-responsive>.table>thead>tr>td, .table-responsive>.table>thead>tr>th {
    white-space: normal;
}`

**Comment by JijinJayakumar** [comment]
ya im on it and merged, removed the unwanted class, table-responsive in div, instead of editing BS

**Comment by nevinvalsaraj** [comment]
Is this issue fixed? Pulled latest, still looks compressed and overlapping to me.

**Comment by nevinvalsaraj** [comment]
Updated PR re-adding `table-responsive` class to tables to keep bootstrap responsive features.
Refer to [PR](https://github.com/IEEEKeralaSection/rescuekerala/pull/93) for more information.

**Comment by visakhsuku** [comment]
#82 could revert back for mobile phones. I am thinking it's due to my last request. lets find a better solution?
https://css-tricks.com/responsive-data-tables/

**Comment by naveenpf** [comment]
Another issue is open
