### ISSUE TITLE
Manually Updating the DB

### ISSUE THREAD

**Issue by remedcu** [IEEEKeralaSection/rescuekerala#422]
### Updating DB
We are getting many inputs in the website from different people but how many are being updated with respect to the current situation?

For that, I believe we need to have a small team of volunteer to call these people and ask about their current situation and if they are still having problem, then we can contact the respective helpline based on what their issues are. Ideally every district should have atleast 1 volunteer or we may even collaborate with some college or so who are already doing the same.

This will also solve the issue #308 to a certain level based on how many contacts we can contact in the short span of time.

### Expected behaviour
- To form a small team of volunteers equipped with mobile phones to contact each request received in the website and update based on what response we receive and connect them with the concerned people/helpline.
- To give these volunteers a limited amount of access to DB so that they can update the current list.

1. Those who are saved, that detail will be removed from the main list and added to a hidden list (just so that we retain the info, but not publicly, and also to restore the info if done by mistake)
2. Those who still need help, we need to identify the help and then provide that info to the concerned and to those who can help them.
3. Those who can't be connected should be retained publicly itself, but in a different section, where it says first point of contact tried and will be tried again after some time.

**Comment by bobinson** [comment]
need to address via #20
