### ISSUE TITLE
[Critical] - Find Relief camp drop down button returns no data

### ISSUE THREAD

**Issue by riginoommen** [IEEEKeralaSection/rescuekerala#423]
### Subject of the issue & Steps to reproduce
Describe your issue here.
1) Visit  Relief Camps | ദുരിതാശ്വാസ ക്യാമ്പുകൾ  Page
2) Select a district name
3) No data is shown on template

### Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.
<img width="1792" alt="screen shot 2018-08-17 at 11 13 34 pm" src="https://user-images.githubusercontent.com/3840244/44280938-c072eb00-a245-11e8-8f27-f31d3ad4d697.png">

**Comment by riginoommen** [comment]
I believe this page is accessed many people at a time.

**Comment by remedcu** [comment]
I can only see data when selecting Thrissur. I guess it is not a programmatic problem, rather a lack of data problem.

**Comment by jose2007kj** [comment]
how shall i help @bobinson

**Comment by bobinson** [comment]
fixing the issue

**Comment by jose2007kj** [comment]
ok @bobinson

**Comment by lijoantony** [comment]
@jose2007kj Are you working on this?

**Comment by barrenmoor** [comment]
@remedcu - Wondering how can Thrissur have like 15 relief camps registered and no other district has anything listed!

**Comment by jose2007kj** [comment]
no shall i test this

**Comment by lijoantony** [comment]
@jose2007kj No pull request yet, I am afraid.

**Comment by riginoommen** [comment]
@jose2007kj Please share the fix lets test it if it goes well we can go ahead

**Comment by lijoantony** [comment]
Looks like data needs to be populated.
Can anyone help with that?

**Comment by namboodiri** [comment]
Is there some way to copy the data from here?
[Kerala Flood Resource - Google Map](https://www.google.com/maps/d/u/0/viewer?mid=19pdXYBAk8RyaMjazX7mjJIJ9EqAyoRs5&shorturl=1&ll=11.33307747196499%2C76.11276631206056&z=10)
I was able to export the kml file and convert it to csv. But the lat_long data was not available.

**Comment by naveenpf** [comment]
Not a issue. Yet to add data from ground

**Comment by riginoommen** [comment]
@namboodiri can we use Google APIs to pull the information https://cloud.google.com/maps-platform/products/
