### ISSUE TITLE
Dev Improvement: Instructions for setting up Docker environment for development/testing

### ISSUE THREAD

**Issue by dipukp** [IEEEKeralaSection/rescuekerala#439]
### Subject of the issue
People who use docker may find it easy to setup the dev/test environment in Docker, instead of installing multiple software on their machines.

### Steps to reproduce
Not an issue, but an improvement

### Expected behaviour
Instructions are added to setup the Docker environment

**Comment by dipukp** [comment]
Someone with docker environment, please test out the steps and confirm if things are working fine as expected. Thanks!

**Comment by jerrydon** [comment]
#37

**Comment by r3dsm0k3** [comment]
I've sent a PR fixing this issue #445

**Comment by sourceflakes** [comment]
@dipukp Any particular reason why you are not using a separate feature branch to develop?

**Comment by sourceflakes** [comment]
@dipukp Refer how PL# 445 the forked repo has a clean feature branch(just an example).

**Comment by dipukp** [comment]
Closing this issue as #445 makes this one obsolete
