### ISSUE TITLE
TWO NEW OPTIONS MAY SAVE PEOPLE

### ISSUE THREAD

**Issue by a-thomas-ny** [IEEEKeralaSection/rescuekerala#449]
### Subject of the issue
https://www.youtube.com/watch?v=pGYtk8tmZyc&feature=youtu.be  I HAVE AN IMPORTANT REQUEST. THERE ARE 60 PAGES OF REQUESTS UNDER ALAPPUZHA https://keralarescue.in/requests/?district=alp&requestee__icontains=&requestee_phone=&location__icontains=. CAN WE GIVE A QUICK CHECK BOX OPTION OR DROP DOWN TO LIST THE RESCUE REQUESTS? ALSO, GIVE THE OPTION TO THE PUBLIC TO CHANGE THE STATUS TO FULFILLED SO NO NEED TO DISPLAY THAT THERE. BECAUSE RELATIVES KNOWS BETTER WHEN THEIR LOVED ONES ARE RESCUED. MOST PEOPLE IN THAT AREA ARE ABROAD WELL CONNECTED THROUGH DIFFERENT FACEBOOK/WHATSAPP GROUPS (LIKE ME). IT IS EASY TO SEND THE INSTRUCTIONS TO EVERYONE ON WHAT TO DO. PLEASE DEVELOPERS - TWO OPTIONS 1. LIST THE RESCUE REQUESTS , 2. OPTION TO CHANGE THE STATUS TO FULFILLED. PLEASE. THERE WILL BE A HUGE IMPACT YOU CAN MAKE.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
understand the importance and we are working on this. will be addressed with #20
