### ISSUE TITLE
Request status and seriousness - sorting and resource distribution

### ISSUE THREAD

**Issue by devakumar** [IEEEKeralaSection/rescuekerala#450]
### Request status and seriousness - sorting and resource distribution
Some of the issues might not be applicable now or may be resolved. We need to have tags for different needs and sort the requests accordingly. Based on the descriptions tags can be auto generated and may be give preference while presenting. With this we can have analytics as to how much of food, water, clothes or rescue are required in different places and place/direct the resources accordingly.

This is an improvement/not a real issue.
Minor updates
1. Display request time in map (requests) as in the table format
2. Mark a field for Status (Check box may do) (Resolved/Unresolved). If its resolved people can close the same. Helps in attending other issues.
3. Display the nearest rescue camp number in the same request for information (Finding it may be difficult for all the people)

Model changes:
Tags creation.
Module for auto tag generation, testing
Badges for the tag count and severity
Sorting of requests based on number of requests/types of requests/people

### Your environment
* Python 3.5
* Firefox Quantum 61.0
* Linux - Ubuntu 16.04 LTS

**Comment by bobinson** [comment]
will be addressed in #20
