### ISSUE TITLE
NGO Registration error

### ISSUE THREAD

**Issue by a-thomas-ny** [IEEEKeralaSection/rescuekerala#457]
### Subject of the issue
Phone number field is not accepting the international number. Without country code number can become a local India number

### Your environment
All browsers

### Steps to reproduce
Just try to register as a real NGO

### Expected behaviour
Phone number should accept different international formats instead of changing the end user behaviour and UX

### Actual behaviour
Giving message " Please enter a number" Screenshot below. (Also, ICNA reported this issue to me when I informed them to use this portal. Screenshot below)
![image](https://user-images.githubusercontent.com/7717754/44285725-79302e80-a234-11e8-8a39-37dc394bc8ff.png)

**Comment by nravic** [comment]
fixing rn

**Comment by bobinson** [comment]
given high priority as this will help a lot of people

**Comment by nravic** [comment]
Considering the circumstances, I'm changing the model field. We don't *need* it to be a number, so I'm going to store it as a charField

**Comment by ssat335** [comment]
Skip Person model? They can be null.

**Comment by a-thomas-ny** [comment]
Is this pushed to production? https://keralarescue.in/NGO/ Still not working

**Comment by ssat335** [comment]
I am working on this.
