### ISSUE TITLE
validation for phone number

### ISSUE THREAD

**Issue by joicemjoseph** [IEEEKeralaSection/rescuekerala#46]

**Comment by salmanulfarzy** [comment]
It currently only allows only 10 characters, But **any character** is allowed. We could restrict that to only numbers.

**Comment by PSNAppz** [comment]
I'm working on it.

**Comment by agzuniverse** [comment]
I'm almost done with this, pls do not duplicate

**Comment by PSNAppz** [comment]
Ok @joicemjoseph

**Comment by agzuniverse** [comment]
This can be closed as #84 subsumes it.

**Comment by naveenpf** [comment]
Duplicate #84
