### ISSUE TITLE
Dummy Data to fill the database

### ISSUE THREAD

**Issue by var23rav** [IEEEKeralaSection/rescuekerala#469]
### Subject of the issue
It will be better to have dummy data to see how the system works in a flow.

### Steps to reproduce
Now after you do the local setup, most of the  link gives warning messages.

### Expected behaviour
Expected to have see the basic functionality with some dummy data.
eg: Volunteer, Issues, Camp..

### Actual behaviour
Warning in most of the place

**Comment by ragsagar** [comment]
Please check if you are able to download it from here https://keralarescue.slack.com/archives/CCASHFV2B/p1534485614000100

**Comment by yeaske** [comment]
Please use this as a workaround until you have valid test data:
https://github.com/IEEEKeralaSection/rescuekerala/wiki/Create-Dummy-data
