### ISSUE TITLE
Enhancement with Google maps location services

### ISSUE THREAD

**Issue by codeslord** [IEEEKeralaSection/rescuekerala#47]
If people can mark their locations via google maps, it would be easier for the rescue teams to help them.
If possible kindly add a widget for the same. [Link]((https://github.com/erdem/django-map-widgets)

**Comment by naveenfrancis** [comment]
Same as #31

**Comment by codeslord** [comment]
@naveenfrancis  👍  Hope the above repo will speed up the process.

**Comment by naveenpf** [comment]
Already implemented
