### ISSUE TITLE
Map showing help request outside kerala.

### ISSUE THREAD

**Issue by roginthomas** [IEEEKeralaSection/rescuekerala#472]
Use this code to filter the map outside kerala. I added a regex fuction to filter data,

def mapdata(request):
    district = request.GET.get("district", "all")
    data = cache.get("mapdata:" + district)
    if data:
        return JsonResponse(list(data) , safe=False)
    if district != "all":
        data = Request.objects.exclude(latlng__exact="").filter(district=district,latlng__regex=r'^[7,8,9,1][0,1,2]?\..*,[ ]*[7][4,5,6,7]\..*').values()
    else:
        data = Request.objects.exclude(latlng__exact="").filter(latlng__regex=r'^[7,8,9,1][0,1,2]?\..*,[ ]*[7][4,5,6,7]\..*').values()
    cache.set("mapdata:" + district, data, settings.CACHE_TIMEOUT)
    return JsonResponse(list(data) , safe=False)

**Comment by roginthomas** [comment]
URL : https://keralarescue.in/map/

This map showing location outside the state kerala. If you what to filter the list of points outside kerala, you can modify the fuction mapdata() in view.py.

**Comment by ssat335** [comment]
People from overseas can make requests. I think this is acceptable and fair. It should be fixed in the user interface, that from within views.py

**Comment by jinoytommanjaly** [comment]
okk

**Comment by vigneshhari** [comment]
The issue has been resolved and hence we are closing this issue
