### ISSUE TITLE
Convert phone number field to international format

### ISSUE THREAD

**Issue by ssat335** [IEEEKeralaSection/rescuekerala#473]
Phone number field is not accepting the international number. Without country code number can become a local India number
Your environment

All browsers
Steps to reproduce

Just try to register as a real NGO
Expected behaviour

Giving message " Please enter a number" Screenshot below. (Also, ICNA reported this issue to me when I informed them to use this portal. Screenshot below)
image

**Comment by johnsamuelwrites** [comment]
Refer https://github.com/IEEEKeralaSection/rescuekerala/issues/457

**Comment by sks444** [comment]
Would be great if you could fix it in https://github.com/IEEEKeralaSection/rescuekerala/pull/470 and have a single migration file for all the Altered Field.

**Comment by ssat335** [comment]
Closing as some other commit has been pulled.
