### ISSUE TITLE
Feature request please - integrate a real-time/crowd-sourced map?

### ISSUE THREAD

**Issue by securitydaemon** [IEEEKeralaSection/rescuekerala#476]
Can we integrate a real-time/crowd sourced map showing flooded roads and areas?
A good example of such a map/location service is the following:
https://www.microid.in/keralaflood/#6.47/10.55/77.701

**Comment by Neonkraft** [comment]
Duplicate of #243

**Comment by vigneshhari** [comment]
We have integrated the flood map hence we are closing the issue
