### ISSUE TITLE
Post request data to Ushahidi instance

### ISSUE THREAD

**Issue by batpad** [IEEEKeralaSection/rescuekerala#482]
We want to push data about requests to our Ushahidi instance as well, to aid in visualizing and giving a ticketing system.

The way this would (probably) work:

 - Setup a `post-save` signal handler in the django code, which will take the data for a newly created `Request` and push it to the Ushahidi instance.

Below is some sample code to make a request to the Ushahidi instance with some data. The JSON data will need to be modified to fit the schema expected by our project on Ushahidi (@geohacker can you help with posting an example CSV of data to get an idea of the fields, etc.?)

```
import requests
import json

oauth_url = 'http://35.200.150.137/platform/oauth/token'

oauth_d = {
  "grant_type": "password",
  "scope": "apikeys posts country_codes media forms api tags savedsearches sets users stats layers config messages notifications webhooks contacts roles permissions csv tos dataproviders",
  "client_id": "ushahidiui",
  "client_secret": "35e7f0bca957836d05ca0492211b0ac707671261",
  "password": "REPLACEME", # replace with your password
  "username": "sanjaybhangar@gmail.com" # replace with your email login
}

oauth_creds = requests.post(oauth_url, json=oauth_d).text

print(oauth_creds)

access_token = json.loads(oauth_creds)['access_token']

post_url = 'http://35.200.150.137/platform/api/v3/posts/'

headers = {
    'Authorization': 'Bearer %s' % access_token
}

post_data = {'allowed_privileges': ['read', 'create', 'update', 'delete', 'search'],
 'author_email': 'null',
 'author_realname': 'null',
 'color': '#2274B4',
 'completed_stages': [],
 'contact': 'rjmackay',
 'content': "Asrang VDC of Gorkha hasn't received any help yet. Need relief efforts",
 'created': '2014-11-11T08:40:51+00:00',
 'form': {'id': '1', 'url': 'https://quakemap.api.ushahidi.io/api/v3/forms/1'},
 'id': 530,
 'locale': 'en_us',
 'message': '',
 'parent': {'id': '1', 'url': 'https://demo.api.ushahidi.io/api/v3/posts/1'},
 'published_to': [],
 'sets': ['1', '2'],
 'slug': 'chhokang-paro-village-upper-tsum-medical-ampamp-food-assistance-urgently-required-560b50a52fe02',
 'source': 'SMS',
 'status': 'published',
 'tags': [{'id': 1, 'url': 'https://quakemap.api.ushahidi.io/api/v3/tags/1'}],
 'title': 'Need help',
 'type': 'report',
 'updated': '2014-11-11T08:40:51+00:00',
 'url': 'https://quakemap.api.ushahidi.io/api/v3/posts/530',
 'user': {'id': '1', 'url': 'https://quakemap.api.ushahidi.io/api/v3/users/1'},
 'values': {'AttributeID1': ['Value 1', 'Value 2'],
  'AttributeID2': [{'lat': '2.456', 'lon': '1.234'}]}}

out = requests.post(post_url, json=post_data, headers=headers)

print(out.text)
```

^^ this script can obviously be improved - the main thing here is getting around the authorization hurdles, and the above script works for that.

cc @geohacker @vigneshhari

**Comment by geohacker** [comment]
We've been using the following CSV structure:

`district,id,location,Latitude,Longitude,latlng_accuracy,dateadded,is_request_for_others,status,needrescue,needwater,needfood,needcloth,needmed,needkit_util,needtoilet,needothers,detailrescue,detailwater,detailfood,detailcloth,detailmed,detailkit_util,detailtoilet,requestee,requestee_phone`

It's important the number fields like lat, lon, phone are Integer/float data types.
