### ISSUE TITLE
Minify/Compress static CSS and JS Files

### ISSUE THREAD

**Issue by amits97** [IEEEKeralaSection/rescuekerala#489]
### Subject of the issue
Currently, the static CSS and JS files: style.css and placepicker.js are not minified before sending to the client side. This could help us shave off valuable KBs to send over the network. 

### Your environment
* Python 3
* Chrome 68
* MacOS Sierra 10.12.6

### Steps to reproduce
Load page in browser, the static CSS and JS files: style.css and placepicker.js are not minified

### Expected behaviour
If compressed, it would help us shave off valuable KBs to send over the network.

### Actual behaviour
Static CSS and JS files: style.css and placepicker.js are not minified

**Comment by amits97** [comment]
I have started working on this using [Django Compressor](https://django-compressor.readthedocs.io/en/latest/)

**Comment by rparjun** [comment]
@amits97  please have a look at #216
