### ISSUE TITLE
Google Maps Relief Resources Page Link

### ISSUE THREAD

**Issue by ssat335** [IEEEKeralaSection/rescuekerala#500]
### Subject of the issue
Currently no way to access google relief resources page link

[https://www.google.com/maps/d/u/0/viewer?mid=19pdXYBAk8RyaMjazX7mjJIJ9EqAyoRs5&ll=10.58818077013663%2C76.59135823100587&z=8](url)

### Your environment
Python3
Mozilla

### Steps to reproduce
NA

### Expected behaviour
Ideally, an ICON in the homepage directing towards the google maps page

**Comment by arunkrishnan** [comment]
This has been implemented https://github.com/IEEEKeralaSection/rescuekerala/pull/566

**Comment by vkmrishad** [comment]
https://keralarescue.in/map-view/

**Comment by ssat335** [comment]
Merged. Closed
