### ISSUE TITLE
Add paypal payment option

### ISSUE THREAD

**Issue by avp1984** [IEEEKeralaSection/rescuekerala#509]
### Subject of the issue
Please add a paypal payment option as this is widely used in western countries as payment platform and Indian diaspora in US, EU or Oceania can contribute with much ease.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by syam3526** [comment]
Thats a very good suggestion. 
cc @vigneshhari  @biswaz

**Comment by yeaske** [comment]
This is out of scope for this git repo, as this project is just for coordinating rescue effort and distributing donations of consumer goods. This site does not handle financial donations.

**Comment by syam3526** [comment]
but we can recommend it to cmo .. to integrate in his portal

**Comment by riginoommen** [comment]
@syam3526 this should be taken in priority. can you add prioritize thos

**Comment by syam3526** [comment]
cc @IEEEKeralaSection/moderators

**Comment by remedcu** [comment]
Quoting @biswaz 

"Officials want just a link to the official portal. Sorry KSITM requirements are our first priority. I know exactly what it feels like be on the contributor side. Been there, done that."

So, I believe this can be closed.

@syam3526 @vigneshhari @vrthra @bobinson

**Comment by bobinson** [comment]
helpless :-(
