### ISSUE TITLE
Update the  Relief camp page

### ISSUE THREAD

**Issue by Richu98** [IEEEKeralaSection/rescuekerala#512]
Try to get the details where all Relief camps are located.

**Comment by ssat335** [comment]
Is fixed in #501

**Comment by aswin-jose** [comment]
when it will be reflecting on the site ? Also district wise requirements also needs to be updated.

**Comment by Richu98** [comment]
Yes, There is no information available on the site

**Comment by ssat335** [comment]
It needs to be reviewed and merged. Seems reviewed, will be merged soon.

**Comment by riginoommen** [comment]
Related to #423, #348, #325
