### ISSUE TITLE
Add road Flood map

### ISSUE THREAD

**Issue by sarath263** [IEEEKeralaSection/rescuekerala#516]
### Subject of the issue
To link road flood/blocked info map from [Microid keralaflood map](https://www.microid.in/keralaflood/#11.6/8.5404/76.9514)

**Comment by shidhincr** [comment]
@sarath263 There is already a button to check the road status on this link. 

https://keralarescue.in/map/

![kerala flood map 2018-08-18 10-56-45](https://user-images.githubusercontent.com/452711/44296118-75a0b400-a2d5-11e8-99fe-c937c75fb23a.png)


Do you mean something else ? or if this is same as the above link, let's close this issue.

**Comment by sarathxm** [comment]
Ohh k fine.

**Comment by sarath263** [comment]
Closes #516

**Comment by sarath263** [comment]
Closes #516
