### ISSUE TITLE
REDIS_URL in settings.py

### ISSUE THREAD

**Issue by SajinSabu** [IEEEKeralaSection/rescuekerala#522]
### Subject of the issue
django exit with error
django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable

### Your environment
python: Python 3.7.0
browser: Chrome 68.0.3440.106
* OS Type : Windows 10 64bit

### Steps to reproduce
Add redis-server installation instructions

### Expected behavior
Error occurs when no redis-server installation in system.  

### Actual behaviour
Update README for installation of redis-server

**Comment by bhumilharia** [comment]
If this is only for test purposes, you don't need a Redis installation on your machine (unless of course you're testing caching). This error is not because there is no Redis, it just that you haven't added `REDIS_URL` to your `.env` file

**Comment by SajinSabu** [comment]
Ok. Thank you.
