### ISSUE TITLE
OutCall Feature To Call Help Requested People and Update their Status.

### ISSUE THREAD

**Issue by vmwsree** [IEEEKeralaSection/rescuekerala#526]
### MyOperator Partnered with us
We are setting up OUtcall/IVR with help of myOperator where they can do automated calls to all our people in our database and ask them to press 1,2, or 3 for 1.Reached a safe place. 2. Isolated help still not received, if help is not received ask 1. internet connectivity 2. some other survey question about what are their requirements and how many people are there. I am starting a thread in general dm or reply me if you can help in exportig the DB and syncing the out data.

### Other Features Offered by MYOperator if developers need,
* Bulk SMS
* IVR 
* Helpline number:- one single number in front behind there are multiple numbers where we can map volunteers.

### Plan
* Start Out call on all victims of the database dump
* Receive Updated status of user.
   - If the user's phone is switched off.
   - If the User has connectivity
   - if someone in their group has  connectivity
* After receiving their status. We can send the SMS.
   - if the user database does not has location someone can write a script to fetch the location 
     description and pick the nearest geolocation from google maps.
   - after properly fixing the locations on this location, 
   - if any rescue operations are still going on that area like a chopper or food supply., we can send 
     SMS 
      notification the victim.
  - constantly check their phone's status .in each hour. to track if the user is going of line or not.

### Connect 
  -  Vivek Mohan in slack, if enough members we can start thread.

**Comment by ssat335** [comment]
keen

**Comment by Neonkraft** [comment]
This is brilliant!

**Comment by gowtham-sai** [comment]
Let's do this?

**Comment by vmwsree** [comment]
Join #outcall channel
