### ISSUE TITLE
Design breaking in desktop mode

### ISSUE THREAD

**Issue by aliaseldhose** [IEEEKeralaSection/rescuekerala#532]
### Subject of the issue
Few large location entries are causing the table width to grow beyond the viewable screen area.

### Your environment
* which browser and its version
Chrome v 68
* OS Type (iOS/Android/Linux/Windows)
Mac Os

### Steps to reproduce
Please go to this URL to reproduce the issue.
https://www.keralarescue.in/requests/?district=alp&requestee__icontains=&requestee_phone=&location__icontains=

<img width="1470" alt="screen shot 2018-08-18 at 13 18 48" src="https://user-images.githubusercontent.com/197383/44297103-4f850f00-a2e9-11e8-8f3b-1488634f3a87.png">

**Comment by aliaseldhose** [comment]
To update please change these in mainapp/templates/mainapp/request_list.html 

line: 26

		#requests-table td {
			/* Behave  like a "row" */
			border: none;
			border-bottom: 1px solid #eee;
			position: relative;
			padding-left: 50%;
/*force break the line and set a minimum width as well*/
      word-wrap: break-all;
      min-width: 100px;
		}

**Comment by SajinSabu** [comment]
No issues on Chrome v68 (Windows)

**Comment by aliaseldhose** [comment]
It depends on the page, few pages have large entries for location without line breaks, that is causing the issue. The url now changed to 

https://www.keralarescue.in/requests/?page=2&district=alp&requestee__icontains=&requestee_phone=&location__icontains=

**Comment by SajinSabu** [comment]
We can add table-layout: fixed; in table properties. But the second column is not properly aligned.

**Comment by SajinSabu** [comment]
We can change it in the second column too.

**Comment by SajinSabu** [comment]
add 'word-wrap: break-word;' in td field.

**Comment by SajinSabu** [comment]
Verify, whether it fix the issue.

**Comment by riginoommen** [comment]
Similar Issue #546 Consider the relief camp page on working on this issue

**Comment by aliaseldhose** [comment]
Verified, 'table-layout' ('fixed' for the TABLE) along with the 'word-wrap' ('break-word' for TD) solves this issue.

**Comment by riginoommen** [comment]
@aliaseldhose Use Basic Bootstrap pagination on this https://getbootstrap.com/docs/4.1/components/pagination/

Pagination also bloken

**Comment by SajinSabu** [comment]
Ok I am making an update on that relief_camps also.

**Comment by SajinSabu** [comment]
If the issue can be fixed with PR. please verify immediately.

**Comment by riginoommen** [comment]
@SajinSabu can you please look into #546

**Comment by aliaseldhose** [comment]
@SajinSabu Verified the PR, fixes this one and issue #546 for the table layout. 
@riginoommen the app is using BS 3.3.7. But will check the pagination styles for both the pages.

**Comment by athimannil** [comment]
I would like to fix this bug, Is this issue fixed ?

**Comment by SajinSabu** [comment]
Yes

**Comment by athimannil** [comment]
@SajinSabu Please let me know if there any frontend open ticket

**Comment by SajinSabu** [comment]
Take look at #546 
A search feature is what he may asking. Need clarification on this.
