### ISSUE TITLE
Do not accept Request for Help when the location is not India

### ISSUE THREAD

**Issue by DextersHub** [IEEEKeralaSection/rescuekerala#536]
The GPS Coordinates is not checked, if the location is outside of India. Especially when people are using the system from overseas to help stranded family members back at home.

**Comment by Demisane** [comment]
Bipin is working towards extracting addresses provided within the rescue requests outside India and Gopikrishna is cleaning up the data here #housekeeping_database in slack.

**Comment by DextersHub** [comment]
Gr8. Good to know. 

If you need a bogus entry already in the system to kick out, here you go:
https://keralarescue.in/request_details/32574/

**Comment by cibingeorge** [comment]
There are people submiting requests for their friends/relatives etc. So this is probably ok. Closing this for now,

**Comment by DextersHub** [comment]
What I meant was don't accept a request(popup an error msg) if the "GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ" is not an address in India and they haven't checked "Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു"

Not block the page based on ip.
