### ISSUE TITLE
[Feature Request] - Need Pagination and Search Filters for the Releif Camp Page

### ISSUE THREAD

**Issue by riginoommen** [IEEEKeralaSection/rescuekerala#546]
This feature will be a great time saving for the users. 

### Steps to reproduce
<img width="1792" alt="screen shot 2018-08-18 at 2 25 48 pm" src="https://user-images.githubusercontent.com/3840244/44297663-c65be100-a2c4-11e8-992e-ca953c0728da.png">

**Comment by SajinSabu** [comment]
Did you mean the table design?

**Comment by riginoommen** [comment]
I meant table pagination with a limit of 20 records per page
https://getbootstrap.com/docs/4.1/components/pagination/

Also additional search box for the data search

**Comment by athimannil** [comment]
@riginoommen It would be nice to add label **frontend** or **backend**

**Comment by riginoommen** [comment]
@kurianbenoy Thanks Kudos

**Comment by cosmicAsymmetry** [comment]
Add label for in progress please.
