### ISSUE TITLE
[High Priority] Map fails to load

### ISSUE THREAD

**Issue by ssat335** [IEEEKeralaSection/rescuekerala#558]
### Subject of the issue
Request Map fails to load. It shows a white screen after some initial processing

### Your environment
* Mozilla firefox
* Ubuntu 16.04

### Steps to reproduce
Click on Request Map

### Expected behaviour
Expected to see actual request mapped geospatially

### Actual behaviour
Shows white screen

**Comment by SajinSabu** [comment]
Yes. There is an issue with https://keralarescue.in/map/

**Comment by arjunkomath** [comment]
@SajinSabu @ssat335 I believe this issue has been resolved, please verify and confirm.

**Comment by bobinson** [comment]
For those who are working with /map

- Every time the map is loaded large amount of data is pulled from /data
- Please try to cache at the OSM layer / Browser side and only pull delta (not an expert in maps)
- Do not pull entire /data : PLEASE
- also third party developers and apps etc please do not scrap and create apps instead join the effort by fixing the bugs or atleast fixing the PRs.

**Comment by dsamanmishra** [comment]
Map seems to load perfectly on my system.

**Comment by shreyasgaonkar** [comment]
Seems to be working perfectly on Chrome Version# 68.0.3440.106 (Official Build) (64-bit)

**Comment by Rohanr007** [comment]
Seems to be working perfectly on Chrome! Please mark fixed issues from the tracker
