### ISSUE TITLE
Effective Utilization of collected resources - “Excess/Need” in column Relief Camp Screen for each ‘Camp’ (Camp specific requirements)

### ISSUE THREAD

**Issue by AkkoliPottammal** [IEEEKeralaSection/rescuekerala#559]
### Subject of the issue
Add new column Relief Camp Screen for ‘Camp’ specific requirements. 
It should show “Excess/Need” . This is for Effective Utilization of collected resources

Now some of the Relief camps are overloaded with resources(food/materials etc..). But other side, we don’t have  enough items in certain camps ,as per social media comments/Lives.  Let’s effectively utilize the resources by sharing it between camps . So it will be better if we add one more column in Relief Camp Screen.  Column Name: “Excess/Need” 

Let’s publish excess items in the camp along with needed items for each camp. It will help the coordinators /public in the camps to help each other internally to manage the needs, if both camps are nearby.

Also nearby people can help the Relief camp, if they know the camp specific requirements.
            This will help the people to make effective contribution based on necessity.

### Your environment
* version of your python:Python 3.7.0
* which browser and its version : Chrome 68.0.3440.106
* OS Type (iOS/Android/Linux/Windows): WINDOWS 10

### Steps to reproduce
1)	Enter following URL  Browser : https://keralarescue.in/

2)	Navigate to ‘Relief Camp’ Screen

3)	Display in contents with Necessary info of Registered Requests
https://keralarescue.in/relief_camps/?district=koz

### Expected behaviour
Now Camp details  shows ‘District’,’ Camp Name’,’ Address’,’ Contact Numbers’& ‘Registrations’
Camp specific requirements should be available in the screen .

### Actual behaviour
Now Camp row shows ‘District’,’ Camp Name’,’ Address’,’ Contact Numbers’& ‘Registrations’
 Now we don’t have Camps specific requirements in the ‘Relief Camp’ screen .

**Comment by riginoommen** [comment]
Related to #423, #348, #325

**Comment by riginoommen** [comment]
Related to #423, #348, #325

**Comment by rajeevravindran** [comment]
Hi @AkkoliPottammal , I'm thinking of working on this issue.

Just to confirm if I understand the issue correctly, the requirement is to add a new column in the "Relief Camps" screen called "Excess/Need". 
In the backend (admin/mainapp/rescuecamp/), one more TextField will be added which will store the excess resources.

Am I correct in my assumptions?

**Comment by rajeevravindran** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/10564476/44301504-b5978380-a335-11e8-9865-898c61948e8e.png)

In backend 
![image](https://user-images.githubusercontent.com/10564476/44301512-e5468b80-a335-11e8-9c32-b26295042b42.png)

**Comment by xaneem** [comment]
@rajeevravindran Please consult with @naveenpf (on slack) before you start on this.

We also have this page to view entered data:
https://keralarescue.in/camp_requirements/

**Comment by rajeevravindran** [comment]
I've added the two columns to /camp_requirements endpoint as well.
![image](https://user-images.githubusercontent.com/10564476/44301731-ef6a8900-a339-11e8-899f-2959903d2439.png)

Should I create a PR?

**Comment by naveenpf** [comment]
Not required

**Comment by naveenpf** [comment]
Modules are currently designed for IT mission requirements .

**Comment by AkkoliPottammal** [comment]
@naveenpf  @xaneem  
This page has no data
https://keralarescue.in/camp_requirements/

How can I enter details about Camp specific details ??? Excess/ needed items specific camps
Through "back end" or "front end" ?

[Please Reply - URGENT]  
NB : We have data in Excel sheet. How to feed to DB now??????

**Comment by AkkoliPottammal** [comment]
Yes. Got it.
https://keralarescue.in/add_camp_data/

**Comment by AkkoliPottammal** [comment]
This page has no data
https://keralarescue.in/camp_requirements/

How can I enter details about Camp specific details ??? Excess/ needed items specific camps
Through "back end" or "front end" ?
