### ISSUE TITLE
Relief Camp contact info

### ISSUE THREAD

**Issue by SajinSabu** [IEEEKeralaSection/rescuekerala#561]
### Subject of the issue
Relief camps information are displayed without contact number. This will make it hard for delivering food or materials. 
###Solution
Make it mandatory to add any contact number along with other relief camp information.

**Comment by riginoommen** [comment]
Related to #423, #348, #325

**Comment by bobinson** [comment]
This needs to cross referenced during sahana deployment.

**Comment by biswaz** [comment]
Relief camps (active) ones were always shown. This issue may be raised when no data was added to the db
