### ISSUE TITLE
Ushahidi? Health needs/resources mapping

### ISSUE THREAD

**Issue by ajrnair** [IEEEKeralaSection/rescuekerala#569]
### Subject of the issue
Doctor/Public health guy here, not an engineer - I am working with a few others like myself to figure out if we can implement something with a realtime crisis map like Ushahidi and some other ways to help based on experience in other disasters. Repo owner or anyone co-ordinating with govt - Please ping me back at ajrnair[at] gmail

**Comment by ajrnair** [comment]
Thanks!

**Comment by bobinson** [comment]
@ajrnair - we are glad to see the support. We working to make this live all your help is welcome. We are on Slack and also me on telegram t.me/bobinson

**Comment by ajrnair** [comment]
Thanks - can you add me to the slack workspace please? Will message you.

**Comment by ajrnair** [comment]
Email ajay [at] meradoctor.com

**Comment by bobinson** [comment]
http://bit.ly/keralarescueslack

**Comment by Rohanr007** [comment]
Integrate KeralaFights Instead of Urshahidi!!!

**Comment by ajrnair** [comment]
@Rohanr007 What is that - share a link?
