### ISSUE TITLE
Change the Status Flag from new to In Progress / Addressed when picked up by Authority

### ISSUE THREAD

**Issue by sarathsasidharan** [IEEEKeralaSection/rescuekerala#577]
### Subject of the issue
Right now the status flag in the dataset appears as new , instead of this change this to In Progress / Addressed as soon as it is picked up / clicked by authorities , this would help us to filter data based on this flag to get open requests into the dashboard

### Your environment
* python :3.6.5
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Check the json value generated by a request, you will find a value in the json element with status set to new

### Expected behaviour
This should be changed to In Progress as soon as a authority / agent clicks on this request to address it

### Actual behaviour
Right now the status stays in new

**Comment by johnsamuelwrites** [comment]
This is being tracked by the issue https://github.com/IEEEKeralaSection/rescuekerala/issues/549
