### ISSUE TITLE
Caching on pages

### ISSUE THREAD

**Issue by MansoorMajeed** [IEEEKeralaSection/rescuekerala#58]
It looks like some pages do not have caching enabled.

For example `https://www.keralarescue.in/requests/?district=alp`. It takes a second or two to load the page. And I do not see any proper cache control headers on the response.

It will be better if we can cache these pages for a minute so that sudden spike in traffic won't fry the servers.

**Comment by vigneshhari** [comment]
We'll implement the cache servers and better load management as soon as we move out of heroku

**Comment by MansoorMajeed** [comment]
Let me know if you guys need any help with the migration. Do we have a architecture planned?

**Comment by naveenpf** [comment]
Closing now.
