### ISSUE TITLE
Can't navigate from Flood map to Homepage

### ISSUE THREAD

**Issue by vkmrishad** [IEEEKeralaSection/rescuekerala#580]
https://keralarescue.in/map/

There is no go back / homepage navigation button.
![screen shot 2018-08-17 at 8 06 15 pm](https://user-images.githubusercontent.com/18536460/44299357-cafab680-a311-11e8-8004-e14435ac4006.png)

**Comment by dshreyas11** [comment]
@bobinson it's not clear to me in what way exactly testing is required?

**Comment by arunpc1711** [comment]
@dshreyas11 I think he is referring to placing a "Home" button to navigate back instead going to the previous page on the Browser.

**Comment by vkmrishad** [comment]
@dshreyas11 exactly....

**Comment by edayan** [comment]
![image](https://user-images.githubusercontent.com/4129151/44305329-79464080-a392-11e8-91b1-09a6b36b0c55.png)

pull request https://github.com/aswinmohanme/kerala-flood-map/pull/36 will do the same
