### ISSUE TITLE
UI ISSUE | Alignment issue if ‘location’ column content length exceeds in ‘Registered Requests’ screen.

### ISSUE THREAD

**Issue by AkkoliPottammal** [IEEEKeralaSection/rescuekerala#582]
### Subject of the issue
Usability issue in  ‘Registered Requests’ [screen.]
If Location column content length exceeds ,then Registered Requests’ Screen shows only “District”, “location” by default .

3 options
1)	Provide tinyurl for URL for Location content (if its URL)
2)	or make location as last column 
3)	Or Provide Scroll bar for the table 
Registered Requests’ Screen should display  “District”, “location” ,”Requestee”, “Phone” &”Date” by default. 

### Your environment
* version of your python:Python 3.7.0
* which browser and its version : Chrome 68.0.3440.106
* OS Type (iOS/Android/Linux/Windows): WINDOWS 10

### Steps to reproduce
1)	Enter following URL  Browser : https://keralarescue.in/

2)	Navigate to ‘Registered Requests’ Screen

3)	Display in contents with Necessary info of Registered Requests
https://keralarescue.in/requests/?district=

### Expected behaviour
Registered Requests’ Screen  should display “District”, “location” ,”Requestee”, “Phone” &”Date” by default . 

### Actual behaviour
“Registered  Requests” Screen has District, location ,Requestee, Phone & date . 
If Location content length exceeds ,then Registered Requests’ Screen shows only “District”, “location by default .

**Comment by SajinSabu** [comment]
Will fix that.

**Comment by SajinSabu** [comment]
#540 fixes the issue. Please verify.

**Comment by SajinSabu** [comment]
Issue fixed.

**Comment by bobinson** [comment]
@ashwinrajeev ashwinrajeev merged commit 7ec0625 into IEEEKeralaSection:master 3 hours ago
1 check passed
