### ISSUE TITLE
[doc] User manual for volunteers

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#583]
### Subject of the issue
User manual for volunteers

https://docs.google.com/document/d/1R5TphBF5D-0dRBCBNyrRdWy2uOejV4WXzo7Wu_TPr2g/

**Comment by ankithjoseph** [comment]
Is this feature up? 
this may enable anyone at a safe location with internet to volunteer and can provide assistance or like validate request received by calling the requested number.

**Comment by salmanulfarzy** [comment]
Started working on a Malayalam translation of the above document.

**Comment by dshreyas11** [comment]
Guys can we have any ivr alternative where people can press there phone's buttons to answer simple questions?

**Comment by salmanulfarzy** [comment]
Uploading PDF of above document updated till IST 03:20 AM. Please checkout and let me know if there is anything missing. 

[പ്രളയ ബാധിത പ്രദേശങ്ങളിലെ  വോളണ്ടിയർസിനുള്ള സഹായ പുസ്തകം.pdf](https://github.com/IEEEKeralaSection/rescuekerala/files/2299875/default.pdf)

**Comment by riginoommen** [comment]
@salmanulfarzy Please add this to readme.md

**Comment by anivar** [comment]
Lets close this

**Comment by salmanulfarzy** [comment]
> @salmanulfarzy Please add this to readme.md

Will send PR ASAP.
