### ISSUE TITLE
Using current or Last Mobile Location status 

### ISSUE THREAD

**Issue by LilliputGuliver** [IEEEKeralaSection/rescuekerala#589]
### Subject of the issue
Rather than prompting the user to enter their location info is it possible to gather it from the N/w operators using the numbers entered on the "https://www.keralarescue.in" website. Even if the mobile is switched off or discharged the last active location can be checked to find the location.
This location if superimposed with the flooded area map from google can help is to filter out the locations where the evacuation team has to search or visit for help.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Refer Subject 

### Actual behaviour
Refer Subject

**Comment by bobinson** [comment]
We need API and necessary access to the Telco NBI APIs. Once The access is available create another issue with the details of access, API end points and documentation.
