### ISSUE TITLE
NGO registration `phone`

### ISSUE THREAD

**Issue by ja8zyjits** [IEEEKeralaSection/rescuekerala#590]
### Subject of the issue
NGO registration has `phone` field which is not set to `required`.
Was that purposeful?

### Expected behaviour
form submission should fail and ask for phone number

### Actual behaviour
It does not require `phone` field

**Comment by anuragagrawal0430** [comment]
will fix it!

**Comment by arunthomas2213** [comment]
@anuragagrawal0430 are you working on it?

**Comment by anuragagrawal0430** [comment]
yep!

**Comment by Gotham13121997** [comment]
`phone = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list`

It has been done purposefully I guess

**Comment by ja8zyjits** [comment]
@anurag  I didn't edit it since I was not sure if it was done by purpose..I thought it needed a wider discussion.

**Comment by anuragagrawal0430** [comment]
@prasadgujar I'm already working on it!! Dude, please check all the comments before jumping on any issue

**Comment by vinyasmusic** [comment]
Is this still open ?
