### ISSUE TITLE
Help to integrate https://whatsbroadcast.com to feed the requests through WhatsApp and Facebook

### ISSUE THREAD

**Issue by alvinbush** [IEEEKeralaSection/rescuekerala#592]
### Subject of the issue
We currently have around 100 requests every hour,  currently we are validating each request on your database and updating the requests manually.

We would like to integrate our system into keralarescue.in via API so that the information can be pull/pushed via REST.

### Your environment
* PAS system
* API available 
* Cloud

### Steps to reproduce
Here is the information how to integrate our system: rest.whatsbroadcast.com API Key: 4de480819716c8bb9b6ee47139e8c6f4_10547_db046cea10940d197a44e0ef4
Documentation: https://rest.whatsbroadcast.com
### Expected behaviour
Could someone guide us how to do this?
https://bit.ly/2vUXKAX is the entry point for our integration to frontside.

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
this will be handed via #569
