### ISSUE TITLE
Add linter, tests coverage reporting, and code review service.

### ISSUE THREAD

**Issue by jilvin** [IEEEKeralaSection/rescuekerala#594]
Linter will ensure better quality code.

Code review service will enable easy review of pull requests.
https://www.codacy.com/

Test coverage reporting will enable the developers to understand how much of the code is actually covered by tests. Though this is not enough for complete confidence, it generally helps in writing more test cases(white box testing).

**Comment by bobinson** [comment]
unfortunately we can't take up this right now. We will add this along with CD and reopen this later.
