### ISSUE TITLE
New Feature Request: An option for Listing and validating fake news

### ISSUE THREAD

**Issue by sr56** [IEEEKeralaSection/rescuekerala#596]
### Subject of the issue
New Feature Request: An option for Listing and validating fake news

- The public can upload or search for authenticity of rumors.  
- Volunteers can mark it as confirmed / fake / probable / invalid or junk  etc.

### Advantages
This would help the flood victims and well wishers to get direct confirmation about fake-news and avoid panic.  Furthermore people can take better decisions before forwarding rumors.

### Expected behavior

Forms that will let the public :
- See the list of current rumors.
- Search for existing ones with text keywords.
- Report new item by Uploading rumor text / image

Forms to let the Volunteers with firsthand information 
- Verify and mark any new rumors as  Confirmed / Fake / Probable /   or Delete junk ones

 

I'm not an expert in the stack used.. but of course can try to help.

**Comment by bobinson** [comment]
#621 will provide this.
