### ISSUE TITLE
Fix pagination links in requests page

### ISSUE THREAD

**Issue by shanavas786** [IEEEKeralaSection/rescuekerala#598]
### Subject of the issue
requests page has about 480 pagination links which eats up lot of spaces.

Show only some links right and left to the selected page

![pagination-before](https://user-images.githubusercontent.com/5337197/44300486-38fca900-a325-11e8-8ef9-3a2fadf7be18.png)

**Comment by cvrajeesh** [comment]
Could anyone share data dump to test this

**Comment by shanavas786** [comment]
You can generate random data. Please refer project wiki

On August 18, 2018 9:05:04 PM GMT+05:30, Rajeesh C V <notifications@github.com> wrote:
>Could anyone share data dump to test this
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/IEEEKeralaSection/rescuekerala/issues/598#issuecomment-414066403

-- 
ഷാനവാസ്
Sent from my Android device with K-9 Mail.

**Comment by cvrajeesh** [comment]
@shanavas786 looks good to me

**Comment by JithinPavithran** [comment]
I'm working on this.

**Comment by shanavas786** [comment]
#597 is already there. please don't duplicate work

**Comment by bobinson** [comment]
@JithinPavithran You can help to test the PR (#597)

**Comment by gauthams09** [comment]
PR has been marked as tested, we need to merge it

**Comment by shiv19** [comment]
#597 has been merged.
Please close this issue.
