### ISSUE TITLE
Should we build an option to export the all requests in to an excel file? so that rescuers can make use of this filtered data by location.

### ISSUE THREAD

**Issue by bibinantony009** [IEEEKeralaSection/rescuekerala#612]
### Subject of the issue
Enhancement suggestion to add capability to export the data based on filters

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Export button in the View all requests page, with capability to filters (eg- district)

### Expected behaviour
Export button in the View all requests page, with capability to filters (eg- district)

### Actual behaviour
If this suggestion is accepted, we could analyze further to bulid this

**Comment by msrshahrukh100** [comment]
i am adding django  import export to the requests model

**Comment by bibinantony009** [comment]
Is this the plug-in to export the data from datatables?

**Comment by bibinantony009** [comment]
can we use data table plugin to offer export options? this could solve pagination issues too.. 
https://datatables.net/extensions/buttons/examples/html5/outputFormat-function.html

**Comment by msrshahrukh100** [comment]
yes it'll allow the data to be imported or exported as csv, xls etc formats, but the problem is it is giving issues with django 2.1. I am on it

**Comment by ssat335** [comment]
Proposed a solution in https://github.com/IEEEKeralaSection/rescuekerala/issues/617 

See skelt implementation in https://processkeralarescue.herokuapp.com/

**Comment by bobinson** [comment]
#621 will provide this feature.

**Comment by bibinantony009** [comment]
@bobinson Just realized that this case has been closed, we have created this enhancement and it's working.. could we raise a PR and push this?
