### ISSUE TITLE
de-cluttering data: avoid possible duplication by showing warning like /request already registered/.

### ISSUE THREAD

**Issue by ankithjoseph** [IEEEKeralaSection/rescuekerala#613]
### Subject of the issue
avoid possible duplication by showing warning lyk /request already registered/.

### Your environment
* Chrome  Version 68.0.3440.106 (Official Build) (64-bit)
* Windows

### Steps to reproduce
https://keralarescue.in/requests/?district=ekm&requestee__icontains=&requestee_phone=&location__icontains=

### Expected behaviour
avoid possible duplication by showing warning lyk /request already registered/.

### Actual behaviour
![we](https://user-images.githubusercontent.com/22425027/44301438-4b321380-a334-11e8-881d-382b67fe209f.PNG)

**Comment by ankithjoseph** [comment]
@gauthams09  as you mentioned "What we can do is take multiple fields such as location, name, phone and then check the duplication"
 adding to it

- also the time of report and user session // as seen in screenshot attached(may caused due to delayed feedback after submitting request , network issues ,  user clicking submit multiple times)

**Comment by bobinson** [comment]
This will increase the number of queries to the db (especailly LIKE/SELECT etc) as we don't have a Solr /Lucene / ES indexing. So this has to be implemented carefully.

**Comment by mithunmanohar** [comment]
Suggestion: Existing help request data can be periodically indexed in a service like [algolia](https://www.algolia.com/)(free for opensource) which provides a scaleable api we can use out of box in the help request page of kerala rescue. A full text search can bring the matching results to the page- which allows user to decide whether to post the request again.
https://github.com/algolia/algoliasearch-django-example

**Comment by ideepakkrishnan** [comment]
Instead of restricting the duplicate entry altogether, we can use this as a way to figure out the relevance of each request.
What I mean is if we have a request which was logged, say, yesterday and someone is trying to add a duplicate one today, we can pull the old request to the top of the list.

**Comment by ankithjoseph** [comment]
@bobinson instead of validating duplicate entry at the entry stage.. can the data available be refreshed at certain time intervals to check for duplication externally....

**Comment by ankithjoseph** [comment]
de-cluttering data is essentially at this stage.

**Comment by ankithjoseph** [comment]
closing #621 may solve this

**Comment by bobinson** [comment]
> closing #621 may solve this
yes and thus closing. 

Also we would need help with #621 - especially search/caching etc. if anyone here has expertise, please ping via slack

@mithunmanohar #621 is LAMP stack. help needed in any case. Also relief module needs help. do help by submitting PRs
