### ISSUE TITLE
Voting for freshness/validity of a Demanded Comodity 

### ISSUE THREAD

**Issue by LilliputGuliver** [IEEEKeralaSection/rescuekerala#615]
### Subject of the issue
 Currently we are not able to identify if a need cited 3 hrs back is still valid or not and hence mobilizing forces towards meeting that demand may prove futile in the end

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
 We need to have a way to list a demand at a place and people to be able to publicly vote for it's relevance , with time the validity should decrease and people should be able to mark the demand as met or not met  ( increasing validity ) 
### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by bobinson** [comment]
good idea and #621
