### ISSUE TITLE
Add S3 support for Announcements Model

### ISSUE THREAD

**Issue by kracekumar** [IEEEKeralaSection/rescuekerala#623]
### Subject of the issue
- Announcement model has an image and file field. All these data should be stored in S3 bucket.

### Expected behaviour
- Announcement list page should link images and uploads to S3 URL.

**Comment by akshayjoyinfo** [comment]
I am testing this one.

**Comment by bobinson** [comment]
> Announcement model has an image and file field. All these data should be stored in S3 bucket.

Do we have cloudfront ?

**Comment by kracekumar** [comment]
No cloudfront setup @bobinson

**Comment by akshayjoyinfo** [comment]
There are couple of issues in this PR.

1. When we make pinned announcements 
   Then the pinned announcement won't shown in the list ( but shows in Red color as priority, but no hyperlink for anouncements
![s3 aaaa](https://user-images.githubusercontent.com/1292985/44302908-51ce8400-a350-11e8-95e5-8d7fe727b974.PNG)

2. What if the annoucement team uploads file (with same name, chances are there) in that s3 will throw exception, 

![image](https://user-images.githubusercontent.com/1292985/44302915-85111300-a350-11e8-950f-c74c982c5f8b.png)


@kracekumar , @biswaz , @bobinson  -- go through my comments
