### ISSUE TITLE
Write tests so that it doesn't break with new merges

### ISSUE THREAD

**Issue by MansoorMajeed** [IEEEKeralaSection/rescuekerala#63]
There should be tests written that makes sure that the core functionalities are unaffected. Ideally, a CI should be setup which will run all tests on open PRs to make sure that the merge doesn't break the app

**Comment by tachyons** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/pull/13 CI config is here, But we have 0 tests for now

**Comment by vineethkartha** [comment]
Can some one add the list of the core functionalities that need to be tested.

**Comment by asimqt** [comment]
Can we start with Request for help Form? It's the most important feature. (Validation, Submit, Edge cases)

**Comment by ragsagar** [comment]
@vineethkartha Are you working on this?

**Comment by asjadnabeel** [comment]
Kindly somebody configure RestAPI for "help request" models in the server (i'm not good in that, i am trying now ).

i will develope an Android app for registering and viewing help requests and other basic facilities. Tomorrow

**Comment by abhn** [comment]
Looping myself into this thread.

**Comment by ragsagar** [comment]
I am adding some tests for views

**Comment by pranavashok** [comment]
PR #268 seems to have fixed this issue. Probably it could be closed.

**Comment by MansoorMajeed** [comment]
@batpad if you can confirm that the tests are good enough to test the core functionalities, we can close this issue

**Comment by batpad** [comment]
We probably won't have "full test coverage" for a while, but that's totally fine. I think the current tests are great and give a fair degree of confidence. I'm +1 to closing this.
