### ISSUE TITLE
Update readme with steps to generate migration files

### ISSUE THREAD

**Issue by yeaske** [IEEEKeralaSection/rescuekerala#630]
### Subject of the issue
Readme should be updated to show steps to generate migration files after adding/modifying model fields. Many PR are failing build because they don't generate migration scripts or manually create a conflicted one. 

### Your environment
N/A

### Steps to reproduce
N/A

### Expected behaviour
Readme should be updated to show steps to generate migration files

### Actual behaviour
Readme does not contain steps to generate migration files.

**Comment by shubhamgoyal42** [comment]
I've added this in wiki page.
https://github.com/IEEEKeralaSection/rescuekerala/wiki/Contribution-Guidelines#creating-migration-files

Let me know if I should write this somewhere else.
