### ISSUE TITLE
The death of /data

### ISSUE THREAD

**Issue by lunaroyster** [IEEEKeralaSection/rescuekerala#634]
The endpoint at keralarescue.in/data provided all the requests made on the website. It was extremely convenient to build tools using that, so I built a tool to [crowdsource the urgency of requests](https://kerala-crowdsource.itsarnavb.me/). It took off and many people are using it right now to triage requests. I made sure to cache it on my end, so I wasn't burdening keralarescue.in. 

Since /data has been down, we're not able to retrieve and triage new requests. 

1. Is there an alternative endpoint to download the latest data available now?
2. Will there be one? Perhaps using pagination to avoid overload?
3. Or, could access be provided to folks who've built tools using it? (cc: keralafights.com)

**Comment by lunaroyster** [comment]
Tools using /data:

https://kerala-crowdsource.itsarnavb.me
https://keralafights.com
https://processkeralarescue.herokuapp.com/

**Comment by biswaz** [comment]
Solutions at work

**Comment by ashuthoshgowda** [comment]
Can we close this?
I think this is resolved

**Comment by ashuthoshgowda** [comment]
Sorry, /data 
crashed again!!!!

**Comment by lunaroyster** [comment]
@biswaz @ashuthoshgowda Is there an alternative yet? I think #637 adds a paginated version that would be nicer on the database.

**Comment by shajith** [comment]
Note that /data was only showing requests with a valid lat/lng, intended to support the map page. 

We had to take it down because it wasn't going to scale with our data growth. you can get a SQL dump in slack - we have one pinned in #devops, and you can ask if you want a more fresh one. Come talk in slack if you'd like something different to get to the data.

**Comment by lunaroyster** [comment]
@shajith Awesome. Thanks!

**Comment by cijo7** [comment]
@biswaz it is not just DB. The client side was also experiencing lag due to huge amount of data. You need to serve a filtered static resource that may be updated every few minutes.Use django-cron for that. Somebody told me that data was already being cached. Who is working on it?

**Comment by vigneshhari** [comment]
/data is alive with pagination now, closing this isue
