### ISSUE TITLE
Announcements page file not found 

### ISSUE THREAD

**Issue by kurianbenoy** [IEEEKeralaSection/rescuekerala#636]
### Subject of the issue
A file not found error is show when I am trying to download page requirements for next 30 days
![screenshot from 2018-08-19 01-46-13](https://user-images.githubusercontent.com/24592806/44302962-b0e0c880-a351-11e8-9ce6-cb8e30a2f422.png)

### Your environment
* Firefox 61
* Linux

### Steps to reproduce
https://keralarescue.in/announcements/
Go to https://keralarescue.in/announcements/
and download attachment for *project requirements for next 7 days*

**Comment by sebinbenjamin** [comment]
Not duplicate. Reproduced the issue.

**Comment by r-tock** [comment]
This seems to have been fixed

**Comment by kurianbenoy** [comment]
You are right @r-tock . I am closing this issue
