### ISSUE TITLE
Adding Hyperlinks to Other Contacts on Contact Us page.

### ISSUE THREAD

**Issue by swetakum** [IEEEKeralaSection/rescuekerala#646]
### Subject of the issue
Adding Hyperlinks to Other Contacts on Contact Us page. Currently, the primary contact made a link, but not the other contacts, which contains mostly mail id or additional phone numbers

### Your environment
* Python 3.6
* Chrome
* OS Type Windows

### Steps to reproduce
https://keralarescue.in/contactus/?district=alp

### Expected behaviour
Other contacts should also be hyperlinks

### Actual behaviour
Other contacts are not hyperlinks

**Comment by xaneem** [comment]
Adding something like this should work. We already have it on Relief Camps list page. Please raise a PR.

```
<script>
  window.onload = function() {
    $('.phone-links').each(function () {
      var content = $(this).html();
      // Convert phone numbers to links
      links = content.replace(/[0-9 ]{10,15}/g, "<a href=\"tel:$&\">$&</a>");
      $(this).html(links);
    })
  }
</script>
```

**Comment by swetakum** [comment]
Thanks @xaneem. I will do the needful.

**Comment by shiv19** [comment]
@swetakum 
That's because the data in other category was supposed to be emails
https://github.com/IEEEKeralaSection/rescuekerala/blob/c08347ed52bc1643728172e11498f3d1853cfdaa/mainapp/templates/mainapp/districtmanager_list.html#L24

Take a look here 🤔

**Comment by dsamanmishra** [comment]
The text entries for other contact field are highly variable, containing email ids at some places, multiple phone numbers with helper texts, phone numbers with spaces and hyphens at some places; so adding an href tag from code wont be the best idea. Instead as @prahaladbelavadi pointed out, the db has to be sanitized or else the fields can remain as they are. I believe this issue can be marked as closed if the column was expected to contain any form of data without any constraints.

**Comment by swetakum** [comment]
I agree with @dsamanmishra  @prahaladbelavadi . Closing this issue.
