### ISSUE TITLE
Error while saving requests under https://volunteers.keralarescue.in/view/data - Validation ErrorStage 'Review' is required before publishing

### ISSUE THREAD

**Issue by renjupaul** [IEEEKeralaSection/rescuekerala#647]
### Subject of the issue
some users are reporting errors while saving the requests here -> https://volunteers.keralarescue.in/views/data. It says 

> Validation ErrorStage 'Review' is required before publishing.

  Are we aware of any such problem? He was trying to save from a status "Under Review" to "Published".

I got it from a whatsapp user. 
![whatsapp image 2018-08-18 at 22 27 44](https://user-images.githubusercontent.com/375841/44304627-dbbe2300-a337-11e8-8c11-dfc321faf0b7.jpeg)
![issue_from_whatsapp](https://user-images.githubusercontent.com/375841/44304628-e4aef480-a337-11e8-936f-e006127b26c6.png)

**Comment by mahesh5u** [comment]
if the user mark the task as complete by selecting the button this error disappears while saving..please advise if that is the additional step required , otherwise please mark it a high priority defect required immediate fix.

**Comment by BenoyStephen** [comment]
<img width="1280" alt="screen shot 2018-08-19 at 08 33 52" src="https://user-images.githubusercontent.com/42506902/44305483-dd1e3880-a395-11e8-894c-2c90bc7020aa.png">
This is how my screen was. We need to forward this case immediately he has been stuck for the last couple of days and all that people are doing are calling and collecting information. Need to move this quickly

**Comment by bobinson** [comment]
looking into this on priority

**Comment by gbhobe** [comment]
Looks like this requires 
1. User to be logged in
2. The `task complete` button to be toggled.

This is a validation step. Perhaps we can take a look at the settings to turn this review step off. But it might increase chances of spam.
