### ISSUE TITLE
Duplicate records in requests

### ISSUE THREAD

**Issue by preethit** [IEEEKeralaSection/rescuekerala#648]
### Subject of the issue
Searching by requests per district, there duplicate records for requests.

### Your environment
* version of your python

* which browser and its version
Safari 
* OS Type (iOS/Android/Linux/Windows)
iOS
### Steps to reproduce

1. Search request
2. Select Pathanamthitta 
3. See duplicate records for 

Achankunju cg | 9656777023 . 
Achankunju cg | 9656777023

### Expected behaviour
Check for duplicates so that the database doesn't get overloaded
### Actual behaviour

Duplicate records

**Comment by aakashaggarwal** [comment]
@ajaypc Are you working on it? Or can I pick it up?

**Comment by ajaypc** [comment]
I am not able to reproduce this issue. Not working on it. You can pick up if possible

**Comment by preethit** [comment]
![image](https://user-images.githubusercontent.com/3870366/44304965-2476db80-a33a-11e8-9680-79712c5f6226.png)

**Comment by aakashaggarwal** [comment]
Sure, picking it up.

**Comment by riginoommen** [comment]
I saw some duplicate issue related to this. Let me link it

**Comment by ferricfury** [comment]
hi, we need to normalize names ie. all upper and remove special characters excluding Malayalam script. then we can clearly identify duplicates and mark 1st record with an inactive/duplicate flag. I am assuming the last record will be more accurate. also issue with requests is that multiple requests can come from the same person. we can only deal with this if we know that the previous request was fulfilled

**Comment by riginoommen** [comment]
#173 its status in progress
