### ISSUE TITLE
[important from KSITM]  Data Collection

### ISSUE THREAD

**Issue by syam3526** [IEEEKeralaSection/rescuekerala#650]
We are going to launch a massive field data collection on camps. however, the volunteers going there may not have data in proper format (it may be in paper as well) can we have a provision to upload scanned images (of that paper) on to our system and have it available in backend (web) somewhere . I will have operations team in backend going through each such paper reports and convert them onto our format and enter

**Comment by arunkrishnan** [comment]
I am working on it

**Comment by ferricfury** [comment]
is this done? can we add emergency contact number/name and relation to the file

**Comment by bobinson** [comment]
I need more information on this as we will be using Ushahidi for the data import / export etc. Also there is someone working on data export for 2 days.
