### ISSUE TITLE
Relief camp mobile app

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#652]
#639

**Comment by LilliputGuliver** [comment]
Visualize it this way as everyone stranded is an uber traveler and every rescue team is a uber driver plus the food provider is also a driver and the food requester is like a traveller. 
Also to track people that are picked up , its like me dropping a pin manually / through GPS etc but the Pin has got in addition to coordinates the mobile number of the people as the key , and then the rescue person on the app parking the pin and picked up and dropped to camp location. This should be searcheable by public using mobile number , so traceability is also solved.

**Comment by naveenpf** [comment]
We have the requirements from IT mission. Just implement that.
