### ISSUE TITLE
Phone number validation failing for land line numbers in https://keralarescue.in/request/

### ISSUE THREAD

**Issue by jojyva** [IEEEKeralaSection/rescuekerala#654]
Phone number validation failing for land line numbers in https://keralarescue.in/request/

Live- Prod
### Steps to reproduce
enter phone number 04772222222 in phone number field of  https://keralarescue.in/request/

### Expected behaviour
Phone number should be accepted

### Actual behaviour
Getting error message "Please Enter 10 digit mobile number"

**Comment by aakashaggarwal** [comment]
Can add a proper validation for landline phones, but the error says mobile number. Is that on purpose?

**Comment by Kavit900** [comment]
Working on it, we can say invalid phone number.

**Comment by Gotham13121997** [comment]
We also need to truncate the 0 in case a number is entered. This is what is causing the problem.

**Comment by jojyva** [comment]
Looks like the code is yet to be fixed to prod/live.

**Comment by bobinson** [comment]
#713 also has the same issue. closing this and working on #713
