### ISSUE TITLE
New Feature to update the existing requests

### ISSUE THREAD

**Issue by tvek** [IEEEKeralaSection/rescuekerala#656]
### Subject of the issue
New Feature to update the existing requests with new time or more description without editing number or name etc.

### Your environment
Production System - Keralarescue.in

### Steps to reproduce

1. Visit the "Registered Request" section
2. Search with phone number 7559032758.
3. You can see that same details is getting duplicated only by time being updated. they want the info to be shared that he's still missing by updating the time or even little description for future so that they can explain why they are not getting reached out.
4. This way we can prevent duplication of data

### Expected behaviour
1. Whenever a user enters already existing number inform the user do you want to update this existing one or create new one.
2. If Existing they can update some fields other than primary field(phone, name).

### Actual behaviour
Currently that feature is not available.

**Comment by rmdso** [comment]
Also, when viewing a 'Registered Request' we should show other requests made from the same phone number below the request that is currently being viewed.

**Comment by shajith** [comment]
we merged a request update feature earlier today, screenshots etc here:
https://github.com/IEEEKeralaSection/rescuekerala/pull/803

also has API support: https://github.com/IEEEKeralaSection/rescuekerala/blob/master/mainapp/api_docs.md
