### ISSUE TITLE
Please Correct the Message on the tiles of the keralakescue.in

### ISSUE THREAD

**Issue by riginoommen** [IEEEKeralaSection/rescuekerala#670]
### Subject of the issue
Message on the Blocks looks confusing and it misleads users 
<img width="255" alt="screen shot 2018-08-19 at 1 07 26 pm" src="https://user-images.githubusercontent.com/3840244/44306670-329d1a00-a383-11e8-99b9-32ecdde599b7.png">

**Comment by shubhamgoyal42** [comment]
![homepage](https://user-images.githubusercontent.com/22051142/44306736-6a6f8600-a3b2-11e8-962c-ebdc7ad881fa.png)
Looks fine on my system
