### ISSUE TITLE
Constant spikes of request handlers in Django taking 4-5 seconds

### ISSUE THREAD

**Issue by r-tock** [IEEEKeralaSection/rescuekerala#671]
You can see it here
https://dashboard.heroku.com/apps/keralarescue/logs

There is no equivalent spike in DB query latencies, slowest query there is still < 100ms

Currently the two conjectures are
- N+1 selects problem happening in Django ORM
- Untuned connection pooling in Django

**Comment by biswaz** [comment]
This might be the file upload (admin feature) using boto, added synchronously

**Comment by biswaz** [comment]
@cibingeorge

**Comment by bobinson** [comment]
@biswaz - anything in the Heroku/  django logs at this point in time ?

**Comment by biswaz** [comment]
Officials are downloading csv's of complete tables! This is the most likely cause

**Comment by r-tock** [comment]
I am closing this, not as urgent now, we have a handle on the behavior.
