### ISSUE TITLE
Create direct donation payment to CMDRF account in home page with paypal integration.

### ISSUE THREAD

**Issue by zubairkumbla** [IEEEKeralaSection/rescuekerala#679]
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

[](https://developer.paypal.com/docs/integration/web/#availability)

**Comment by riginoommen** [comment]
Thanks for filing the Issue 

But seems to be duplicate of #509

**Comment by riginoommen** [comment]
Please forward the communication at #509

**Comment by aravindharinair** [comment]
Solution proposed and awaiting merge at PR #614

**Comment by bobinson** [comment]
#509
