### ISSUE TITLE
Need to add Required filters in camp_requirements

### ISSUE THREAD

**Issue by bensonkb** [IEEEKeralaSection/rescuekerala#688]
Kindly add filters that can be used to search for camp_requirements easily. 

Now case is that need search for each champ what is required for. 

Kindly add priority also. Like urgently needed or need with in few something like that.

**Comment by mnbvcxz010308** [comment]
This is doable. We can make use of plots and diagrams.

**Comment by bensonkb** [comment]
Important Announcements page Launched: - https://keralarescue.in/announcements/
So closing this Issue.
