### ISSUE TITLE
Immediate short-term fix, and related questions

### ISSUE THREAD

**Issue by akhulbe** [IEEEKeralaSection/rescuekerala#69]
I read that the site is currently hosted on Heroku. As we work on optimizing the site, here are some suggestions for immediate fix:

1. Dial up the numbers of hosts/dynos on Heroku
2. Dial up the numbers of processes per dyno, via the WEB_CONCURRENCY param. We need to be careful and look at CPU and memory usage metrics before increasing WEB_CONCURRENCY
https://devcenter.heroku.com/articles/python-concurrency-and-database-connections

Two related questions
1. Has someone created a list of issues the site is facing? What specific problems need to be solved?
2. What traffic and performance metrics are available?

**Comment by old-M0nk** [comment]
+1
Is there a place where we can monitor health of servers and errors?
Have you set up New Relic on the servers? We can use that for the same. I can provide a few licences of New Relic.

**Comment by vigneshhari** [comment]
We are currently hosted in the free Heroku Tier so we have very limited resources and customisability, we will migrate from Heroku to the state data center soon

**Comment by akhulbe** [comment]
@vigneshhari instead of migrating to another data center, why are we not upgrading to a higher Tier in Heroku? That will be faster than migrating.

**Comment by naveenpf** [comment]
Closing now.
