### ISSUE TITLE
HTTPS redirection for volunteers.keralarescue.in

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#690]
### Subject of the issue
http://volunteers.keralarescue.in should redirect to https://volunteers.keralarescue.in

### Your environment
everywhere.

**Comment by anshprat** [comment]
wip

**Comment by anshprat** [comment]
curl -I volunteers.keralarescue.in
HTTP/1.1 301 Moved Permanently
Content-Length: 191
Content-Type: text/html
Date: Sun, 19 Aug 2018 12:47:36 GMT
Location: https://volunteers.keralarescue.in/
Server: openresty/1.11.2.5
Connection: keep-alive

**Comment by bobinson** [comment]
verified and closing.  @anshprat 

CC: @cibingeorge
