### ISSUE TITLE
Enhancement: Implement breadcrumbs

### ISSUE THREAD

**Issue by arjun-pp** [IEEEKeralaSection/rescuekerala#693]
The site has grown and I think we should add breadcrumbs to the site for faster navigation.

**Comment by arpit7714** [comment]
how i can help ?

**Comment by amiteshP** [comment]
I can help too. How to start?

**Comment by cosmicAsymmetry** [comment]
Please add label.

**Comment by yeaske** [comment]
@amiteshP 

> I can help too. How to start?

https://getbootstrap.com/docs/4.0/components/breadcrumb/ is the easiest way do static. I guess it can be done as part of django template/views too.

**Comment by amiteshP** [comment]
@yeaske  thanks! I will start on it.

**Comment by remedcu** [comment]
This can be closed @syam3526 @biswaz @vigneshhari
