### ISSUE TITLE
change in settings.py file 

### ISSUE THREAD

**Issue by AkshJain99** [IEEEKeralaSection/rescuekerala#709]
changes need to be done in settings.py
Add ALLOWED HOST [127.0.0.1]
### 
 python 3.5
* mozilla firefox
* OS linux

Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by vigneshhari** [comment]
We already have added localhost in the environment file provided in the repo.

**Comment by AkshJain99** [comment]
But when we create localhost it doesn't create as it has two lines changes
In allowed host list
