### ISSUE TITLE
not  able to create new request - phone number entry issue 

### ISSUE THREAD

**Issue by msrajesh** [IEEEKeralaSection/rescuekerala#713]
### Subject of the issue
Describe your issue here.

### Your environment
Production site ,  used chrome 

### Steps to reproduce
create a new req 

This is hampering the triage for the rescue reqs

**Comment by satheesht0** [comment]
@msrajesh can you please add more details on the issue? (There are some fixes with phone number entry  already in progress such as #654.)

**Comment by msrajesh** [comment]
@satheesht0 ,  got the issue in production while trying to add following 

District : Alappuzha
Area : Near Edathua Brethren Church, Alappuzha (Edathua-Parathoide-Thiruvalla road)
Name of the person : Soman
Phone number : 9526698070

Location  - https://goo.gl/maps/9A9NnVwBdJQ2

**Comment by salmanulfarzy** [comment]
Tested on production and can confirm.

![image](https://user-images.githubusercontent.com/10276208/44311487-18585000-a406-11e8-99c1-6f976bbf0c43.png)

**Comment by satheesht0** [comment]
Thanks @msrajesh  and @salmanulfarzy . Checking if its working after the fix for #654

**Comment by salmanulfarzy** [comment]
Tested #657 and its working.

**Comment by satheesht0** [comment]
Yes, fix for #654 fixes this issue as well.

**Comment by salmanulfarzy** [comment]
@biswaz @ashwinrajeev @vigneshhari

**Comment by msrajesh** [comment]
Could some one post a msg to -  https://chat.whatsapp.com/9Tz2hteY0og1H4fgmC9vmW    ,   Once its working .    Triaging of the cases to close once req is fullfilled  & priority  marking  of req is happening  there

**Comment by salmanulfarzy** [comment]
Pinged @bobinson and this will be resolved asap.

**Comment by shajith** [comment]
eventually fixed via https://github.com/IEEEKeralaSection/rescuekerala/pull/724 merged and deployed now
