### ISSUE TITLE
/map-view icons are same

### ISSUE THREAD

**Issue by cyriac** [IEEEKeralaSection/rescuekerala#715]
### Subject of the issue
/map-view icons are the same and can be confusing.

### Your environment
* Python 3.6.5
* Chrome
* Mac OS High Sierra

### Steps to reproduce
Open /map-view

### Expected behaviour
Different icons that make sense to the title. Flooded streets can use `road` icon.

### Actual behaviour
Both ```Relief Resouce``` and ```Flooded Streets``` show the same icon.

**Comment by cosmicAsymmetry** [comment]
Once reviewed and appropriate tags added may I claim this?

**Comment by AkshJain99** [comment]
want to work on this issue please put a tag there
