### ISSUE TITLE
Flood reporting map

### ISSUE THREAD

**Issue by naveenfrancis** [IEEEKeralaSection/rescuekerala#72]
Add flood reporting tool. @geohacker 
http://osm-in.github.io/flood-map/

**Comment by jeslyvarghese** [comment]
Can waze or something similar be used to help rescue workers reach locations required?

**Comment by vigneshhari** [comment]
We have a team building a custom flood map right now

**Comment by geohacker** [comment]
Great, let us know if anyone can help. Also tagging the previous flood map team @planemad @batpad @arunasank @rub21

**Comment by aswinmohanme** [comment]
Here's the repo link https://github.com/aswinmohanme/kerala-flood-map

**Comment by manu-codes** [comment]
@aswinmohanme I can work with it ( https://github.com/aswinmohanme/kerala-flood-map) since react if required

**Comment by naveenpf** [comment]
Revathi Kannan is working on it

**Comment by biswaz** [comment]
Please note that @aswinmohanme implemented a map for locating rescue requestee.
Flood map maps the flooded roads and paths right?

**Comment by AbhijithKonnayil** [comment]
will it be helpful, if the one who is requesting the help have an option to upload an image of the landmark near to the building they are trapped? So that the rescue team/volunteers can spot the building more easily

**Comment by jinadcruz** [comment]
There are some previously used disaster management technology options that maybe useful https://sahanafoundation.org/sambro/
https://sahanafoundation.org/pictographs/

**Comment by rojinphilip** [comment]
Crowed sourced flood map: https://www.microid.in/keralaflood/

**Comment by aashiks** [comment]
The guy who raised the request is the author of that. @arunasank was helping with it 
@geohacker  Can you coordinate this in the morning ?

**Comment by pranavashok** [comment]
This issue can be closed now.

**Comment by vrthra** [comment]
Closing this since https://keralarescue.in/map/ is available.
