### ISSUE TITLE
[New feature] Have crowd source collection centres. 

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#723]
### Subject of the issue
Have crowd source collection centres. 

### Expected behaviour
1. Have crowdsourced collection centres in this page 
https://keralarescue.in/relief_camps/
2. One form to Register with two tabs inside kerala and outside kerala 
       Name of collection centre.
       Address 
       Integrate geolocation from mapview.(if possible pop-up google map to select the location)
      Contact : mobile multiple no.
        Type of materials collecting. 
       In kerala, collect district ,lsgtype, lsg, ward  in dropdown option (get data from http://lsgelection.kerala.gov.in/public/search/voterlist  G,M,C have moved out for lsg type in local body)
     outside kerala have in all city lists.

3. have page to display collection centers
    two tabs.
    inside kerala (do not have ward, ward is collected for govt use)
    outside kerala 
   Searchable table
  Have Download CSV in right top corner
   With pagination

4. desirable to have map under maps section

**Comment by naveenpf** [comment]
From backend we should have option to mark as verified/unverified and open and closed

**Comment by biswaz** [comment]
Not required anymore
