### ISSUE TITLE
Improve phone number validation defect fix/patch #724 

### ISSUE THREAD

**Issue by securitydaemon** [IEEEKeralaSection/rescuekerala#729]
@shajith 
@Kavit900

Currently in the fixed version (patch #724) the regex is:
`((\+91|91|0)[\- ]{0,1})?[456789]\d{9}`

Here is a couple of suggestions:

1. The following should also do to cover case "0091"
`((\|+91|0091|91|0)[\- ]{0,1})?[456789]\d{9}`

2. We need to also filter out premium rate numbers, not sure what those are in India. Any thoughts?
For example, the following passes, but they shouldn't?
9990096699
9891892181
08007356836

**Comment by sourabh1024** [comment]
Try this 
`^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789](\d{8,9})$`

**Comment by sourabh1024** [comment]
@securitydaemon any reason you want to filter them out ?

**Comment by naveenpf** [comment]
Not required

**Comment by securitydaemon** [comment]
@sourabh1024 without such filtering volunteers or authorities may end up dialling premium rate number if they are accepted in request.
