### ISSUE TITLE
Feature - Add section for Animal Rescue in Kerala Floods

### ISSUE THREAD

**Issue by npari** [IEEEKeralaSection/rescuekerala#732]
### Subject of the Feature

1. There are many keralites who have left behind their precious pets and need a way to ask for help to rescue their pets.
2. There are animal rescue groups actively working to rescue them. 
3. There is a need for people to report these pets and their location so that animal rescue teams can go rescue them. 

### Expected behavior
We need an icon in the homepage that would on clicking lead to a page for animal rescue in Kerala:
1. Report a pet that needs to be rescued and create a Case 
2. Share animal rescue helpline

**Comment by npari** [comment]
Organizations Supporting animal rescue: 
**Humane Society International - India** 
- [Facebook](https://www.facebook.com/IndiaHSI/) 
- Helpline: _**+91 89433 22808**_

**Comment by gitLee47** [comment]
I can start and add the card linking to the FB page and also the helpline number in the card

**Comment by npari** [comment]
Thanks @gitLee47! I will get more information and add to it.
