### ISSUE TITLE
[Feature Request] - SMS Integration to gather consent from volunteers

### ISSUE THREAD

**Issue by akshaim** [IEEEKeralaSection/rescuekerala#767]
### Subject of the issue
SMS to be sent to all volunteers. SMS contents
1. Acknowledge the help with volunteer name.
2. Unique Shortened URL to seek an opinion from volunteer to find his current status.

URL should be unique and should direct to a poll page to indicate the status of the volunteer. The status may be tagged as Active /Inactive. The poll may work in such a way that once a volunteer clicks the link, he is registered as an active volunteer in the system.

### Your environment
REST API offered by KSITM for SMS Gateway.

**Comment by syam3526** [comment]
@IEEEKeralaSection/moderators

**Comment by bobinson** [comment]
quick plan:

1. setup sub domain r.keralarescue.in to act as the unique shortened URL
2. Python + Redis for data storage.

need to figure out how to do the web server.
