### ISSUE TITLE
Ability to Mark Requests as Flagged/ Resolved

### ISSUE THREAD

**Issue by vvazhayil** [IEEEKeralaSection/rescuekerala#769]
### Subject of the issue
Need a screen that will interact with a new table where issues can be tagged as flagged/ resolved
Original table will not be updated 
Volunteers can enter the data on a screen which is only available for logged in volunteers. 
- Status (Flagged/ Resolved/ Duplicate etc.)
- Reason (Text)
- Updated by 
- Auto capture original ticket number, logged in user and timestamp in the table 

For each original ticket, there can be multiple entries in the second table. Multiple people may/can update an original ticket. 

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by cibingeorge** [comment]
Maybe we dont care about logged in user..bt text field abt who is updating..hopefully wont be abused. that way we open this up the the world..easier for all the teams who hve the data to update

**Comment by cibingeorge** [comment]
add a reference/link to a related/subsequent request made?

**Comment by vvazhayil** [comment]
@cibingeorge - Ticket number for subsequent ticket? Original ticket should be referenced. Would someone know the future ticket when updating this status?

**Comment by cibingeorge** [comment]
Maybe i was too crazy..ignore that related thing suggestion

**Comment by theryecatcher** [comment]
So would we be designing a new table for this referencing the original requests table?

**Comment by vvazhayil** [comment]
Yes, that;'s the plan.

**Comment by lunaroyster** [comment]
Would this reflect in the data from the /data endpoint?

**Comment by biswaz** [comment]
That or ushahidi, that is the qn now

**Comment by theryecatcher** [comment]
The ushahidi one seems to be taking a lot of time. I believe we could work on a quick fix on a different table as suggested so that the work can move on. The solution suggested by @vvazhayil could be done in a short time. What do you guys suggest?

**Comment by shajith** [comment]
@theryecatcher or anyone else available with Django dev capability, pls ping me on slack. same handle as here.

**Comment by vvazhayil** [comment]
Can someone with the real on the ground experience state what resolutions should each ticket get?
- Resolved
- Pending
- Duplicate
- Flagged 
? I don't know who can tell us that clearly.
