### ISSUE TITLE
Link not clickable

### ISSUE THREAD

**Issue by haseebpvt** [IEEEKeralaSection/rescuekerala#774]
### Unable to click link
The links in https://keralarescue.in/district_needs are not not clickable

### Steps to reproduce
1. Go to https://keralarescue.in/district_needs
2. Notice there are three columns namely 'District', 'Items required' and 'Contacts & Collection points'
3. In the column 'Contacts & Collection points' google map address links are included
4. Hover the mouse over those links

### Expected behaviour
The links should be highlighted automatically

### Actual behaviour
It does not highlate. It is plain text.

**Comment by angrysumit94** [comment]
Need to write @property for map_link field containing "<a href=" + self.map_link + "</a>". Anyone ready to do it now ?

**Comment by haseebpvt** [comment]
@syam3526 Added more details on how to reproduce the issue

**Comment by SajinSabu** [comment]
Somebody working on this?

**Comment by ladvine** [comment]
Yes, there are hyperlink available among the content under section "Contacts & Collection points" in the page [district needs](https://keralarescue.in/district_needs/).
All such markups has to be automatically detected and converted for the ease of user.
