### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by jsrunner** [IEEEKeralaSection/rescuekerala#78]
Our team has a 3000 dollar credit in our google cloud, so we are ready to help with hosting, effective caching using cloud flare, Nginx hosting and scaling of the application if needed.

**Comment by hemanth7787** [comment]
I am guessing it will be difficult for them to migrate under this situation, especially when people in distress are actively using it.

**Comment by naveenpf** [comment]
Thank you. Closing now.
