### ISSUE TITLE
Register missing cases

### ISSUE THREAD

**Issue by ladvine** [IEEEKeralaSection/rescuekerala#783]
### Description
Provision to register man missing cases and prepare xls sheet etc. Better if there is a provision to pass information to Kerala police.

Please note that this is not a person finder.

**Comment by vchacko** [comment]
I can work on this with following information of missing person and reporter

1. Name
2. Approximate Age
3. Gender
4. Missing from location
5. Missing from date
6. Description of missing person
7. Reporter Name
8. Reporter Number
9. Police station
10. Assigned To Volunteer - Admin can assign a volunteer and ask him to verify if missing case is true and hecan report bact if found
11. is active - By default, all records be activa and when missing person is found, set this as false(by admins)
12. Reported time
13. Found Date/Time
14. Current Location of missing person
15. Current contact number

# 13 to # 15 should be filled in when missing person is found and # 10 to # 15 need not be displayed on website form for reporter. They need to be in search section

**Comment by ntsreejith** [comment]
@vchacko  Person's photo,  Reporting person's relationship

**Comment by vchacko** [comment]
@ntsreejith Will add them too.

I am working on this issue

**Comment by vchacko** [comment]
Adding field District as # 4.a

**Comment by naveenpf** [comment]
16, photo of missing person.

**Comment by vchacko** [comment]
@naveenpf Sure

**Comment by naveenpf** [comment]
Already added
