### ISSUE TITLE
Vertical Scrollbar in District needs and Collection Centers

### ISSUE THREAD

**Issue by rakemen** [IEEEKeralaSection/rescuekerala#789]
A vertical scrollbar appears in the District needs section

Chrome Browser on Windows

![image](https://user-images.githubusercontent.com/6099915/44368089-b5b39280-a49f-11e8-9532-972b08e6842b.png)

**Comment by thelostone-mc** [comment]
@abhisrphoenix I went another route and reduced the font-size just a bit without compromising on the the emphasis on the heading.
Disable vertical scroll -> might get content hidden which IMHO was not ideal.
Mind taking a look at it? 

cc @rakemen

**Comment by abhisrphoenix** [comment]
@thelostone-mc Yeah that too solves the problem. Am fine with that.

**Comment by TribeAsteraea** [comment]
The same problem now occurs in Private Relief camps & collection center as well 
![image](https://user-images.githubusercontent.com/42574806/44523056-d6b2f800-a6d8-11e8-8834-4eba721c8522.png)
