### ISSUE TITLE
Data consolidation and sanitization from different data entry points

### ISSUE THREAD

**Issue by deepusnath** [IEEEKeralaSection/rescuekerala#794]
As of now, different people at different locations are trying to collect data of relief camps in multiple means. Many are using google spreadsheets. We need to bring all such data to a central point to consolidate, remove duplicates and sanitize so that it will be complete. Can we have a section in keralarescue.in for data synchronization where anybody who has data can share their link to it. By this way we can consolidate it and provide an API for everyone to use it from a central point. 

We have to consolidate and maintain the following list basic list of data of each rescue camp. It will be the root point to start coordinating activities across the state using the call center volunteers.

District | Camp Name | Address | Region | Contact Numbers | Men | Women | Kids | Infants | Total People | Requirements | Notes

Following is a spreadsheet with updated data. Those who wish to contribue please comment for edit access. 
https://docs.google.com/spreadsheets/d/1uVdZwQ1S8JWh26EGBe8-A8aktmDPBT_pCalfAi7rWLI

**Comment by vjayakumar** [comment]
Can a column be added for people with disability?
