### ISSUE TITLE
Add Privacy Text to Disclaimer Page

### ISSUE THREAD

**Issue by vvazhayil** [IEEEKeralaSection/rescuekerala#795]
Add the following text to the Disclaimer Page. Change the Disclaimer Link to "Disclaimer, Terms and Privacy"

_**By providing your personal information, you consent to making such information accessible to persons who visit this website. You further acknowledge and agree that in order to serve the specific purposes for which personal information is volunteered by you, such information needs to be accessible to the public at large and therefore, by volunteering your information on this website, you consent to making such information public. By providing your phone number and email address, you further consent to being contacted by anyone who accesses such information through this website. The creators of this website or the government of Kerala shall not be liable for any unauthorized use, misuse or sharing of such information.**_

On the volunteer signup screen, add a checkbox with the text that says "I agree to terms & conditions of keralarescue.in " - Add a link on "terms & conditions" to the disclaimer page.

**Comment by abhisrphoenix** [comment]
working on it.
which is the html file for volunteer signup screen,

**Comment by iKshitiz** [comment]
This issue is closed.

**Comment by binobose** [comment]
Unable to push updates

**Comment by vvazhayil** [comment]
I see the updates now
