### ISSUE TITLE
urgent requirement. for having options for private relief camps and collection centres

### ISSUE THREAD

**Issue by syam3526** [IEEEKeralaSection/rescuekerala#802]
private relief camps and collection centres
  

1.  register private relief camps
2.     view private relief camps
3.    register private collection camps
4.    view private collection centres

3 and 4 will be done by @naveenpf 

1 and 2 to be done similar to government relief camps

**Comment by ragsagar** [comment]
Task 1 and 3 looks same

**Comment by rajeevrmenon97** [comment]
I think 3 is register private collection centres?

**Comment by ragsagar** [comment]
Are there difference in fields? If it is the same I think it is enough to add new field `type`

**Comment by syam3526** [comment]
@naveenpf please comment
yes without making conflicts in the model.

**Comment by ja8zyjits** [comment]
I can write tests, once the functionality is ready.

**Comment by ragsagar** [comment]
How do you want to see this? With the same relief camp listing we just add column to show if it is pblic or private? Or a separate page itself?

**Comment by naveenpf** [comment]
@vignesh is working on 1 and 2

**Comment by naveenpf** [comment]
Done

**Comment by ja8zyjits** [comment]
@naveenpf  can you tag the PR?
