### ISSUE TITLE
Database of people in relief camps

### ISSUE THREAD

**Issue by sreenadh** [IEEEKeralaSection/rescuekerala#81]
We also need a database of people/family name in relief camps to let people staying away from family know if their family/relatives are safe or not.

Here is a case
http://www.marunadanmalayali.com/news/special-report/dr-neethu-seeks-help-118475

**Comment by JijinJayakumar** [comment]
ya, but the campu is already crouded and every on is busy with activites, how we can get the data ?

**Comment by sreenadh** [comment]
@JijinJayakumar provide an option. "Mark as safe"
enter name/phone/family name

Interface 2: search by phone/email/name

**Comment by JijinJayakumar** [comment]
@sreenadh i think  that's not possible, someone from camp told that they don't have charge in mobile, generators are not functional, 
else we need a volunteer from campus to collect and upload the data

**Comment by sreenadh** [comment]
@JijinJayakumar  yup

**Comment by bobinson** [comment]
good intentions - but at the same time keep in mind about elements which will misuse the information. So even if its getting implemented it should not be a list-all feature. May querying for info should be done after an OTP verification or so.

**Comment by naveenpf** [comment]
Same as #120
