### ISSUE TITLE
NGO cant be searched by district

### ISSUE THREAD

**Issue by vchacko** [IEEEKeralaSection/rescuekerala#812]
### NGO cant be searched by district
The model NGO has 'District' in the model, but the form https://keralarescue.in/NGO/ doesn't have field to enter district. The view https://keralarescue.in/ngoview/ has search by district, but since we can't enter district, we can't search by district. 

### Steps to reproduce
Go to  https://keralarescue.in/ngoview/ and search by district, there is no data
Go to https://keralarescue.in/NGO/, there is no field to enter district

### Expected behaviour
https://keralarescue.in/NGO/ needs a dropdown to select district

**Comment by vchacko** [comment]
Duplicate of https://github.com/IEEEKeralaSection/rescuekerala/issues/642

**Comment by bobinson** [comment]
thus closing.
