### ISSUE TITLE
[https://donation.cmdrf.kerala.gov.in/ task] Paypal Global - payment gateway integration - Help requested from CDIT

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#814]
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

**Comment by naveenpf** [comment]
Help request from donation website. Nothing on kerala rescue site

**Comment by cgninan** [comment]
ok looks like this already been worked upon by bobinson. I didn't notice this was assigned.

**Comment by bobinson** [comment]
This was a duplicate of #509 and we have not heard anything from CDIT or anyone regarding the paypal global integration.

- the payment page also had a low uptime yesterday and we are helpless regarding the same too though we have companies and technical volunteers ready to willing.
