### ISSUE TITLE
Automatic deployment using now.sh

### ISSUE THREAD

**Issue by shidhincr** [IEEEKeralaSection/rescuekerala#815]
### Automatic deployment using now.sh for pull requests
How about adding automatic deployments to now.sh -- so we can easily test the new pull requests.

Integration details given here:

https://zeit.co/github

**Comment by amiteshP** [comment]
Automatic Tests Integration pipeline will be more helpful, one which automatically tests the PR once it is pushed against our testcases(similar to travis), I think we will need manual deployments in the end.

**Comment by ja8zyjits** [comment]
manual with heroku.

**Comment by shidhincr** [comment]
My point is, we can create a staging kind of environment in **heroku** or **now.sh** just for testing the pull requests. The **now.sh** creates a unique url for each deployment -- so it will be easier to test different branches/PRs

Let the live deployment to be whichever it is currently using.

**Comment by k0Lm4ch** [comment]
Already working on setting up pipeline in heroku for keralarescue-test app.Once we have beta tested that, can implement the same for prod
