### ISSUE TITLE
Change location textbox to Google maps places searchbox. GPS co-ordinates

### ISSUE THREAD

**Issue by sreenadh** [IEEEKeralaSection/rescuekerala#83]
Change location textbox to Google maps places searchbox.  We can find GPS coordinates from that. https://developers.google.com/maps/documentation/javascript/examples/places-searchbox

#31  #29 #47

**Comment by naveenfrancis** [comment]
+ #80

**Comment by prajinprakash4u** [comment]
Sample template from google.
[aa.zip](https://github.com/IEEEKeralaSection/rescuekerala/files/2293310/aa.zip)

**Comment by naveenpf** [comment]
Already implemented

**Comment by sreenadh** [comment]
@naveenpf Not implemented. pls check again.

**Comment by biswaz** [comment]
We have a text based placepicker now. @sreenadh 's suggestion is better. #695 is for this
