### ISSUE TITLE
Confirmation link never expiring

### ISSUE THREAD

**Issue by joeldeleep** [IEEEKeralaSection/rescuekerala#838]
### Confirmation link never  @biswaz 
The confirmation link that is send to mobile for confirming the participation of volunteer never expire , even after cancelling 
### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
The csrf token should expire after performing the confirmation

### Actual behaviour
Csrf token never expiring

**Comment by bobinson** [comment]
We will mostly be going to OTP based verification - fyi

**Comment by biswaz** [comment]
We're using a time stamp based verification. It was a one time hack. Any (security) issues in this?

**Comment by bobinson** [comment]
I think we can fix any issues expire the token etc - this one time hack can be used in scenarios like ours when the OTP/SMS will not be available.

**Comment by joeldeleep** [comment]
it would be better to update with csrf token expiration , if you are planning for a time based verification , consider to make the link after the first use , the main issue that arise during time based verification is  if 24 hours is the provided limit , token can be used n number of times during the limit .
