### ISSUE TITLE
Change phone number field type to number

### ISSUE THREAD

**Issue by sreenadh** [IEEEKeralaSection/rescuekerala#84]
Change phone number field type to "number" to open numkeypad in Mobile browsers.

**Comment by bobinson** [comment]
> Change phone number field type to "number" to open numkeypad in Mobile browsers.

With water on the touch screen, hard to say whether its a good idea. This is not a regular scenario where we are talking about Usability. Also this will cause few additional CPU cycles from a perhaps about to die mobile phone. So, I would suggest to keep the options given to the end users.

So let people enter details without doing additional checks. Let the users enter.

Also, I would suggest to use geo location being captured with every request using

- GSM geo location if possible
- GPS
- Get the finest information as possible.

PS: I may not be able to respond as I am myself in an area with little bit of water.

**Comment by sidharthv96** [comment]
Phone number field to number will automatically pop up the numeric keypad. Which facilitates entry of numbers easily. We can let them enter all the other details freely, but don't you think mobile should be numbers only and validated.

**Comment by naveenpf** [comment]
Needs merge

**Comment by naveenpf** [comment]
Fixed
