### ISSUE TITLE
Non standard design in one of the boxes on homepage.

### ISSUE THREAD

**Issue by dsamanmishra** [IEEEKeralaSection/rescuekerala#840]
### Subject of the issue
The private relief center and collection center box is not following the standard design of other boxes i.e. icon, english word, then horizontal line and then translation.

### Expected behaviour
Private relief center and collection center box should follow the standard design like other boxes.

### Actual behaviour
It follows design where horizontal line comes after icon itself.

**Comment by dsamanmishra** [comment]
Am working on this.

**Comment by TribeAsteraea** [comment]
Also the malayalam translation on this box is missing.

**Comment by dsamanmishra** [comment]
Yes, have added that as well in my PR.
