### ISSUE TITLE
Malayalam Text missing in the Add Private camp 

### ISSUE THREAD

**Issue by TribeAsteraea** [IEEEKeralaSection/rescuekerala#843]
The malayalam text on the tabs on https://keralarescue.in/pcampadd are missing 
![image](https://user-images.githubusercontent.com/42574806/44416368-fcbe8800-a572-11e8-9927-eec542824c3a.png)

**Comment by arpit7714** [comment]
its missing on heading . can i work?

**Comment by TribeAsteraea** [comment]
arpit7714 - pls do

**Comment by arpit7714** [comment]
Dome please check @TribeAsteraea 
https://github.com/IEEEKeralaSection/rescuekerala/pull/864

**Comment by Gotham13121997** [comment]
@arpit7714 also tag this issue #843 in your pull request by commenting
