### ISSUE TITLE
Social Computing Lab from IIT Ropar

### ISSUE THREAD

**Issue by sudarshansudarshan** [IEEEKeralaSection/rescuekerala#844]
Dear all,

I am Dr. Sudarshan, a professor from IIT Ropar running a social computing lab at the CSE dept of our IIT. We are desined a web portal to collect all information on who is ready to help and who are the seekers of help and how to assign a virtual volunteer per camp. We have collected 500+ volunteers who are ready to help by taking part in the crowdsourced portal. Please let us know if we can team up with you people to double up our efficiency. Please pass on the number of the person in charge with whom I can talk. 

Sudarshan Iyengar
www.sudarshaniyengar.com
9023978851

**Comment by muraleedharanm** [comment]
Thanks, please call me ( Murali ) at 8086335855 / Santhosh at 8592994200

**Comment by bobinson** [comment]
Thank you for reaching out @sudarshansudarshan we need all the support help to 

- identify the short term action items
- 1 month to 3 month action items
- long term

in the Relief and Rehabilitation of the state and its people.

I believe, the volunteer co-ordination can help various Government departments to co-ordinate the volunteers on ground and from call centers.  Linking of the call centers, supply demand, volunteers + govt officials on various tasks etc needs clear direction and execution. I will introduce you to the volunteers working on many of the aspects, we need to define a clear path that we can follow to ensure long term and permanent solutions to the aftermath of the disaster with emphasis to healthcare.
