### ISSUE TITLE
Frontend changes for faster page loading

### ISSUE THREAD

**Issue by sreenadh** [IEEEKeralaSection/rescuekerala#85]
1. Avoid all other CSS files except bootstrap
2. Use standard browser font. Remove 'raleway'
3. Put request for help in home page and give other links on right side. two column layout
4. Load logos on top asynchronously.
5. If possible remove bootstrap and use table layout for faster loading.

#83 #84

**Comment by visakhsuku** [comment]
i could help with 2nd one

**Comment by sreenadh** [comment]
Remove the district column in 'view requests'. not necessary @biswaz

**Comment by shabinGravitum** [comment]
5. If possible remove bootstrap and use table layout for faster loading.

The design is responsive and looks well on mobile, do you really want to do this?

**Comment by sreenadh** [comment]
@shabinGravitum to reduce page load time. not for responsiveness.

**Comment by bodhish** [comment]
Use tailwind, only styles which are used will be loaded to production

**Comment by sreenadh** [comment]
Use single external CSS file or use inline style.

**Comment by prajinprakash4u** [comment]
reduce the use of images and styles. move images and assets to s3bucket or cdn.

**Comment by ivalsaraj** [comment]
@shabinGravitum Table is messed up. See the mobile view.
![capture1](https://user-images.githubusercontent.com/42429710/44203707-91894600-a16d-11e8-8b6c-1964fa6bb543.PNG)

**Comment by visakhsuku** [comment]
#105 for 2nd one

**Comment by prajinprakash4u** [comment]
Please use it https://github.com/django-compressor/django-compressor

**Comment by naveenpf** [comment]
Many issues reported in one ticket. Please log separate one

**Comment by sengar23** [comment]
Couple of fixes I used and managed to bring down the website size from 172 kb to 105 kb, which will definitely help in reducing the load time of the site on weaker connections.
The fixes are listed below:
1. Don't use an external font (very important). Use default font provided by bootstrap.css. Removed the loading of font.css file in base.html.
2. Did the optimization the images, retaining the original features but reduced the file size to 60% of total image data downloaded on loading of the website. Below are the links of the optimized image:
[https://ranjeetsengar.com/keralarescue/kerala-government.png](url)
[https://ranjeetsengar.com/keralarescue/it-mission.png](url)
[https://ranjeetsengar.com/keralarescue/ieeelogo.png](url)
[https://ranjeetsengar.com/keralarescue/emblem.png](url)

Note: I'm sharing the link of the screenshots of the fixes done
[https://ranjeetsengar.com/keralarescue/keralarescue1.png](url)
[https://ranjeetsengar.com/keralarescue/keralarescue2.png](url)

Hope this helps.

**Comment by asimqt** [comment]
Anybody working on rewriting CSS? (Remove bootstrap)

**Comment by sengar23** [comment]
If we remove bootstrap then the 'Glyphicons Halflings' will also be gone and there won't be any icons. Is that okay? 
I suggest to let go of the icons, it will reduce 18kb of total website size.

**Comment by sengar23** [comment]
We are loading 'Montserrat' font in templates/base.html. Are we loading that external font for any reason? Because I can't find it being used anywhere. Please let me know. Thank you.

**Comment by prajinprakash4u** [comment]
I think it is better to remove all external fonts. also remove the references.

**Comment by asimqt** [comment]
@sengar23 We removed that font in some PR. NOt sure whether it's merged or not.

**Comment by sreenadh** [comment]
Good work guys 👍
