### ISSUE TITLE
Add link to https://www.afterflood.in/

### ISSUE THREAD

**Issue by WarFox** [IEEEKeralaSection/rescuekerala#851]
After flood.in is a website that provides information about every Do's and don'ts, waste management, personal hygiene and every other aspect to keep in mind while moving back to home after flood.
It'll be of great use to people.

https://www.afterflood.in/

**Comment by ja8zyjits** [comment]
I believe a new card like the 10 others would be good.

**Comment by WarFox** [comment]
How can we get govt approval?

**Comment by biswaz** [comment]
Approved., By akshai. Accepting PRs.
May be a button on the main page like the donation button? But the existing buttons should have more importance

**Comment by biswaz** [comment]
Added

**Comment by tomahawk-pilot** [comment]
@biswaz 
@vigneshhari

**Comment by bodhish** [comment]
@R-Aravind what happened to PR?

**Comment by R-Aravind** [comment]
@bodhish I talked with @vigneshhari and he pointed out that they didnt have govt. approval for it.
