### ISSUE TITLE
google analytics tracking

### ISSUE THREAD

**Issue by syam3526** [IEEEKeralaSection/rescuekerala#852]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-124193959-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-124193959-1');
</script>

**Comment by biswaz** [comment]
We have all the info we want in cloudflare. Even more now with the business paln

**Comment by syam3526** [comment]
#854

**Comment by vigneshhari** [comment]
Analytics might slow down our website and we already have cloudfare based analytics

**Comment by syam3526** [comment]
closing this considering we don't want the site to slow down. .

**Comment by bobinson** [comment]
not needed more analytics as we have cloudflare. If needed IMHO we can go with Opensource Piwik to avoid leaking out any personal data. Closing considering - performance impact and privacy impact and because of low priority.
