### ISSUE TITLE
Need Help in Django Rest API

### ISSUE THREAD

**Issue by vigneshhari** [IEEEKeralaSection/rescuekerala#86]
We need to setup Django REST API in the branch "app" in our repo,
We need to disable CORS and CSRF in order for the API to work,
The base model is written, please test and verify the code before submitting a pull request

**Comment by sreeramvenkitesh** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/pull/73

DRF is already set up . now what is it that you need to do here ? could you elaborate on your requirements a bit  ?

**Comment by biswaz** [comment]
Creating an app in parallel just for the rescue requests

**Comment by prajinprakash4u** [comment]
from django.views.decorators.csrf import csrf_exempt

@method_decorator(csrf_exempt)

**Comment by sreecodeslayer** [comment]
@sreenadh Related to this #22

**Comment by sidharthv96** [comment]
Add "*" to allowed_hosts in settings.py, that should help with CORS.

**Comment by kurianbenoy** [comment]
@prajinprakash4u  your proposed solution won't work for a class based views. 
https://github.com/IEEEKeralaSection/rescuekerala/blob/app/restendpoint/views.py
https://github.com/IEEEKeralaSection/rescuekerala/blob/app/restendpoint/serializers.py
Check out the following files for having a better idea of the issue

**Comment by biswaz** [comment]
@all Take a lot at the app branch

**Comment by sidharthv96** [comment]
Instead of an android app, please make a PWA. It can be loaded in any phone, and also can be updated easily and shared too.

**Comment by sidharthv96** [comment]
https://github.com/ottoyiu/django-cors-headers/

CORS fix

**Comment by prajinprakash4u** [comment]
this is some portion of my code ,Can i get the api codes?.

@method_decorator(csrf_exempt, name='dispatch')
class SkinnerGit(LoginRequiredMixin,View):
    login_url = '/api/auth/login'
    redirect_field_name = 'redirect_to'
    def post(self, request, *args, **kwargs):
        post_data = request.body.decode()
        if(post_data):
            post_data = jsonpickle.decode(post_data)
        if 'commit_message' in post_data:
            commit_message = post_data["commit_message"]+" :- Source Updated from IP :"+get_client_ip(request)
        else:
            commit_message = "Source Updated from IP :"+get_client_ip(request)
        response = subprocess.getoutput('cd static/skinner && git add -A && git commit -m "'+commit_message+'"')
        print(response)
        if "changed" in response:
            status = 200
        else:
            status = 400
        response = re.sub("[^A-Za-z0-9/.%, :\-+]+", r' ', response)
        json_string='{"response" : "'+response+'"}'
        json_data =jsonpickle.decode(json_string)
        return JsonResponse(json_data, safe=False,status=status)
    def put(self, request, *args, **kwargs):
        response = subprocess.getoutput('cd static/skinner && git push')
        print(response)
        if "Everything" not in response:
            status = 200
            response = "Pushed Successfully to the remot branch"
        else:
            status = 400
            response = re.sub("[^A-Za-z0-9/.%, :\-+]+", r' ', response)

        json_string='{"response" : "'+response+'"}'
        json_data =jsonpickle.decode(json_string)
        return JsonResponse(json_data, safe=False,status=status)

**Comment by sreenadh** [comment]
@biswaz  Install an app just for creating a request!! nobody will do it it seems.

**Comment by sidharthv96** [comment]
@prajinprakash4u  Please paste formatted code for easy viewing

**Comment by sidharthv96** [comment]
PWA is the best choice for our situation. You can't even get past google play verification quickly. That will take atleast a few hours. And every subsequent update also will be slow. App is not the optimal solution.

**Comment by biswaz** [comment]
@sreenadh Just merged geo location from web itself

**Comment by biswaz** [comment]
Our only concern was accuracy

**Comment by SpEcHiDe** [comment]
Maybe create a WhatsCRApp or Telegram bot, that will allow the user to share location.

**Comment by sreenadh** [comment]
please see #85 Simple changes. 
@sidharthv96 since the data is online and if there are no external CSS/JS PWA is not required.

**Comment by sidharthv96** [comment]
https://medium.com/@onejohi/introducing-geolocation-in-your-pwas-65713faba51a

**Comment by sidharthv96** [comment]
Can't we add a map with pointer to get the precise location. People will actually mark that, but very few will install an app for this specific purpose. I think the bigger issue is sharing the app. Wonder if anyone here have any workarounds to speed up playstore verification procedure.

**Comment by Gotham13121997** [comment]
I can spin up a telegram bot if rest api is ready

**Comment by prajinprakash4u** [comment]
https://github.com/IEEEKeralaSection/rescuekerala/blob/app/restendpoint/models.py
mobile no is integer field.

**Comment by prajinprakash4u** [comment]
The issue with csrf soleved?. if not take a look at, https://stackoverflow.com/questions/30871033/django-rest-framework-remove-csrf

**Comment by abhijithanilkumar** [comment]
Can someone update what the exact requirement is? Is it just getting the API to work?

**Comment by mjzac** [comment]
CSRF issue can be resolved if the authentication is done using `TokenAuthentication`. DRF already provides mechanism for it. 

https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

**Comment by prajinprakash4u** [comment]
If this issue is resolved please close it
