### ISSUE TITLE
"Join our slack" link has expired.

### ISSUE THREAD

**Issue by ALonelyTower** [IEEEKeralaSection/rescuekerala#862]
### "Join our slack" link has expired
Clicking on the link results in this page:
![slack_unavailable](https://user-images.githubusercontent.com/42524361/44435061-18ba2d80-a563-11e8-8387-096703864f44.PNG)

**Comment by gitLee47** [comment]
Are you talking about the one on the github page

**Comment by abhisrphoenix** [comment]
@gitLee47 
This slack link is in the website Home Page
Our Collaboration Platform (Slack) "Join" - link is not working.

**Comment by syam3526** [comment]
@gitLee47 @abhisrphoenix the link expired.  here is a new link http://bit.ly/Keralarescuechat . i have updated the link in the readme as well.
Closing this since the issue has been fixed
