### ISSUE TITLE
Enhancement: Add Filter Condition to "Open / Close" in Relief Camps

### ISSUE THREAD

**Issue by abhisrphoenix** [IEEEKeralaSection/rescuekerala#865]
### Subject of the issue
Add Relief Camps Status as Filter Condition to Identify - Open or Closed camps 
https://www.keralarescue.in/relief_camps_list

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Go to https://www.keralarescue.in/relief_camps_list
### Expected behavior
Users should be able to filter Open and Closed Relief  Camps

### Actual behaviour
Currently functionality is not available to filter Open/Closed Relief camps.

**Comment by naveenpf** [comment]
It is already there in back emd
