### ISSUE TITLE
Request Update page  displays Metadata as text 

### ISSUE THREAD

**Issue by TribeAsteraea** [IEEEKeralaSection/rescuekerala#883]
### Subject of the issue
The Request Update page displays Text 

Looks like the meta element is displayed as text 

![image](https://user-images.githubusercontent.com/42574806/44469842-a3189500-a628-11e8-899e-9eea75051e85.png)

**Comment by gauthams09** [comment]
please add malayalam text here https://github.com/IEEEKeralaSection/rescuekerala/blob/master/mainapp/templates/mainapp/request_update.html#L86

**Comment by gauthams09** [comment]
you might need to modify here as well https://github.com/IEEEKeralaSection/rescuekerala/blob/master/mainapp/templates/mainapp/request_update_success.html#L7

Please raise a PR

**Comment by TribeAsteraea** [comment]
I can see that it is reflecting in the portal

**Comment by 7vikpeculiar** [comment]
Can I take this up ??

**Comment by TribeAsteraea** [comment]
@7vikpeculiar Issue is closed and the fix is live
