### ISSUE TITLE
[Fix required] View of private collection center.

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#889]
Have two pages for view of private collection center.
Currently inside kerala and outside kerala are on same page. 
We need two pages, one for inside kerala and other one for outside kerala.
https://keralarescue.in/collection_centers/

Change the respective filters accordingly

**Comment by naveenpf** [comment]
Yes

**Comment by namboodiri** [comment]
working on it

**Comment by naveenpf** [comment]
Filters are not updated properly.
Drop down filters required similar to register page for inside kerala

**Comment by dsamanmishra** [comment]
@naveenpf Can you please share the link to register page for inside kerala which you are referring to?

**Comment by naveenpf** [comment]
https://keralarescue.in/collection_center/

**Comment by namboodiri** [comment]
am working on this
