### ISSUE TITLE
[Fix required] Changes required in add private relief camps

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#890]
Following changes are required for below page https://keralarescue.in/pcampadd

Add LSG dropdown in private relief camps. (whatever implemented in private collection centers.)
Remove LSG Type
Remove Center inside kerala? - കേന്ദ്രം കേരളത്തിലാണോ
Remove City - നഗരം
Remove Status from front page needed in backend

**Comment by arpit7714** [comment]
can i work on this?

**Comment by naveenpf** [comment]
Yes

**Comment by arpit7714** [comment]
ok !

**Comment by naveenpf** [comment]
No
