### ISSUE TITLE
[Fix required]View of private relief camps

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#891]
Add ID for each private relief camps. 
Display phone no on private relief camps.

**Comment by kurianbenoy** [comment]
Can I take up this issue?

**Comment by naveenpf** [comment]
Yes

**Comment by naveenpf** [comment]
Total no is showing phone no
Contact is total no

**Comment by kurianbenoy** [comment]
@naveenpf , can you mention which page are you referring to? Can you share the URL?

**Comment by naveenpf** [comment]
https://keralarescue.in/pcamp/?district=&name__icontains=
