### ISSUE TITLE
[Internal] Make person finder visible and change datasource of stats

### ISSUE THREAD

**Issue by biswaz** [IEEEKeralaSection/rescuekerala#895]
1. Add a card pointing to https://keralarescue.in/find_people/ in https://keralarescue.in/relief_camps/

2. The total people on https://keralarescue.in/relief_camps_list and all stats in here are fetched from 
the fields on RescueCamp model
Now that amble camp inamte data is added, the data should be fetched from Person model

Create enough test camps and person to test your fix. 

@vigneshhari is available to guide you

**Comment by naveencode** [comment]
working on this

**Comment by ad6190** [comment]
enabled card for people. opening PR.
