### ISSUE TITLE
[Feature request]  Add Disha Helpline

### ISSUE THREAD

**Issue by thejeshgn** [IEEEKeralaSection/rescuekerala#898]
Its a government project and mental health toll free line 

http://disha1056.com/

**Comment by vjayakumar** [comment]
Yes. Every day brings news of one more death by suicide as a direct consequence of the floods. 
https://bangaloremirror.indiatimes.com/bangalore/others/kerala-floods-deluge-ravaged-state-on-the-verge-of-nervous-breakdown-three-suicides-reported/articleshow/65504951.cms
