### ISSUE TITLE
Collection center in Trivandrum showing up in Outside Kerala

### ISSUE THREAD

**Issue by namboodiri** [IEEEKeralaSection/rescuekerala#903]
### Subject of the issue
The Collection center (Id: 4, Name: Nishagandhi), is showing up in 'Outside Kerala' list.

### Your environment
* version of your python NA
* which browser and its version NA
* OS Type (iOS/Android/Linux/Windows) NA

### Steps to reproduce
Goto link https://keralarescue.in/collection_centers/outside_kerala/ and click Search

### Expected behaviour
Places outside Kerala should only be listed

### Actual behaviour
A place in Trivandrum is being listed

###Other notes
Check if the problem is in the entry in the admin page and correct it if necessary.

<img width="1667" alt="screen shot 2018-08-23 at 5 49 46 pm" src="https://user-images.githubusercontent.com/2396024/44525227-ee50a780-a6fd-11e8-8a4b-04bad6ec3294.png">

**Comment by naveenpf** [comment]
Please check after refreshing your cache

**Comment by namboodiri** [comment]
All good now. 👍
