### ISSUE TITLE
[Feature request] Grievance Posting 

### ISSUE THREAD

**Issue by TribeAsteraea** [IEEEKeralaSection/rescuekerala#905]
### Subject of the issue
There should be a tile in the rescue portal for the people to express the various grievance in the ground situation, or even suggestions for improvement.  

I can see the Google docs here https://docs.google.com/forms/d/e/1FAIpQLSfbh2Zj1z9UGNdZQclSIS6YzBTQtxLIniU7_EFkdg37bdtw-A/viewform

Any attempt to integrate it into the portal?

**Comment by bobinson** [comment]
> Any attempt to integrate it into the portal?

It can be integrated very quickly but there is no official request to the volunteers regarding the same. If there is a request from any government bodies, we can implement and roll out this in 30 minutes.

In general we just need to follow the model of missing persons report. Refer #926 

Please re-open this if any govt department needs this.
