### ISSUE TITLE
Urgent,  Site broken / Taking too long to load

### ISSUE THREAD

**Issue by hemanth7787** [IEEEKeralaSection/rescuekerala#911]
### Subject of the issue
Site is taking too long to load,  shows application error screen

### Your environment
Firefox 61.0.1
Kubuntu 18.04 - 64bit

### Steps to reproduce
Visit  https://keralarescue.in/ 
![screenshot_20180824_003227](https://user-images.githubusercontent.com/2316704/44546363-4eaf0b80-a735-11e8-9fec-2fc824b0b5f4.png)

**Comment by rakemen** [comment]
Can confirm. It's down!

Chrome on Windows 10

![image](https://user-images.githubusercontent.com/6099915/44546803-184a9f80-a6e7-11e8-9639-170d98358af9.png)

**Comment by vigneshhari** [comment]
We are looking into it

**Comment by vigneshhari** [comment]
This Issue is fixed now
