### ISSUE TITLE
[Deploy] Missing person

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#918]
Missing person 

1. Add a missing link person page in  https://keralarescue.in/relief_camps/. 
2. Rearrange such a way that people finder and missing person are together. 
3. Once link is click it should go to an intro page 
4. Intro page should have button with text "Report Missing Person"  linked to http://help.keralarescue.in  

Missing person page

Kerala Flood: Report Missing persons 
കേരളം പ്രളയം: കാണാതായ വ്യക്തികളെ റിപ്പോർട്ട് ചെയ്യുക

This is a crowdsourced website that aims to track all the persons missing during the Kerala floods. Add as much information as possible so that volunteers can help search for your loved ones in the relief camps. Once you enter the details we will do the below:
The missing person details will be shown on our website prominently 
The details may be shared on Facebook and other social media to help track people 
The volunteers on ground may post the missing person details on walls or o ther prominent places within the relief camps 
We will make every effort to find the missing persons, but if the person cannot be located the details would be shared with the Police through the Thuna Portal

Help us avoid fake reports! Share at least 3 contact numbers so that we can verify the missing person report. 

കേരള വെള്ളപ്പൊക്കത്തിൽ കാണാതായ എല്ലാവരെയും ട്രാക്ക് ചെയ്യാൻ ലക്ഷ്യമിട്ടുള്ള ഒരു വെബ് സൈറ്റ് ആണ് ഇത്. സന്നദ്ധപ്രവർത്തകർ ദുരിതാശ്വാസ ക്യാമ്പുകളിൽ തിരയാൻ സഹായിക്കുന്നതിന് കഴിയുന്നിടത്തോളം വിശദാംശങ്ങൾ ചേർക്കുക. നിങ്ങൾ നൽകുന്ന വിശദാംശങ്ങൾ ഞങ്ങൾ ചുവടെയുള്ള സ്ഥലങ്ങളിൽ ഉപയോഗിക്കും:

കാണാതായ വ്യക്തിയുടെ വിശദാംശങ്ങൾ ഞങ്ങളുടെ വെബ്സൈറ്റിൽ പ്രദർശിപ്പിക്കും
ആളുകളുടെ വിവരങ്ങൾ അറിയാൻ Facebook, മറ്റ് സോഷ്യൽ മീഡിയകൾ എന്നിവയിലൂടെ വിവരങ്ങൾ പങ്കിടാം
കാണാതായ വ്യക്തികളുടെ വിശദാംശങ്ങൾ ദുരിതാശ്വാസ ക്യാമ്പ് ചുമരുകളിൽ പ്രദർശിപ്പിക്കും
കാണാതായവരെ കണ്ടെത്താൻ എല്ലാ ശ്രമങ്ങളും നടത്തും, എന്നാൽ ഞങ്ങൾക്ക് കണ്ടെത്താൻ കഴിഞ്ഞില്ലെങ്കിൽ വിശദാംശങ്ങൾ Thuna പോർട്ടലിലൂടെ പോലീസുമായി പങ്കുവെക്കപ്പെടും.

വ്യാജ റിപ്പോർട്ടുകൾ ഒഴിവാക്കാൻ ഞങ്ങളെ സഹായിക്കൂ! കാണാതായ വ്യക്തിയുടെ റിപ്പോർട്ട് ഞങ്ങൾക്ക് സ്ഥിരീകരിക്കാനായി ചുരുങ്ങിയത് 3 കോൺടാക്റ്റ് നമ്പറുകൾ പങ്കിടുക.

Ushahidi Support:-
Bobinson Bobby to handle. #917

**Comment by bobinson** [comment]
1. Add a missing link person page in https://keralarescue.in/relief_camps/.
    2. Rearrange such a way that people finder and missing person are together.
    3. Once link is click it should go to an intro page
    4. Intro page should have button with text "Report Missing Person" linked to     http://help.keralarescue.in
    5. http://help.keralarescue.in will provide a form where any one can enter the missing person report
    6. The report will be submitted to volunteers as per the ACL in #917 
    7. volunteers will verify the report and publish to social media (twitter, facebook)
    8. Volunteers will wait for reports and on not finding any feedback in 24 hours, will report to police ? [@naveenpf ]
