### ISSUE TITLE
relief-camps "Search by District" page-next option picks the previously entered district name

### ISSUE THREAD

**Issue by pkrajanand** [IEEEKeralaSection/rescuekerala#919]
### Subject of the issue
"Search by District" page-next clicks seemed to operate on previously selected districts when using the "Search by District" option across multiple districts.

### Your environment
Google Chrome  with Android 8.0
Google Pixel phone

### Steps to reproduce
I searched relief camps under Alappuzha first. Since I was checking for a particular camp, I had to traverse through multiple pages. Later I realized that the place I search does belong to Pathanamthitta. The first page of the search was fine, but second-page did display results belong to "Alappuzha" instead of "Pathanamthitta".

### Expected behaviour
Second-page for "Pathanamthitta" in that case should have displayed results belong to Pathanamthitta only obviously.

### Actual behaviour
Second-page for "Pathanamthitta" in that case dispay results belong to Alappuzha

**Comment by sriduth** [comment]
Hi Guys,

I think this is because &district= is missing in `relief_camps_list.html` Pagination :
      <li><a href="?page={{ relief_camps_pag.next_page_number }}">&raquo;</a></li>
