### ISSUE TITLE
embedd ushahidi forms to HTML pages

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#923]
### Subject of the issue
We should be able to embedd ushahidi forms to web pages.

### Your environment
all OSes and browsers

### Expected behaviour
various pages like missing persons should have ushahidi forms embedded. Please test and confirm this.

Sample code to test:

`<iframe width="560" height="315" src="https://keralarescuemap.ushahidi.io/posts/create/4" frameborder="0" allowfullscreen></iframe>`

**Comment by subinamathew** [comment]
can test on MacOS (firefox/chrome/safari), Android(Chrome/firefox). VM(Win 10 - Edge)

**Comment by bobinson** [comment]
please do

**Comment by subinamathew** [comment]
Errors Detected:
MacOS - Chrome:  Last known Location - "Use Current Location" - not allowed (by default) ( need to add allow="geolocation"  to iframe tag)

**Comment by subinamathew** [comment]
Apart from Errors working normally as expected on Chrome/ Safari/ Firefox (MacOS)


**Errors Detected:**
- MacOS - Chrome: Both Form - Last known Location - "Use Current Location" - not allowed (by default) ( need to add allow="geolocation"  to iframe tag)

- Android devices: Website **Not** responsive. 
 - Firefox : Website **Not** responsive. 
 - Chrome : Geolocation needs https:// (Android security)

- Windows: firefox: as expected
- Edge: cannot test

General Form Errors
- ALL OS - ALL Browsers: Residential Property Damage Assessment Form - Taluk &Village not autopopulated. 

- ALL OS - ALL Browsers: All forms: Number field minimum is not set as 0. Can enter of negative numbers ( not an error as it is later validated by form ) (But 0 is not allowed - infants?)

- ALL OS - ALL Browsers: All forms: Telephone number field is text field?

- ALL OS - ALL Browsers - ALL Forms: Cannot remove image once added. Can replace them 

- ALL OS - ALL browsers - Upload image can be a zip. Not validated by form. Error is not handled properly.

**Comment by bobinson** [comment]
> ALL OS - ALL Browsers: Residential Property Damage Assessment Form - Taluk &Village not autopopulated.

Cannot be done due to issues with a certain API.

> ALL OS - ALL Browsers: All forms: Number field minimum is not set as 0. Can enter of negative numbers ( not an error as it is later validated by form ) (But 0 is not allowed - infants?)

Good point and will look into this. Also the form is getting changed etc. so not sure at this point this is relevant or not.

> ALL OS - ALL Browsers: All forms: Telephone number field is text field?

I am told that this is to support zero and plus !


>  ALL OS - ALL Browsers - ALL Forms: Cannot remove image once added. Can replace them

looks to be a way the app behaves. needs close inspection. Also we need support for multiple images to be uploaded together.


>   ALL OS - ALL browsers - Upload image can be a zip. Not validated by form. Error is not handled properly.

ie no check test for the media type ?

**Comment by subinamathew** [comment]
> ALL OS - ALL browsers - Upload image can be a zip. Not validated by form. Error is not handled properly.


`ie no check test for the media type ?`
True 👍  no check for media type.
