### ISSUE TITLE
Mismatching Text on Request Help Page

### ISSUE THREAD

**Issue by ALonelyTower** [IEEEKeralaSection/rescuekerala#934]
### Subject of the issue
A browser test I had written had failed because the text for one of the links had been modified.  I don't understand Malayalam, so I'm uncertain if the former or latter translation is correct, incorrect, more(?) correct.

Home Page
![homepage_requesthelp_text_link](https://user-images.githubusercontent.com/42524361/44598112-cce7ce00-a786-11e8-8e37-e1b7efdf6fa2.PNG)

Request for Help Page
![requesthelppage_headertext](https://user-images.githubusercontent.com/42524361/44597923-2d2a4000-a786-11e8-9b61-a8cb1ac6c725.PNG)

### Steps to reproduce
1. Visit the homepage, and observer the Malayalam text in the Requst for Help link
2. Click on Request for Help link
3. Observe the Malayalam header text.

### Expected behaviour
I'm uncertain as I'm not a native speaker.

### Actual behaviour
The text on both pages should match.

**Comment by bobinson** [comment]
Ok, please confirm whether this is still an issue or not.

**Comment by ALonelyTower** [comment]
As a non-native speaker, I don't know which one is more appropriate.
