### ISSUE TITLE
SMS volunteers for damage assessment

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#942]
### Subject of the issue

New feature - Massive survey for damage assessment will start shortly

### Expected behaviour

Form to seggreate volunteers into groups based on block panchayath

1. Send SMS to volunteers and collect:

   - Personal Details ( Name, Phone, email ) 

   - District , Local Body Name
   - Available timings for survey (date, time in IST )

2. Form behavior 

   - District name should be loaded
   -  if possible auto-fill Local Body name as we type to avoid confusions
   - Available time should be stored in ISO format in the db

3. Store phone number block mapping in the db

4. block officer will call the volunteers and co-ordinate

## flow chart

![image](https://user-images.githubusercontent.com/18070249/44619874-4081fc00-a8a9-11e8-948a-79ddc7dcd88f.png)

SMS content: Visit the link and provide us with the block panchayath that you would be able to volunteer keralarescue.in/{url}

#767  -----> this has previous code. We just need to extend it to collect additional info.

**Comment by kurianbenoy** [comment]
@bobinson  are you planning to make this form to inform volunteers for Damage assessment mission?
I couldn't properly understand the feature request mentioned here, can you please elaborate?

**Comment by bobinson** [comment]
@kurianbenoy  - requirements are changing. Once its frozen, I will update here. Current work is happening in slack

**Comment by bobinson** [comment]
cc @giju
