### ISSUE TITLE
[New request] Need a icon in homepage 

### ISSUE THREAD

**Issue by naveenpf** [IEEEKeralaSection/rescuekerala#956]
We need to a new home page icon
"Missing Person/Find Person"

Move "Missing Person/Find Person" from relief campus to this link.

Currently,  "Missing Person/Find Person" are at relief camps.
https://keralarescue.in/relief_camps/

**Comment by naveenpf** [comment]
Muneeb kattody is working on this

**Comment by ntsreejith** [comment]
![report missing persons details kerala rescue in 1](https://user-images.githubusercontent.com/42038063/44625624-4fa98e00-a92b-11e8-868e-8baf43cafd80.png)
![report missing persons details kerala rescue in](https://user-images.githubusercontent.com/42038063/44625625-50422480-a92b-11e8-8f88-2c57a2822cc3.png)
Please see these will suffice

**Comment by biswaz** [comment]
LGTM

**Comment by muneebkattody** [comment]
Completed.

**Comment by biswaz** [comment]
I don't see a new icon on homepage or the person page? Point me to the change pls

**Comment by muneebkattody** [comment]
new Icon Means New Link To Missing Persons And Finding Persons.

**Comment by muneebkattody** [comment]
![img_e3835](https://user-images.githubusercontent.com/31755549/44626463-876c0200-a93a-11e8-8602-0bc83ec9cc55.JPG)
