### ISSUE TITLE
Implementing predictive search to fill in LSB

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#957]
### Subject of the issue

**LSB** = Local Self Governing Body

We have large list that contains the names of Local Self Governing Bodies. We need a mechanism in Ushahidi forms to auto fill the form items as opposed to using a drop down menu.

ideas : 

- use ushahidi API and trigger a backend action when someone clicks in the text area of LSB in the data collection form
- The backend should quickly do a look up based on the user input. say, Ale should give "aleppey" etc
- explore the possibility of this in the hosted instance.

pointers:

ushahidi API, list of LSBs, Lucene

**Comment by naveenpf** [comment]
+ Administrative boundaries - Taluk and Village

**Comment by ja8zyjits** [comment]
where do we update ushahidi code base for our instance? like where do write code that will modify the behavior of any fields in our ushahidi?

**Comment by bobinson** [comment]
This is implemented cc @giju

![image](https://user-images.githubusercontent.com/18070249/44948044-2fe6fe00-ae34-11e8-9dee-8dc8068a2a16.png)


@biswaz  - please publish the code via github
