### ISSUE TITLE
Create a Map layer of Rescue requests. 

### ISSUE THREAD

**Issue by naveenfrancis** [IEEEKeralaSection/rescuekerala#96]
- [ ] Use the geolocation and create a map. 

- [ ] Map should have only open requests.

**Comment by geohacker** [comment]
Most straightforward approach:

* add an API end point to return requests in GeoJSON format something like GET `/help-requests/geojson` 
* then plugin in Mapbox GL JS to the view. Example https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

**Comment by nishadhka** [comment]
How about using https://www.ushahidi.com, it has good use cases in emergency response situation, gives an comprehensive web map utility with SMS and other tools

**Comment by bobinson** [comment]
Please don't make the location info mandatory as friends or family may be requesting the information and those who are requesting information may not be having exact location information.

**Comment by nishadhka** [comment]
It is basically for volunteers to enter the location details getting from SOS, to have a "Flooding and inundation collaborative mapping", it gives imporved perspective and visualisation of ground situation

**Comment by msrshahrukh100** [comment]
will adding something like - https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete to the field solve this issue, so that those making requests can enter the location?

**Comment by naveenpf** [comment]
https://keralarescue.in/map
