### ISSUE TITLE
Data cleansing

### ISSUE THREAD

**Issue by biswaz** [IEEEKeralaSection/rescuekerala#974]
Clean duplicate Person/RescueCamp and redundant LSB data

**Comment by naveenpf** [comment]
Issue taluk was entered free text in registration of Camps. 
Same taluk was entered in different ways. 
Clean taluk from backend too. 
https://keralarescue.in/dmotal/?district=all

**Comment by biswaz** [comment]
Progress: All duplicate person entries marked with is_dup flag. Change yet not reflected on frontend.
Since csvimports brought in some dups, save function of model was overrided to reject dups universally, on save()

**Comment by vigneshhari** [comment]
Closing this issue since data Cleansing is over and csv issues are fixed
