### ISSUE TITLE
HTTP Parameter Override

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#983]
### Subject of the issue
HTTP Parameter Override

https://www.keralarescue.in/find_people/?address__icontains&camped_at&district&gender&name__icontains&notes__icontains&page=396&phone__icontains

Unspecified form action: HTTP parameter override attack potentially possible. This is a known problem with Java Servlets but other platforms may also be

### Steps to reproduce
https://www.acunetix.com/blog/whitepaper-http-parameter-pollution/

![image](https://user-images.githubusercontent.com/18070249/44891777-c9ac8f00-acfe-11e8-8c59-6b29431e7fa7.png)

Tested with OWASP Zap

**Comment by vigneshhari** [comment]
The forms are created by Django dynamically and is not hardcoded , In this case the same URL endpoint is used for the form as well as rendering the initial page which is why the action is left unspecified

**Comment by bobinson** [comment]
ok, understood. 

closing as false positive.
