### ISSUE TITLE
Docker-compose on OS X does not start Postgres instance

### ISSUE THREAD

**Issue by pkrajanand** [IEEEKeralaSection/rescuekerala#985]
### Subject of the issue
docker-compose, from the cloned environment at 3477f74, do not open network connection for Postgres instance, if port(even the default one) is not explicitly specified in the yaml file. However, start log do not indicate any false step.
### Your environment
* OS-X 10.13.6

### Steps to reproduce
1. As is given in the ReadMe, run ``` sudo sh docker.sh ```
2. Monitor the opened network ports 

> RAJANAND-P-Ks-MacBook-Pro:~ rajanandpk$ sudo lsof -PiTCP -sTCP:LISTEN
> Password:
> COMMAND     PID       USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> rapportd    347 rajanandpk    3u  IPv4 0xa1238a8b2741dbeb      0t0  TCP *:59265 (LISTEN)
> rapportd    347 rajanandpk    4u  IPv6 0xa1238a8b25c89b43      0t0  TCP *:59265 (LISTEN)
> Google      388 rajanandpk  169u  IPv4 0xa1238a8b28ce328b      0t0  TCP localhost:60575 (LISTEN)
> cupsd      1087       root    5u  IPv6 0xa1238a8b3f668dc3      0t0  TCP localhost:631 (LISTEN)
> cupsd      1087       root    6u  IPv4 0xa1238a8b3f78f54b      0t0  TCP localhost:631 (LISTEN)
> pgAdmin4  10264 rajanandpk   15u  IPv4 0xa1238a8b25219beb      0t0  TCP localhost:50798 (LISTEN)
> com.docke 13352 rajanandpk   19u  IPv4 0xa1238a8b2770192b      0t0  TCP *:8000 (LISTEN)
> com.docke 13352 rajanandpk   20u  IPv6 0xa1238a8b3f669f03      0t0  TCP localhost:8000 (LISTEN)
> com.docke 13352 rajanandpk   23u  IPv4 0xa1238a8b2748dbeb      0t0  TCP *:6379 (LISTEN)
> com.docke 13352 rajanandpk   24u  IPv6 0xa1238a8b3f667c83      0t0  TCP localhost:6379 (LISTEN)

3. Observe that no process run to listen to 5342, the postgres one.

### Expected behaviour
Postgres instance must be running on a specified or default port.

### Actual behaviour
It doesn't.

**Comment by bobinson** [comment]
@pkrajanand  - do you mind sharing steps starting docker in the wiki ? 

1. https://github.com/IEEEKeralaSection/rescuekerala/wiki

2. quick steps here also can help

**Comment by pkrajanand** [comment]
There is a section "Docker" already within the Readme (https://github.com/IEEEKeralaSection/rescuekerala#requirements) which I found quite sufficient content-wise.

**Comment by pkrajanand** [comment]
@bobinson Moved info to "wiki" (https://github.com/IEEEKeralaSection/rescuekerala/wiki/Using-Docker) and hyperlinked in Readme through pull-request https://github.com/IEEEKeralaSection/rescuekerala/pull/991.
