### ISSUE TITLE
Issue and PR templates

### ISSUE THREAD

**Issue by sreecodeslayer** [IEEEKeralaSection/rescuekerala#99]
Relating this to the idea of issue and PR template from discussion #92 

Any criteria you guys wish to  have or mandate on the template.
Am currently preparing a template, let me know what you guys have in mind

**Comment by bobinson** [comment]
List of Browsers: 

Android browsers : UC Browser, Android Default Webview (which will be opened from Whatsapp etc), Google Chrome, Opera flavours

iOS - iOS default web view, Safari

**Comment by naveenpf** [comment]
Not required

**Comment by bobinson** [comment]
> Not required
Why ?
