### ISSUE TITLE
survey application - status

### ISSUE THREAD

**Issue by bobinson** [IEEEKeralaSection/rescuekerala#996]
### Subject of the issue

Which is the current survey application ?

Ionic based custom application.

## Applications tested

1. Ushahdi 
2. KoboToolbox 
3. Ionic based custom application

## Evaluation Criteria

The GO below is used for  evaluation criteria & final selection criteria can be defined based on the same.

[GO Ms No 18 2017 DMD.pdf](https://github.com/IEEEKeralaSection/rescuekerala/files/2351423/GO.Ms.No.18.2017.DMD.pdf)

#### 1. Ushahidi ( http://help.keralarescue.in/)

FOSS: Yes
(LICENSE: FOSS)
Offline Capacity : Tested and verified by volunteers across Kerala
Networks types tested :  GSM, 3G, 4G, LTE + few networks in USA
Operators tested: Vodafone (2G,3G,4G),  Jio (LTE), BSNL, Airtel & Idea
Indoor vs Outdoor : Tested
Location accuracy : 3 to 4 meters
Ability to upload photos : any number of photos
OS support : Android 4.4+ (  lollipop, marshmello, nougat, oreo)  and iOS 
Was it used before in other countries : Yes (Nepal, Syria, Chili, Haiti, Kenya, USA ... )
Phones Tested: Moto C plus, Lenovo K8+, iPhone 6S, iPhone 7, Micromax canvas, Nokia3, Redmi note 5, note 5 pro
Web browsers tested : Google Chrome, Chromium, Firefox (Linux, macOS and Windows), Safari (macOS)

Logical Branching for data collected : not Available
Number of people tested : ~ 24 under co-ordinated fashion

Deployment types: Self Hosted in AWS India with Scalable infrastructure, Hosted donated by Ushahidi Non-Profit

Security Audits: OWZAP ZAP is used for through audit & code has 3rd party audits

User creation : Possible via secure API, Mode of Difficulty: HIGH
Permissions: Form based permissions are  possible
Transparency: Peer review and validation of collected data possible via crowdsourced means & hiding sensitive personal information

Ready for Rollout:  yes, (Completed on August 18th without field testing, Full and complete field testing completed on 23rd August 4:00 AM IST)

Cost involved : Ushahidi  Inc asked for agreements and charges for migration. Which they later agreed to waive off subject to approval of funding from Gates Foundation via UNICEF

#### 2. KoboTool box ( http://kobo.keralarescue.in/ )

FOSS: Yes
(LICENSE: FOSS)
Offline Capacity : Tested and verified by ICFOSS
Networks types tested : unknown
Operators tested: unknown
Indoor vs Outdoor : Tested

Location accuracy : 3 to 4 meters
Ability to upload photos : unknown

OS support : unknown

Was it used before in other countries : Yes (Nepal by UN/UNDP/UNICEF ), USA, India (for wildlife surveys, river basin survey at Thrissur, KSEB high tension line survey, Kerala, Pollution testing )
Phones Tested: Moto C-plus

Logical Branching for Data collected: Available
Number of people tested : unknown

Deployment types: Self Hosted in state data center with SPOF

Security Audits: Unknown

Cost involved : scalable infrastructure will cost

Ready for Rollout:  unknown

User creation : Possible via secure API, Mode of Difficulty: LOW
Permissions: Form based permissions are NOT possible

Transparency: Unknown

### 3. Custom Application  ( https://play.google.com/store/apps/details?id=in.gov.ikm.disasterreliefsupport )

FOSS: unknown
LICENSE: unknown
Source code : not available
Offline Capacity : unknown
Networks types tested :  unknown
Operators tested: Unknown
Indoor vs Outdoor : Unknown
OS support : Unknown
Was it used before in other countries : No
Phones Tested: Unknown
Logical Branching for Data collected: unknown
Number of people tested :Unknown
Deployment types: Unknown
Security Audits: Unknown
User creation : Possible via unsafe API
Permissions: unknown
Transparency: Unknown
Ready for Rollout:  May be/Yes
Cost involved :Unknown
Ability to upload photos : unknown

## volunteer registration and on-boarding

via : https://volunteers.rebuild.kerala.gov.in/ 

## Selection criteria

Define the parameters based on which each solution is assessed and finally a solution is selected.

TBD / unknown

**Comment by bobinson** [comment]
cc: @akshaim

**Comment by syam3526** [comment]
Do we need the hosted ushahidi since they are asking for way too much money. When we can self host it

**Comment by bobinson** [comment]
We can self host it In India & thus the issue data migration is not there.

**Comment by bobinson** [comment]
1.3  Offline Capacity : Tested and verified by volunteers across Kerala

![img_7196](https://user-images.githubusercontent.com/18070249/45134529-9794a480-b1b8-11e8-8f8e-7d6e608b727d.PNG)


![img_7195](https://user-images.githubusercontent.com/18070249/45134537-9bc0c200-b1b8-11e8-8c59-d57d545c3ac5.jpg)
